### ISSUE TITLE
User last_connexion and nb_connexions

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1084]
Hello,

Is it possible to add fields `last_connexion` and `nb_connexions` in table `main.user` like it's done for the short urls (`main_static.shorturl.last_hit` and `main_static.shorturl.nb_hits`)?

I don't know if easily implementable or if it requires a specific development.

Thank you for your feedback on this request.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-518
