### ISSUE TITLE
Eggs cleaner

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1093]
Has anyone tried to apply point 6 of chapter: http://docs.camptocamp.net/c2cgeoportal/master/integrator/update_application.html#updating-c2cgeoportal to a Windows instance ?

Because on my side, the console tells me that it cannot install ` buildout.eggscleaner`... (and obviously crashes...)

**Comment by sbrunner** [comment]
We don't have anymore the egg cleaner in the master branch !
