### ISSUE TITLE
Print with IE11

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1112]
Does the print works with IE11?

What I do:
* Print PDF
* _(print in progress...)_
* _(document ready)_
* Download
* Open --> Nothing happened but the url is something like `printproxy/xxxxx.pdf.printout`

If I try to click Save instead of Open, there is an error "file cannot be downloaded"

Thanks for any feedback on this one.

**Comment by sbrunner** [comment]
Is it still valid ?

**Comment by rbovard** [comment]
Yes sorry, I think it was related to our IE config (I didn't change anything on my side and it worked).
