### ISSUE TITLE
Oriented symbols with print rotation

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1136]
When printing with a rotation, the symbols defined with an `ANGLE` aren't well oriented (the print rotation isn't taken in consideration).

![image](https://cloud.githubusercontent.com/assets/4549666/5069349/7c9644a0-6e59-11e4-9e83-bd1d5c108558.png)

**Comment by rbovard** [comment]
I reopen this one because it seems to not working anymore with MapServer 7.

I tried to remove

```
encodeLayer: {
useNativeAngle: false
}
```

But the result is always wrong.

Any ideas?

**Comment by sbrunner** [comment]
On witch layer is it?

**Comment by rbovard** [comment]
It's always on private layers...

2016-04-07 9:11 GMT+02:00 Stéphane Brunner <notifications@github.com>:

**Comment by sbrunner** [comment]
Then can we have thy symbol definition?

**Comment by rbovard** [comment]
https://github.com/camptocamp/nyon_c2cgeoportal/blob/e6b6953c8f5705083aa8217c386e90d255d4e2bb/mapserver/mapfiles/reseau_eau.map.mako#L314-L480

**Comment by sbrunner** [comment]
Merci :-)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-570
