### ISSUE TITLE
Strange behaviour when printing layer with minscale

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1146]
I have a layer with `MAXSCALEDENOM` defined and it appears in the print depending the orientation of the page.

Steps to reproduce:
- http://map.nyon.ch/s/YX7A
- Print A3 Portrait 1:10'000 -> Points doesn't appear -> OK
- Print A3 Landscape 1:10'000 -> Points appear -> **KO**

Is the scale handled differently according to the format? Because it works fine with A4 Portrait, A4 Landscape, A3 Portrait but not with A3 Landscape.

![image](https://cloud.githubusercontent.com/assets/4549666/5181917/9b9edebe-749b-11e4-9bab-ad594acd3bbe.png)

**Comment by sbrunner** [comment]
Is it fixed ?

**Comment by rbovard** [comment]
More or less...

In fact, you need to be careful when setting min/max scales because if values are to close to the limit, the printed map will not reflect the displayed map for the same scale.

Maybe add a note in print documentation about it.

**Comment by sbrunner** [comment]
Moved to Jira

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-500
