### ISSUE TITLE
WMTS layers with min/max resolutions

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1152]
When setting min and max resolutions on a WMTS layer, the tiles are requested even when outside the range.

I'm sure to set correctly the resolutions because the layer is gray and the icon to zoom to max resolution is here if I'm outside range.

**Comment by sbrunner** [comment]
Actually it's the expected behavior...

**Comment by rbovard** [comment]
Ok, so you send a lot of useless queries that all result with 404 errors...

**Comment by sbrunner** [comment]
Effectively...

**Comment by rbovard** [comment]
I have an issue about this one.

I noticed that the print plugin queries the tiles of lower resolution (print resolution 1 -> tiles resolution 0.25) so I generated them on a layer with scales restictions. And now, because the tiles are requested even of the visibility of the layer, the tiles shows when I don't want them to.

So my question is if it's possible to disable queries when outside the range of the layer?

**Comment by sbrunner** [comment]
Do you have an example ?

You need this for ?:
- The CGXP application
- The Print version 2
- The Print version 3

**Comment by rbovard** [comment]
Yes sure: http://map.nyon.ch/demo/s/UiP5

If you zoom in (1:250), the layer in the TOC become gray but the tiles are asked. For me it's a bug between the status of the layer in the TOC and the display on the map.

Not concerning the print, I mentionned it because when printing, the tiles of 2 level after are requested. So to be able to print at 1:500, I autorized the layer in MapFile until ~1:100 and limit the visibility in admin panel.

Do you see what I mean?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-519
