### ISSUE TITLE
Disabling WMS GetCapabilities

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1154]
When disabling the WMS GetCapabilities in `config.yaml.in`, there is a 404 error when trying to get this file (which is correct), but the WMS can still be queried with another client like QGIS.

Is it the expected behaviour?

**Comment by sbrunner** [comment]
Is it fixed ?

**Comment by rbovard** [comment]
No, but there is nothing to fix on your side (I misunderstood this functionality).
