### ISSUE TITLE
EPSG.io API endpoints will be deprecated after the 1st of February 2025

### ISSUE THREAD

**Issue by petr-hajek** [camptocamp/c2cgeoportal#11570]
https://github.com/camptocamp/c2cgeoportal/blob/6fd10fd2f2c76c74479ea9870d8be31f6a932d22/geoportal/c2cgeoportal_geoportal/scripts/pcreate.py#L280

HI, EPSG.io API endpoints will be deprecated after the 1st of February 2025: https://epsg.io/docs#migration

This will affect the functionality of your epsg2bbox method. I am not sure to what extent it is used in your project.

You can easily replace the endpoint with a new endpoint from MapTiler. However the new endpoint requires MapTiler API key. You could adjust the code to allow users of this project to add their MapTiler API as an env variable. They can get the API key with a Free plan (up to 100K request per month).

More extensive documentation: https://documentation.maptiler.com/hc/en-us/articles/360020950098-How-to-migrate-from-EPSG-io-to-MapTiler-Coordinates-API

**Comment by sbrunner** [comment]
Thanks @petr-hajek for the notification :-)

**Comment by petr-hajek** [comment]
Alternative would be to fetch the https://epsg.io/{srid}.proj (if you have the exact coors id) and then implement the transformation yourself using pyproj
