### ISSUE TITLE
Unique id for layers in the theme service

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/c2cgeoportal#1166]
Each node in the themes tree should have its own unique id.

**Comment by sbrunner** [comment]
Why ?

**Comment by pgiraud** [comment]
See https://github.com/Geoportail-Luxembourg/geoportailv3/commit/2018c3b6fe0cda9c62168e5e6e50ee80040ed78b#commitcomment-9045836

**Comment by pgiraud** [comment]
Actually we need a unique id for the layers.
