### ISSUE TITLE
Default basemap functionality in mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1178]
It seems that `default_basemap` functionality doesn't work with mobile application.

Is there a way to achieve this?

**Comment by asaunier** [comment]
> It seems that default_basemap functionality doesn't work with mobile application.

Indeed. This feature is not implemented in the mobile app.

> Is there a way to achieve this?

Not without making some new dev.

**Comment by rbovard** [comment]
Ok, thanks for the answer.

**Comment by rbovard** [comment]
You close it because the mobile will have the same functionality as the desktop version since it's the same, right?

**Comment by sbrunner** [comment]
Yes with ngeo it will be the same component

**Comment by rbovard** [comment]
Great, thanks!
