### ISSUE TITLE
Documentation for mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1179]
After installing mobile application, I noticed some points in the documentation:

* __Building the mobile application__
http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/mobile.html?highlight=sdk#building-the-mobile-application
 * Also need to create the `touch` folder
 * Cannot acces `mobile_dev`

* __UI strings translations__
http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/mobile.html?highlight=sdk#ui-strings-translations
 * It's now based on desktop translations

**Comment by sbrunner** [comment]
> Also need to create the touch folder

it should be created by the update template ...

> Cannot acces `mobile_dev`

What's your error (where) ?
