### ISSUE TITLE
WFS GetFeature queries on mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1181]
When querying a feature without any attributes on mobile application, the result appears with nothing. In desktop version, the message "no result" is displayed instead of opening an empty window.

You can reproduce it on your demo instance with layer "Caméra".

![image](https://cloud.githubusercontent.com/assets/4549666/5760161/110a7370-9cd3-11e4-9cba-f1b4fd2b2c11.png)

**Comment by rbovard** [comment]
@sbrunner Sorry to ask, but is it possible to have a feedback on this one (and if it can be solved in `1.5` branch)?

**Comment by pgiraud** [comment]
@rbovard Hi. FYI, I have a bit of time this week to dig into this issue.

**Comment by rbovard** [comment]
Cool, thanks for the info.

**Comment by pgiraud** [comment]
What's the URL to demo instance?

**Comment by pgiraud** [comment]
Fixed via #1193.

**Comment by rbovard** [comment]
Thanks @pgiraud!
