### ISSUE TITLE
Mobile - Marker when passing coordinates

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1195]
Is there an "easy" way to implement the display of a marker in the mobile app when passing coordinates & zoom through the URL ?

The idea would be to add a custom variable in the URL and to display the map overlaid by a marker (located on the passed coordinates) if this variable exists, something like:

http://example.com/mobile?map_x=554225&map_y=200210&map_zoom=12&marker=1

(This is fake...)
![example](https://cloud.githubusercontent.com/assets/1681332/5902459/e19265c0-a57a-11e4-8fb3-92b807725d05.png)

**Comment by kalbermattenm** [comment]
@gnerred and @rbovard, would that be something interesting for you ?

**Comment by gnerred** [comment]
Yes it would be interesting

**Comment by rbovard** [comment]
Why not, but maybe also think about adding this to the desktop version.

I like the way how OSM.org included this feature in the permalink:

![image](https://cloud.githubusercontent.com/assets/4549666/5918082/d44d1f72-a624-11e4-9e53-5d488cc5293b.png)

**Comment by kalbermattenm** [comment]
Could you give an example of permalink ? I can't reproduce it (yeah... don't ask...) on openstreetmap.org and I would like to see what is the name of the variable ?

**Comment by rbovard** [comment]
It seems the marker can be not in the middle of the map: http://www.openstreetmap.org/?mlat=46.38231&mlon=6.24008#map=19/46.38231/6.24008

**Comment by rbovard** [comment]
FYI to add the marker when generating the permalink:

![image](https://cloud.githubusercontent.com/assets/4549666/5918647/7af63b28-a62b-11e4-8a57-645b7eae43ef.png)

**Comment by kalbermattenm** [comment]
Thanks I did see that, but didn't get that there wasn't a query variable explicitly defining the marker...

Personally, I would rather have a marker added only when it is explicitly declared as a variable... Something like `...&addMarker`

**Comment by rbovard** [comment]
Yes I think your first proposal is fine, the marker is in the middle of the map.

The reference to OSM was more about how to add a marker when generating a permalink.

**Comment by sbrunner** [comment]
Just an additional info:
With Ext it's not possible to have a paramer like `marker=1` the parameter should be named as `map_marker` if it's the map component who manage the marker.
Otherwise that looks good :-)

**Comment by kalbermattenm** [comment]
I have done something...

The code is here: https://github.com/camptocamp/sitn_c2cgeoportal/pull/852

The demo is here: http://sitn.ne.ch/dev_internet/mobile/?map_x=549600&map_y=206050&map_zoom=8&map_marker=1

Yeah I know... The marker is not the most beautiful marker of all time...

I followed @sbrunner's advice and called the variable `map_marker`

This modifies code which is part of the `c2cgeoportal`, do you think it would be good to directly integrate it into this one ?

**Comment by gnerred** [comment]
Looks good, but you have two markers, one in the center and one on top left. 

I think it will be usefull to add a tooltip to the marker. Instead of map_marker=1, you could set map_marker=BLABLA and the blabla becomes a tooltip. We did that on the very first version of GeoMapfish desktop...

http://map.cartoriviera.ch/theme/cadastre?map_x=560000&map_y=142000&map_zoom=5&map_tooltip=BLABLA

**Comment by kalbermattenm** [comment]
> Looks good, but you have two markers, one in the center and one on top left. 

Cool... I don't know how I managed that...

> I think it will be usefull to add a tooltip to the marker. Instead of map_marker=1, you could set map_marker=BLABLA and the blabla becomes "interrogeable". We did that on the very first version of GeoMapfish desktop...

Hmmm... This is going to be quite complicated on the mobile... We don't have `Ext.Window` and to integrate this directly into the map using seems quite complicated to me...

Maybe @pgiraud would have some advices on this...

In the mean time, I'm going to make the upper left marker disappear ;-)

**Comment by gnerred** [comment]
Okay so forget my proposal if it is not super easy. You could also look for a smarter marker ;O)

**Comment by gnerred** [comment]
For the tooltip, couldn't you use the same methods as in the API ?

**Comment by kalbermattenm** [comment]
>  You could also look for a smarter marker ;O) 

Indeed, that would be a good idea...

> For the tooltip, couldn't you use the same methods as in the API ? 

It there a tooltip in the API ? Would you have an example ?

**Comment by kalbermattenm** [comment]
I have a weird side effect...

Two markers (one on the top left):
http://sitn.ne.ch/dev_internet/mobile/?theme=mobile_default&baselayer_ref=plan_ville&map_x=549600&map_y=206050&map_zoom=8&map_marker=1&tree_layers=

One marker (as expected...):
http://sitn.ne.ch/dev_internet/mobile/?theme=mobile_default&baselayer_ref=plan_ville&map_x=548947&map_y=206266&map_zoom=8&map_marker=1&tree_layers=

I just moved a bit the map (`map_x` and `map_y` are slightly different).

I will have to investigate that, because I checked in the OL layer containing the marker and there is only one of them...

**Comment by kalbermattenm** [comment]
OK, I found the bug and modified the image.

@gnerred, what do you think (use the above links, but don't forget to empty your cache...)

**Comment by gnerred** [comment]
Yeah that's cool, good job :O)

**Comment by sbrunner** [comment]
Nice :-)

**Comment by kalbermattenm** [comment]
Thanks ;-)

@sbrunner, would it make sense to submit a PR with that (cleaned up, CONST_changelog updated and adding documentation) to the `c2cgeoportal` project (branch 1.5) ?

**Comment by sbrunner** [comment]
For me in the master branch it's relay good, but for me it's a too big change for the 1.5 branch...

**Comment by kalbermattenm** [comment]
@gnerred and @rbovard, I suggested a <a href="https://github.com/camptocamp/c2cgeoportal/pull/1204">PR</a> for the mobile app.

I didn't know is that in the desktop app there is already something like that. For instance, try:

http://sitn.ne.ch/theme/main?map_x=538075.0&map_y=199075.0&map_zoom=10&map_crosshair=1

**Comment by rbovard** [comment]
Thanks for the work!

I didn't know about this functionality, it's a little hidden since we cannot create permalink with it enabled :)

**Comment by gnerred** [comment]
Thanks @kalbermattenm

**Comment by sbrunner** [comment]
done
