### ISSUE TITLE
Difficulty to query with Chrome

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1201]
After some tests with Chrome on an Android Tablet, I noticed that it's very hard to make a GetFeature, even after update to `1.5.3dev-20150126`.

In fact, when "clicking" on the map, the map moves so the GetFeature is not fired. I tested with the native Android browser, the map doesn't move when clicking on it so it's more much simple to make a query.

I don't know if it's related to C2Cgeoportal or OpenLayers.

@kalbermattenm @gnerred Did you noticed the same behaviour?

**Comment by sbrunner** [comment]
It's related of OpenLayers, than witch version of CGXO/OpenLayers do you use ?

**Comment by kalbermattenm** [comment]
@rbovard, not as far as I know... I never heard about the "clicking-move" issue...

**Comment by rbovard** [comment]
CGXP branch 1.5 https://github.com/camptocamp/cgxp/commits/7814a1a514355bb5dbb965625140e68231d84ac0

**Comment by gnerred** [comment]
I can reproduce. But if you do a very quick touch, there is no problem. But I can well understand that in administrations, the touch can be slow... ;O))

**Comment by rbovard** [comment]
Ha ha, thanks @gnerred !

Yes if you tap very very quickly, you have a chance to succeed but 9/10 times, the map moves...

**Comment by gnerred** [comment]
It is not so evident on my Samsung Galaxy tab active. I succeed 9/10 when I tap quickly (but not very very quickly)

**Comment by rbovard** [comment]
Hmm ok, so it's related to the hardware?

I test here with a Galaxy Tab S, I can give a try at home with a Galaxy Tab 2 to confirm that.

**Comment by rbovard** [comment]
I tested with a Galaxy Tab 2 yesterday evening and the issue was not present. So I think it's happening on recent tablets, which have higher capacities...

Maybe someone could test with another recent tablet to confirm that?

**Comment by rbovard** [comment]
@sbrunner I see that you removed the milestone, so it won't be fixed?

**Comment by sbrunner** [comment]
The solution I can do is to do a click with a pixel tolerance of 5px.
The problem is that the longpress is managed by SenchaTouch and he can't have any tollerence...

**Comment by sbrunner** [comment]
Example: http://geomapfish-demo.camptocamp.net/sbrunner/mobile

**Comment by rbovard** [comment]
I just tried your example and it works a lot better than http://geomapfish-demo.camptocamp.net/1.6/mobile !!

For the record, the map is still moving on the "click" but the getfeature is fired, so I think it's a good workaround.

Thanks a lot!
