### ISSUE TITLE
Openlayers error in admin interface

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1217]
I get an error when a page of admin interface contains an Openlayers map : 

Uncaught TypeError: undefined is not a function
on following line
new OpenLayers.Layer.OSM("OSM"),
    'POLYGON((710189.563857429 5896129.24645693,712024.052614936 5825195.68388646,797633.524960828 5824584.18747307,796410.532424497 5896129.24626647,710189.563857429 5896129.24645693))'
);

The map does not display.

**Comment by asaunier** [comment]
Hi Daniel,
with what page and what version of GMF?

**Comment by gnerred** [comment]
Hi Alex,

For example : 
http://map.cartoriviera.ch/main/wsgi/admin/RestrictionArea/46/edit
http://map.cartoriviera.ch/main/wsgi/admin/Role/46/edit

CGXP :  0a283d42b230ad4a090db06c2f6f4272af03ad99
GMF : 1.5.2 in indicated in version.cfg

**Comment by sbrunner** [comment]
There is an error in this package version (in the build), I should create an new version, or you can use a version 1.5.3dev ...

Sorry for that :-(

**Comment by gnerred** [comment]
Can I keep the CGXP version I mentionned, and install the 1.5.3 dev ? Are there know issues with this version ? I also could live with that Openlayers error, it is not blocking

**Comment by sbrunner** [comment]
> Can I keep the CGXP version I mentionned, and install the 1.5.3 dev ?

Yes :-)

> Are there know issues with this version ?

With the 1.5.3dev ? 

* Yes but none of them are big issues:
https://github.com/camptocamp/c2cgeoportal/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.5.3

> I also could live with that Openlayers error, it is not blocking

ok :-)
