### ISSUE TITLE
External WMS Layer: GetFeatureInfo returns Geometry only -> no result shown on map

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1222]
Reproduce:
- Integrate a WMS layer in the admin interface that has no attributes
- do a query (getFeatureInfo) on this layer
- -> there are no results shown in the map (of course there are no results in the FeatureGrid/Window, but the Service returns a geometry, so why can't it be shown only on the map?)

Example:
Query on http://dev.donatsch.ch/s/KkW3

**Comment by sbrunner** [comment]
We don't know what to do with a feature without any attribute ... a table without any columns looks very strange !

**Comment by eleu** [comment]
show it in the map, but don't show it in the result table.

**Comment by sbrunner** [comment]
:-/, than looks like a bug ...

**Comment by tsauerwein** [comment]
> :-/, than looks like a bug ...

What about showing a message like `No attributes available` instead of the result table?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-520
