### ISSUE TITLE
External WMS Layer: GetFeatureInfo not supported -> no results

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1223]
In the case of a external WMS Service, it might not support GetFeatureInfo on some layers.

According to the OGC Specs, it's up to the client side to only ask the layers that support GetFeatureInfo.

At the moment, one GetFeatureInfo request for all layers in a group is done, instead of requesting separately. What would it mean to do separate requests?

Example:
http://dev.donatsch.ch/s/raLr

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-521
