### ISSUE TITLE
Prevent the egg cleaner from running useless parts

### ISSUE THREAD

**Issue by asaunier** [camptocamp/c2cgeoportal#1239]
As for now when running the eggs cleaner:
```
./buildout/bin/buildout -c CONST_buildout_cleaner.cfg
```
all the parts are run, including the print deploying, JS/CSS buildong as well as the mobile stuff. Which is useless and takes a while.
Shouldn't CONST_buildout_cleaner.cfg excludes all those parts?

**Comment by sbrunner** [comment]
If he don't run thoes part he will uninstall all the required eggs and  it's not what we want ...

**Comment by asaunier** [comment]
OK, too bad :(
Thanks for the explanation! Then closing the issue.
