### ISSUE TITLE
Translation of Raster Layer Name Key

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1244]
https://github.com/camptocamp/c2cgeoportal/blob/master/doc/integrator/raster.rst states the terms mns and mnt are simply translatable by the client.

I tried to translate them in /project/static/js/Proj/Lang/de.js, but this doesn't help.

Example: http://mapfish-geoportal.demo-camptocamp.com/eleu-demo/wsgi/?lang=de still has the term "mnt" instead of the translation "DTM".

1. Should they be translated in the plugin / CGXP?
2. Will the mnt also be translated in the exported CSV?

**Comment by asaunier** [comment]
I had the same question a few weeks ago. According to my investigations, as is, the raster names are not translatable despite what the doc says...

**Comment by eleu** [comment]
OK thanks @asaunier ! I will tempt a PR to correct the docs ;)

**Comment by rbovard** [comment]
(Why not fix the plugin?)

I had the same question when I implemented the elevation tools :)

**Comment by sbrunner** [comment]
moved to https://github.com/camptocamp/cgxp/issues/918
