### ISSUE TITLE
disable OGC proxy gives an error

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1282]
related to the commit https://github.com/camptocamp/c2cgeoportal/commit/a6fe1285daa5fa911f772f127f66ce8c70c59866

following the doc in
http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/security.html?highlight=ogc#enable-disable-the-ogc-proxy

```ogcproxy_enable: false``` gives the following error:

```
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]   File "/home/vvmalbre/geoview/buildout/eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/util.py", line 56, in fix_call
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]     val = callable(*args, **kw)
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]   File "/home/vvmalbre/geoview/bl_gis2012/__init__.py", line 113, in main
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]     config.include('c2cgeoportal')
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]   File "/home/vvmalbre/geoview/buildout/eggs/pyramid-1.5.1-py2.7.egg/pyramid/config/__init__.py", line 755, in include
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]     c(configurator)
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]   File "/home/vvmalbre/geoview/buildout/eggs/c2cgeoportal-1.5.3-py2.7.egg/c2cgeoportal/__init__.py", line 218, in includeme
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199]     if config.get_settings().get("ogcproxy_enable", "true").lower() in ["true", "yes", "1"]:
[Tue Mar 03 16:25:18 2015] [error] [client 192.168.25.199] AttributeError: 'bool' object has no attribute 'lower'
```

also, these options dont work:

- ```ogcproxy_enable: False``` -> same error as above
- ```ogcproxy_enable: 'false'``` -> viewer.js does not work

**Comment by sbrunner** [comment]
`ogcproxy_enable: toto` should work, but it's just a workaround ...

**Comment by eleu** [comment]
update: 
> - ```ogcproxy_enable: 'false'``` -> viewer.js does not work

=> not relevant, the viewer.js did just not work because there was still an OGC proxy related line in viewer.js

**Comment by eleu** [comment]
I confirm it works fine with `ogcproxy_enable: toto`

**Comment by sbrunner** [comment]
The proxy host should also be removed in the `viewer.js`
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/+package+/templates/viewer.js_tmpl#L13
I will update the Documentation
