### ISSUE TITLE
mobile - cache control on config.js

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1315]
in the mobile interface, the cache control is not set correctly for the config.js file, 
meaning the file stay in cache in the browser and is only refreshed when force-reloading the mobile interface.
this bug is especially visible on an iPad (it happens only sometimes on pc desktop browser)

**Comment by rbovard** [comment]
Is the issue #1305 related to this one?

**Comment by sbrunner** [comment]
Probably yes :-)

**Comment by rbovard** [comment]
Cool :)

**Comment by sbrunner** [comment]
The cache control is correct but the role is missing in the query ...
