### ISSUE TITLE
prefered Linux Distribution + version + prerequirements?

### ISSUE THREAD

**Issue by vlasvlasvlas** [camptocamp/c2cgeoportal#1331]
Hi, i was going to try (again) a c2cgeoportal server installation.

Starting from zero,

whats the reccomended Linux Distro + version? i dont seem to find that information / requirement anywhere.

thanks!

**Comment by sbrunner** [comment]
Hello,

Debian Wheezy or Jessie :-)

CU
Stéph

**Comment by vlasvlasvlas** [comment]
oki thanks, ill try again to install c2cgeoportal server! hope this time works :)

**Comment by vlasvlasvlas** [comment]
32 or 64 bits? txs

**Comment by vlasvlasvlas** [comment]
maybe would be nice to add this into documentation (recommended linux distro + version + 32/64)

**Comment by vlasvlasvlas** [comment]
another thing:

1- are ALL pre -requirements for server side install this ones?
http://docs.camptocamp.net/c2cgeoportal/master/integrator/requirements.html

or do i need any other pre -requirements?

2- and are there any autoinstaller for all this pre-requirements?

thanks!

**Comment by vlasvlasvlas** [comment]
anyone?

**Comment by ochriste** [comment]
1) pretty much yes if you want to use all the functionalities, beside "deploy" which is used for inter-server application deployment, it's nice but it's not required.
2) no, you will need to install all these manually. But most of these are already packaged (on linux) or have their own installer (on windows).

**Comment by vlasvlasvlas** [comment]
Hi Ochriste! thanks!

do i need 32 or 64bit of linux distro?

is there any specific order when installing all the pre-requirements?

thanks!

**Comment by ochriste** [comment]
all our infra is 64bit (amd64),
it may work on 32bit but I cant guaranty it
if you install on linux, the order will be automatically set accordingly to the package own dependencies.
on windows, beside python, which is a dependency of several of the other requirements, I dont think the order really matter.

**Comment by vlasvlasvlas** [comment]
thanks a lot! ill retry to install server. thnks!
