### ISSUE TITLE
Syntax of multiple entries in authorized_plugins functionalities

### ISSUE THREAD

**Issue by asaunier** [camptocamp/c2cgeoportal#1333]
The doc at http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/functionality.html#limiting-access-to-some-cgxp-plugins-using-functionalities doesn't explain what syntax to use in the admin interface when creating a new "authorized_plugins"  specifying a list of plugins.

For a single entry, "authorized_plugins" would be ``<some plugin name>```, but what if there are several?

**Comment by ochriste** [comment]
maybe one functionality by plugin ?

**Comment by asaunier** [comment]
Thanks @ochriste this works!
It would be cool to add this tip to the doc.
