### ISSUE TITLE
DeprecationWarning - custom predicates

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1342]
This is a question...

I am using mapserverproxy_route_predicate as custom predicate in one of our projects.

If I use it like here https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/__init__.py#L457

Then I get a warning in my console:

```
my_project\__init__.py:115: DeprecationWarning: The "custom_predicates" argument 
to Configurator.add_route is deprecated as of Pyramid 1.5.  Use "config.add_route_predicate"
and use the registered route predicate as a predicate argument to add_route instead.
See "Adding A Third Party View, Route, or Subscriber Predicate" in the "Hooks" chapter
of the documentation for more information.
```

Does someone get the same warning ? (or am I the only one...)

**Comment by sbrunner** [comment]
see also: http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#view-and-route-predicates

**Comment by sbrunner** [comment]
For me it's fixed with the pyramid upgrade, to be verified.
