### ISSUE TITLE
Cannot reach the documentation

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1343]
Hmmm... I can only see the documentation for branch 1.5 and not anymore the documentation from the master branch, was this done on purpose ?

Cf: http://docs.camptocamp.net/c2cgeoportal/

**Comment by sbrunner** [comment]
Oups ...

**Comment by sbrunner** [comment]
Fixed :-)

**Comment by kalbermattenm** [comment]
Thanks ;-)
