### ISSUE TITLE
Mobile doesn't work anymore with Chrome

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1365]
Mobile doesn't work anymore with Chrome, the map doesn't show up!

![image](https://cloud.githubusercontent.com/assets/4549666/7879844/5fabccba-05f4-11e5-9945-b61ce0ac13a5.png)

Confirmed with Chrome `43.0.2357` (PC, tablet, smartphone), on all 1.5 projects.

**Comment by rbovard** [comment]
@pgiraud Any ideas? It's quite annoying...

**Comment by sbrunner** [comment]
On Linux it's working, on windows we have the same issue on windows and on Android ...

**Comment by jaykayone** [comment]
We have got the same problem in Luxembourg

**Comment by kalbermattenm** [comment]
Apparently this occurred with Chrome 43:

I do not know if it might help, but I found that: http://www.ladysign-apps.com/developer/chrome-43-breaks-sencha-touch-modern-toolkit-and-how-to-fix-it/#.VX6-mEarG-0

**Comment by pgiraud** [comment]
Thanks @kalbermattenm, I found the same resource. I'll keep you informed if this "hack" works.

**Comment by kalbermattenm** [comment]
Thanks @pgiraud !

**Comment by gnerred** [comment]
Same problem here, thanks @pgiraud if you can find a hack...

**Comment by rbovard** [comment]
Fixed with https://github.com/camptocamp/c2cgeoportal/pull/1417
