### ISSUE TITLE
Escaping % in mako - v 1.6

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1373]
While preparing my mapfile for version 1.6, I encountered a little issue.

When you want to secure an attribute, you have to use variable substitution (use a functionality) in your mapfile, more precisely in your layer's SQL query. Something like:

mymapfile.map.mako:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute
    %your_functionality_name%
   ...
```
Because Mako is quite sensitive to `%` signs, I though that I just would have to escape them by replacing all single `%` with `%%`, but:

mymapfile.map:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute
    %%your_functionality_name%%
   ...
```
Then I read that only the first `%` of a line had to be escaped, but it still keeps the double `%`

mymapfile.map:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute
    %%your_functionality_name%
   ...
```
Finally, I found out a solution:

mymapfile.map.mako:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute
    ${'%your_functionality_name%'}
   ...
```
Finally I get what is expected:
mymapfile.map:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute
    %your_functionality_name%
   ...
```
Is that the right way to do it ?

**Comment by sbrunner** [comment]
The simplest way it to don't put the concern '%' at the start of the line:
```
DATA "geom FROM (SELECT
    your_first_nonsecured_attribute %your_functionality_name%
   ....
```
:-)

**Comment by kalbermattenm** [comment]
Thanks for your answer @sbrunner !

Closing
