### ISSUE TITLE
main schema in DB

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1374]
Am I right that there is no more foreign key between the main_static.user and main.role ?

Thus I can only retrieve the role of an user by making a request like

```
DBSession.query(User).filter(User.role_name =='toto').all()
```
And not anymore through the direct ORM link from SQLAlchemy...

Right ?

**Comment by sbrunner** [comment]
Right, we do it to be able to update the main schema without any interaction with the main_static schema :-)

**Comment by kalbermattenm** [comment]
OK, thanks for the info... That's quite a change for us, notably our user management system....

Closing

**Comment by sbrunner** [comment]
Yes it's true...
Ask me it you have big issue!
