### ISSUE TITLE
c2ctool - upgrade step 1

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1377]
@sbrunner, I am still trying to upgrade c2cgeoportal...

On line https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/c2ctool.py#L285, you run a `git pull --rebase` on a remote called `origin`. At SITN, `origin` is my own repository (kalbermattenm\sitn_c2cgeoportal), `upstream` would be camptocamp\sitn_c2cgeoportal...

Is it the same on your side ? Because, quite often, my own repository is really not up-to-date. I just use it to make pull requests...

**Comment by kalbermattenm** [comment]
Moreover, can anyone please tell me what this file is and where it comes from:

`.build/requirements.timestamp`

This one is called in the upgrade process (https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/c2ctool.py#L342), but I don't have any file of this kind in my `.build` folder....

**Comment by kalbermattenm** [comment]
Oh... by the way, regarding my first comment in this issue,I implemented an option in `c2ctool.py` which enables you to choose which git remote to use

**Comment by sbrunner** [comment]
What we want on the line 342 is to call to make to build this file, this file is a marker that the requirements will be installed correctly in the virtual environment :-)

**Comment by kalbermattenm** [comment]
But I don't have this file on my computer but I have it on the dev server... And I do not get why...

Could you tell me how to create it (which command) ?

Is it something like `make -f ...` ?

**Comment by sbrunner** [comment]
You should have this before lunching the command will create it !

**Comment by kalbermattenm** [comment]
Working with #1384
Closing
