### ISSUE TITLE
Add | n to templates

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1387]
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L111-L115

This change also concerns the `*.html` files in the `my_project/template` folder, right ?

**Comment by sbrunner** [comment]
False, this point is right :-)

By default pyramid do a replacement that correct when we are in the html (<a href> , <img src>, <link href>, <script src>), but not when we set  a JavaScript variable :-)

**Comment by kalbermattenm** [comment]
OK, thanks, got it, so closing.
