### ISSUE TITLE
MANIFEST File in Jasmine

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1390]
Each time I build our app it creates a `MANIFEST` file in `sitn/static/lib/cgxp/core/tests/lib/jasmine`

This file contains:

```
recursive-include . *.py
include lib/jasmine-core/*.js
include lib/jasmine-core/*.css
include images/*.png
include package.json
```
Is there a way to avoid that ? (`.gitignore`) And am I the only one to have that ?

**Comment by sbrunner** [comment]
No but I see the issue ...
