### ISSUE TITLE
Cache for static file

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1406]
I need the number generated for the cache, ie `http://sitn.ne.ch/main/wsgi/proj/29f9a3df311d47148551c4af3c149376/...` in a Python view...

How do I get `29f9a3df311d47148551c4af3c149376` ? (I was not able to find it in `request.registry.settings`)

I need this because in the SITN project we call some on-the-fly generated SLD files through `http://localhost/proj/misc/sld/my_sld.xml` and this URL is not anymore valid since the cache number was added to the URL.

Moreover, it would be cool if it was possible to bypass it. In other words, that these two URLs are valid:
```
http://localhost/proj/29f9a3df311d47148551c4af3c149376/misc/sld/my_sld.xm
http://localhost/proj/misc/sld/my_sld.xm
```

**Comment by sbrunner** [comment]
The cache number is generated on the fly than he isn't in the registry.settings.

What do you mean with on the fly ? a pyramid view ?

Finally I don't understand why and where you need this number, for your information the URL like:
`http://localhost/proj/whatever/misc/sld/my_sld.xml` will work :-)

**Comment by kalbermattenm** [comment]
> What do you mean with on the fly ? a pyramid view ?

See: https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/sitn/views/traffic.py#L271-L323

And then it is used here:

https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/sitn/templates/data_templates/traffic_event_show.html#L87-L90

It enable to filter quite simply the features that mapserver has to return in a WMS request...

> Finally I don't understand why and where you need this number, for your information the URL like:
`http://localhost/proj/whatever/misc/sld/my_sld.xml` will work :-)

Ok, I did not get that this was generated on the fly. I though it had something to do with the 10 day cache stuff...

I just tried with `http://localhost/proj/000/misc/sld/my_sld.xml` and it is working...

Thanks @sbrunner !
