### ISSUE TITLE
Admin panel doesn't work anymore with Chrome

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1411]
Related to #1365?! (KO on Windows, KO on Android, OK on Ubuntu)

![image](https://cloud.githubusercontent.com/assets/4549666/8110139/00d5b72a-105b-11e5-9e7e-f61bd9a4640f.png)

**Comment by kalbermattenm** [comment]
@rbovard, on Chrome Version 43.0.2357.124 m (Windows 7 x64) it seems to work...:
![presse-papiers-1](https://cloud.githubusercontent.com/assets/1681332/8180417/dc1a7dd2-141d-11e5-8b1e-39cdbf69a0ac.jpg)

**Comment by rbovard** [comment]
Mmm thanks @kalbermattenm, it seems that's OK now...

Maybe an update of Chrome ? I'm now with `43.0.2357.124 m` on W7 32 bits

**Comment by kalbermattenm** [comment]
> Maybe an update of Chrome ?

I think so...
