### ISSUE TITLE
Problem install - Getting distribution for 'Pillow==2.1.0'.

### ISSUE THREAD

**Issue by Comiii** [camptocamp/c2cgeoportal#1413]
Hi. I am using Ubuntu 14.10 and I am trying to install c2cgeoportal. After install Python 2.7 and other required components, I download and try to build c2cgeoportal with
./buildout/bin/buildout
osboxes@osboxes:~/Downloads/Python-2.7.5/c2cgeoportal$ ./buildout/bin/buildout
Develop: '/home/osboxes/Downloads/Python-2.7.5/c2cgeoportal/.'
/usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'message_extractors'
  warnings.warn(msg)
warning: no files found matching '*.ini'
warning: no files found matching '*.pt' under directory 'c2cgeoportal'
warning: no files found matching '*.mak' under directory 'c2cgeoportal'
warning: no files found matching '*.mo' under directory 'c2cgeoportal'
no previously-included directories found matching 'buildout'
warning: no previously-included files found matching 'bootstrap.py'
warning: no previously-included files found matching '.installed.cfg'
no previously-included directories found matching 'c2cgeoportal/static/examples'
no previously-included directories found matching 'c2cgeoportal/static/lib/checkboxtree/library'
warning: no previously-included files found matching 'c2cgeoportal/static/lib/checkboxtree/index.html'
warning: no previously-included files found matching 'c2cgeoportal/static/lib/checkboxtree/jquery.checkboxtree.css'
warning: no previously-included files found matching 'c2cgeoportal/static/lib/checkboxtree/jquery.checkboxtree.js'
warning: no previously-included files found matching 'c2cgeoportal/static/lib/checkboxtree/minify.sh'
no previously-included directories found matching 'c2cgeoportal/static/lib/openlayers/art'
warning: no files found matching 'c2cgeoportal/scaffolds/update/+package+/static/mobile/touch.tar.gz'
Installing eggs.
Getting distribution for 'Pillow==2.1.0'.
warning: no previously-included files found matching '.hgignore'
warning: no previously-included files found matching '.hgtags'
warning: no previously-included files found matching 'BUILDME.bat'
warning: no previously-included files found matching 'make-manifest.py'
warning: no previously-included files found matching 'SHIP'
warning: no previously-included files found matching 'SHIP.bat'
warning: no files found matching 'COPYING'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching 'README' under directory 'docs'
warning: no files found matching 'CHANGES' under directory 'docs'
warning: no files found matching 'CONTENTS' under directory 'docs'
_imaging.c: In function ‘_filter’:
_imaging.c:861:8: warning: ‘kernelsize’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (kernelsize != xsize * ysize) {
        ^
_imagingft.c:62:31: fatal error: freetype/fterrors.h: No such file or directory
 #include <freetype/fterrors.h>
                               ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
An error occurred when trying to install Pillow 2.1.0. Look above this message for any errors that were output by easy_install.
While:
  Installing eggs.
  Getting distribution for 'Pillow==2.1.0'.
Error: Couldn't install: Pillow 2.1.0
*************** PICKED VERSIONS ****************
[versions]

How I can fix this ? Thanks

**Comment by kalbermattenm** [comment]
Looks like you need a newer version of Pillow, see https://github.com/python-pillow/Pillow/issues/435

You should try to change Pillow to a newer version. In the `versions.cfg` file of the c2cgeoportal egg (`buildout\eggs\c2cgeoportal_xxxxx-py2.7.egg\c2cgeoportal\scaffolds\create\versions.cfg`), try to replace `Pillow = 2.1.0` and `pillow = 2.1.0` by `Pillow = 2.8.1` and `pillow = 2.8.1`.

I just hope that the indicated path is right and I don't really know how the whole thing is going to react, but it might be worth to give it a try....

**Comment by Comiii** [comment]
Thanks! It's work now.

**Comment by ochriste** [comment]
my guess is you are missing one of the Pillow dependency

please check that you have all required linux packages as indicated there:

http://pillow.readthedocs.org/en/latest/installation.html

the error, "fatal error: freetype/fterrors.h: No such file or
directory", seems to point to libfreetype.

maybe other package are required, check the error message if you have
more error when installing Pillow

regards
Oliver


> Hi. I am using Ubuntu 14.10 and I am trying to install c2cgeoportal.
> After install Python 2.7 and other required components, I download and
> try to build c2cgeoportal with
> ./buildout/bin/buildout
> osboxes@osboxes:~/Downloads/Python-2.7.5/c2cgeoportal$
> ./buildout/bin/buildout
> Develop: '/home/osboxes/Downloads/Python-2.7.5/c2cgeoportal/.'
> /usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
> distribution option: 'message_extractors'
> warnings.warn(msg)
> warning: no files found matching '/.ini'
> warning: no files found matching '/.pt' under directory 'c2cgeoportal'
> warning: no files found matching '/.mak' under directory 'c2cgeoportal'
> warning: no files found matching '/.mo' under directory 'c2cgeoportal'
> no previously-included directories found matching 'buildout'
> warning: no previously-included files found matching 'bootstrap.py'
> warning: no previously-included files found matching '.installed.cfg'
> no previously-included directories found matching
> 'c2cgeoportal/static/examples'
> no previously-included directories found matching
> 'c2cgeoportal/static/lib/checkboxtree/library'
> warning: no previously-included files found matching
> 'c2cgeoportal/static/lib/checkboxtree/index.html'
> warning: no previously-included files found matching
> 'c2cgeoportal/static/lib/checkboxtree/jquery.checkboxtree.css'
> warning: no previously-included files found matching
> 'c2cgeoportal/static/lib/checkboxtree/jquery.checkboxtree.js'
> warning: no previously-included files found matching
> 'c2cgeoportal/static/lib/checkboxtree/minify.sh'
> no previously-included directories found matching
> 'c2cgeoportal/static/lib/openlayers/art'
> warning: no files found matching
> 'c2cgeoportal/scaffolds/update/+package+/static/mobile/touch.tar.gz'
> Installing eggs.
> Getting distribution for 'Pillow==2.1.0'.
> warning: no previously-included files found matching '.hgignore'
> warning: no previously-included files found matching '.hgtags'
> warning: no previously-included files found matching 'BUILDME.bat'
> warning: no previously-included files found matching 'make-manifest.py'
> warning: no previously-included files found matching 'SHIP'
> warning: no previously-included files found matching 'SHIP.bat'
> warning: no files found matching 'COPYING'
> warning: no files found matching '/.html' under directory 'docs'
> warning: no files found matching '/.css' under directory 'docs'
> warning: no files found matching 'README' under directory 'docs'
> warning: no files found matching 'CHANGES' under directory 'docs'
> warning: no files found matching 'CONTENTS' under directory 'docs'
> _imaging.c: In function ‘_filter’:
> _imaging.c:861:8: warning: ‘kernelsize’ may be used uninitialized in
> this function [-Wmaybe-uninitialized]
> if (kernelsize != xsize * ysize) {
> ^
> _imagingft.c:62:31: fatal error: freetype/fterrors.h: No such file or
> directory
> #include
> ^
> compilation terminated.
> error: Setup script exited with error: command 'gcc' failed with exit
> status 1
> An error occurred when trying to install Pillow 2.1.0. Look above this
> message for any errors that were output by easy_install.
> While:
> Installing eggs.
> Getting distribution for 'Pillow==2.1.0'.
> Error: Couldn't install: Pillow 2.1.0
> *************** PICKED VERSIONS ****************
> [versions]
> 
> How I can fix this ? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/c2cgeoportal/issues/1413>.
> 


-- 
Camptocamp SA
Oliver Christen
PSE A, EPFL
CH-1015 Lausanne

www.camptocamp.com

+41 21 619 10 23 (direct)
+41 21 619 10 10 (centrale)
+41 21 619 10 00 (fax)

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
