### ISSUE TITLE
Apache error when adding a new layer in the admin interface

### ISSUE THREAD

**Issue by cimbach** [camptocamp/c2cgeoportal#1416]
On v1.5.2 and 1.5.4, each time the 'Nouveau couche' button is pressed, the following error shows up in the apache error log.
Same behaviour with the 'Nouveau Groupe de couches' and 'Nouveau Thème' buttons.

[Tue Jun 16 09:50:13 2015] [error] 2015-06-16 09:50:13,627 ERROR [pyramid_formalchemy.resources][Dummy-2] (DataError) invalid input syntax for integer: "new"
[Tue Jun 16 09:50:13 2015] [error] LINE 3: WHERE main.treeitem.id = 'new'
[Tue Jun 16 09:50:13 2015] [error]                                  ^
[Tue Jun 16 09:50:13 2015] [error]  'SELECT main.treeitem.type AS main_treeitem_type, main.layer.id AS main_layer_id, main.treeitem.id AS main_treeitem_id, main.treeitem.name AS main_treeitem_name, main.treeitem."order" AS main_treeitem_order, main.treeitem."metadataURL" AS "main_treeitem_metadataURL", main.layer.public AS main_layer_public, main.layer."inMobileViewer" AS "main_layer_inMobileViewer", main.layer."inDesktopViewer" AS "main_layer_inDesktopViewer", main.layer."isChecked" AS "main_layer_isChecked", main.layer.icon AS main_layer_icon, main.layer."layerType" AS "main_layer_layerType", main.layer.url AS main_layer_url, main.layer."imageType" AS "main_layer_imageType", main.layer.style AS main_layer_style, main.layer.dimensions AS main_layer_dimensions, main.layer."matrixSet" AS "main_layer_matrixSet", main.layer."wmsUrl" AS "main_layer_wmsUrl", main.layer."wmsLayers" AS "main_layer_wmsLayers", main.layer."queryLayers" AS "main_layer_queryLayers", main.layer.kml AS main_layer_kml, main.layer."isSingleTile" AS "main_layer_isSingleTile", main.layer.legend AS main_layer_legend, main.layer."legendImage" AS "main_layer_legendImage", main.layer."legendRule" AS "main_layer_legendRule", main.layer."isLegendExpanded" AS "main_layer_isLegendExpanded", main.layer."minResolution" AS "main_layer_minResolution", main.layer."maxResolution" AS "main_layer_maxResolution", main.layer.disclaimer AS main_layer_disclaimer, main.layer."identifierAttributeField" AS "main_layer_identifierAttributeField", main.layer."geoTable" AS "main_layer_geoTable", main.layer."excludeProperties" AS "main_layer_excludeProperties", main.layer."timeMode" AS "main_layer_timeMode" \\nFROM main.treeitem JOIN main.layer ON main.treeitem.id = main.layer.id \\nWHERE main.treeitem.id = %(param_1)s' {'param_1': u'new'}
[Tue Jun 16 09:50:13 2015] [error] Traceback (most recent call last):
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/pyramid_formalchemy-0.4.4-py2.7.egg/pyramid_formalchemy/resources.py", line 166, in __init__
[Tue Jun 16 09:50:13 2015] [error]     request.model_instance = request.query_factory(request, query, id=name)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/pyramid_formalchemy-0.4.4-py2.7.egg/pyramid_formalchemy/__init__.py", line 93, in query_factory
[Tue Jun 16 09:50:13 2015] [error]     return query.get(id)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 775, in get
[Tue Jun 16 09:50:13 2015] [error]     return self._load_on_ident(key)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2512, in _load_on_ident
[Tue Jun 16 09:50:13 2015] [error]     return q.one()
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2184, in one
[Tue Jun 16 09:50:13 2015] [error]     ret = list(self)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2227, in __iter__
[Tue Jun 16 09:50:13 2015] [error]     return self._execute_and_instances(context)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2242, in _execute_and_instances
[Tue Jun 16 09:50:13 2015] [error]     result = conn.execute(querycontext.statement, self._params)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1449, in execute
[Tue Jun 16 09:50:13 2015] [error]     params)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
[Tue Jun 16 09:50:13 2015] [error]     compiled_sql, distilled_params
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1698, in _execute_context
[Tue Jun 16 09:50:13 2015] [error]     context)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1691, in _execute_context
[Tue Jun 16 09:50:13 2015] [error]     context)
[Tue Jun 16 09:50:13 2015] [error]   File "/home/cimbach/lausanne-mapfish/buildout/eggs/SQLAlchemy-0.7.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 331, in do_execute
[Tue Jun 16 09:50:13 2015] [error]     cursor.execute(statement, parameters)
[Tue Jun 16 09:50:13 2015] [error] DataError: (DataError) invalid input syntax for integer: "new"
[Tue Jun 16 09:50:13 2015] [error] LINE 3: WHERE main.treeitem.id = 'new'
[Tue Jun 16 09:50:13 2015] [error]                                  ^

**Comment by kalbermattenm** [comment]
The stuff in the log in "normal..."

It is blocking on your side...? (or does it just fill up the logs...)

**Comment by cimbach** [comment]
If you say so.
Just trying to have an empty error log... 
Thx for the info anyway!
