### ISSUE TITLE
psycopg2- Problem install on Windows 

### ISSUE THREAD

**Issue by Comiii** [camptocamp/c2cgeoportal#1423]
Hi. I install Python 2.7 on Windows, after that I install  psycopg2  with command pip install git+https://github.com/nwcell/psycopg2-windows.git@win32-py27#egg=psycopg2. After all I start install c2cgeoportal with tutorial http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/create_application.html#project-structure
but then I get error after start build:

$ ./buildout/bin/buildout
Develop: 'c:\\c2cgeoportal\\c2cgeoportal\\.'
C:\Python27\LIB\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'message_extractors'
  warnings.warn(msg)
warning: no files found matching '*.ini'
warning: no files found matching '*.pt' under directory 'c2cgeoportal'
warning: no files found matching '*.mak' under directory 'c2cgeoportal'
warning: no files found matching '*.mo' under directory 'c2cgeoportal'
no previously-included directories found matching 'buildout'
warning: no previously-included files found matching 'bootstrap.py'
warning: no previously-included files found matching '.installed.cfg'
no previously-included directories found matching 'c2cgeoportal\static\examples'

no previously-included directories found matching 'c2cgeoportal\static\lib\check
boxtree\library'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\index.html'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\jquery.checkboxtree.css'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\jquery.checkboxtree.js'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\minify.sh'
no previously-included directories found matching 'c2cgeoportal\static\lib\openl
ayers\art'
warning: no files found matching 'c2cgeoportal\scaffolds\update\+package+\static
\mobile\touch.tar.gz'
Installing eggs.
Getting distribution for 'psycopg2==2.6.1'.
psycopgmodule.c
green.c
pqpath.c
utils.c
bytes_format.c
connection_int.c
connection_type.c
cursor_int.c
cursor_type.c
diagnostics_type.c
error_type.c
lobject_int.c
lobject_type.c
notify_type.c
xid_type.c
adapter_asis.c
adapter_binary.c
adapter_datetime.c
adapter_list.c
adapter_pboolean.c
adapter_pdecimal.c
adapter_pint.c
adapter_pfloat.c
adapter_qstring.c
microprotocols.c
microprotocols_proto.c
typecast.c
   Creating library build\temp.win32-2.7\Release\psycopg\_psycopg.lib and object
 build\temp.win32-2.7\Release\psycopg\_psycopg.exp
psycopgmodule.obj : error LNK2019: unresolved external symbol _PQinitOpenSSL ref
erenced in function _psyco_libcrypto_threads_init
pqpath.obj : error LNK2019: unresolved external symbol _PQclear referenced in fu
nction _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQclear
cursor_type.obj : error LNK2001: unresolved external symbol _PQclear
error_type.obj : error LNK2001: unresolved external symbol _PQclear
pqpath.obj : error LNK2019: unresolved external symbol _PQerrorMessage reference
d in function _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQerrorMessage
lobject_int.obj : error LNK2001: unresolved external symbol _PQerrorMessage
pqpath.obj : error LNK2019: unresolved external symbol _PQresultErrorField refer
enced in function _pq_raise
diagnostics_type.obj : error LNK2001: unresolved external symbol _PQresultErrorF
ield
pqpath.obj : error LNK2019: unresolved external symbol _PQresultErrorMessage ref
erenced in function _pq_raise
pqpath.obj : error LNK2019: unresolved external symbol _PQstatus referenced in f
unction _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQstatus
pqpath.obj : error LNK2019: unresolved external symbol _PQgetResult referenced i
n function _pq_clear_async
pqpath.obj : error LNK2019: unresolved external symbol _PQsetnonblocking referen
ced in function _pq_set_non_blocking
pqpath.obj : error LNK2019: unresolved external symbol _PQresultStatus reference
d in function _pq_execute_command_locked
connection_int.obj : error LNK2001: unresolved external symbol _PQresultStatus
pqpath.obj : error LNK2019: unresolved external symbol _PQexec referenced in fun
ction _pq_execute_command_locked
pqpath.obj : error LNK2019: unresolved external symbol _PQgetvalue referenced in
 function _pq_get_guc_locked
cursor_type.obj : error LNK2001: unresolved external symbol _PQgetvalue
pqpath.obj : error LNK2019: unresolved external symbol _PQisBusy referenced in f
unction _pq_is_busy
pqpath.obj : error LNK2019: unresolved external symbol _PQconsumeInput reference
d in function _pq_is_busy
pqpath.obj : error LNK2019: unresolved external symbol _PQflush referenced in fu
nction _pq_flush
connection_int.obj : error LNK2001: unresolved external symbol _PQflush
pqpath.obj : error LNK2019: unresolved external symbol _PQsendQuery referenced i
n function _pq_send_query
pqpath.obj : error LNK2019: unresolved external symbol _PQfname referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQfmod referenced in fun
ction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQfsize referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQftype referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQbinaryTuples reference
d in function __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQnfields referenced in
function __pq_fetch_tuples
cursor_type.obj : error LNK2001: unresolved external symbol _PQnfields
pqpath.obj : error LNK2019: unresolved external symbol _PQcmdTuples referenced i
n function __read_rowcount
pqpath.obj : error LNK2019: unresolved external symbol _PQputCopyEnd referenced
in function __pq_copy_in_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQputCopyData referenced
 in function __pq_copy_in_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQfreemem referenced in
function __pq_copy_out_v3
connection_int.obj : error LNK2001: unresolved external symbol _PQfreemem
adapter_binary.obj : error LNK2001: unresolved external symbol _PQfreemem
pqpath.obj : error LNK2019: unresolved external symbol _PQgetCopyData referenced
 in function __pq_copy_out_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQntuples referenced in
function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQoidValue referenced in
 function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQcmdStatus referenced i
n function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQresStatus referenced i
n function _pq_fetch
utils.obj : error LNK2019: unresolved external symbol _PQescapeString referenced
 in function _psycopg_escape_string
utils.obj : error LNK2019: unresolved external symbol _PQescapeStringConn refere
nced in function _psycopg_escape_string
connection_int.obj : error LNK2019: unresolved external symbol _PQnotifies refer
enced in function _conn_notifies_process
connection_int.obj : error LNK2019: unresolved external symbol _PQparameterStatu
s referenced in function _conn_get_standard_conforming_strings
connection_type.obj : error LNK2001: unresolved external symbol _PQparameterStat
us
connection_int.obj : error LNK2019: unresolved external symbol _PQprotocolVersio
n referenced in function _conn_get_protocol_version
connection_int.obj : error LNK2019: unresolved external symbol _PQserverVersion
referenced in function _conn_get_server_version
connection_int.obj : error LNK2019: unresolved external symbol _PQgetCancel refe
renced in function _conn_setup_cancel
connection_int.obj : error LNK2019: unresolved external symbol _PQfreeCancel ref
erenced in function _conn_setup_cancel
connection_type.obj : error LNK2001: unresolved external symbol _PQfreeCancel
connection_int.obj : error LNK2019: unresolved external symbol _PQsetNoticeProce
ssor referenced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectStart r
eferenced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectdb refe
renced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectPoll re
ferenced in function __conn_poll_connecting
connection_int.obj : error LNK2019: unresolved external symbol _PQfinish referen
ced in function _conn_close_locked
connection_type.obj : error LNK2019: unresolved external symbol _PQtransactionSt
atus referenced in function _psyco_conn_get_transaction_status
cursor_type.obj : error LNK2001: unresolved external symbol _PQtransactionStatus

connection_type.obj : error LNK2019: unresolved external symbol _PQbackendPID re
ferenced in function _psyco_conn_get_backend_pid
connection_type.obj : error LNK2019: unresolved external symbol _PQsocket refere
nced in function _psyco_conn_fileno
connection_type.obj : error LNK2019: unresolved external symbol _PQcancel refere
nced in function _psyco_conn_cancel
cursor_type.obj : error LNK2019: unresolved external symbol _PQgetlength referen
ced in function __psyco_curs_buildrow_fill
cursor_type.obj : error LNK2019: unresolved external symbol _PQgetisnull referen
ced in function __psyco_curs_buildrow_fill
lobject_int.obj : error LNK2019: unresolved external symbol _lo_open referenced
in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_creat referenced
 in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_create reference
d in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_import reference
d in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_close referenced
 in function _lobject_close_locked
lobject_int.obj : error LNK2019: unresolved external symbol _lo_unlink reference
d in function _lobject_unlink
lobject_int.obj : error LNK2019: unresolved external symbol _lo_write referenced
 in function _lobject_write
lobject_int.obj : error LNK2019: unresolved external symbol _lo_read referenced
in function _lobject_read
lobject_int.obj : error LNK2019: unresolved external symbol _lo_lseek referenced
 in function _lobject_seek
lobject_int.obj : error LNK2019: unresolved external symbol _lo_tell referenced
in function _lobject_tell
lobject_int.obj : error LNK2019: unresolved external symbol _lo_export reference
d in function _lobject_export
lobject_int.obj : error LNK2019: unresolved external symbol _lo_truncate referen
ced in function _lobject_truncate
adapter_binary.obj : error LNK2019: unresolved external symbol _PQescapeBytea re
ferenced in function _binary_escape
adapter_binary.obj : error LNK2019: unresolved external symbol _PQescapeByteaCon
n referenced in function _binary_escape
build\lib.win32-2.7\psycopg2\_psycopg.pyd : fatal error LNK1120: 63 unresolved e
xternals
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microso
ft Visual Studio 9.0\\VC\\BIN\\link.exe' failed with exit status 1120
An error occurred when trying to install psycopg2 2.6.1. Look above this message
 for any errors that were output by easy_install.
While:
  Installing eggs.
  Getting distribution for 'psycopg2==2.6.1'.
Error: Couldn't install: psycopg2 2.6.1
*************** PICKED VERSIONS ****************
[versions]

*************** /PICKED VERSIONS ***************

**Comment by kalbermattenm** [comment]
By using https://github.com/nwcell/psycopg2-windows.git@win32-py27#egg=psycopg2, I think that you installed psycopg2 2.5.3. I can check that by opening a Python console and:
```
import psycopg2
psycopg2.__version__
```
Then, in c2cgeoportal, you should overwrite the specified pyscopg2 version in the `version.cfg` file (https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/scaffolds/create/versions.cfg#L81). If you do not so, then buildout will believe that it needs to install another version then the one you have installed manually.

You might encounter this issue with other Python packages, notably shapely...

**Comment by Comiii** [comment]
Thanks for answering but this is not help me. 
When I check pszcopg2 from Python console I get this:
>>> import psycopg2
>>> psycopg2.__version__
'2.6.1 (dt dec pq3 ext)'
>>>

I overwrite version.cfg with psycopg2 = 2.6.1. Then when I try building a get same error:
$ ./buildout/bin/buildout
Develop: 'c:\\c2cgeoportal\\c2cgeoportal\\.'
C:\Python27\LIB\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'message_extractors'
  warnings.warn(msg)
warning: no files found matching '*.ini'
warning: no files found matching '*.pt' under directory 'c2cgeoportal'
warning: no files found matching '*.mak' under directory 'c2cgeoportal'
warning: no files found matching '*.mo' under directory 'c2cgeoportal'
no previously-included directories found matching 'buildout'
warning: no previously-included files found matching 'bootstrap.py'
warning: no previously-included files found matching '.installed.cfg'
no previously-included directories found matching 'c2cgeoportal\static\examples'

no previously-included directories found matching 'c2cgeoportal\static\lib\check
boxtree\library'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\index.html'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\jquery.checkboxtree.css'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\jquery.checkboxtree.js'
warning: no previously-included files found matching 'c2cgeoportal\static\lib\ch
eckboxtree\minify.sh'
no previously-included directories found matching 'c2cgeoportal\static\lib\openl
ayers\art'
warning: no files found matching 'c2cgeoportal\scaffolds\update\+package+\static
\mobile\touch.tar.gz'
Installing eggs.
Getting distribution for 'psycopg2==2.6.1'.
psycopgmodule.c
green.c
pqpath.c
utils.c
bytes_format.c
connection_int.c
connection_type.c
cursor_int.c
cursor_type.c
diagnostics_type.c
error_type.c
lobject_int.c
lobject_type.c
notify_type.c
xid_type.c
adapter_asis.c
adapter_binary.c
adapter_datetime.c
adapter_list.c
adapter_pboolean.c
adapter_pdecimal.c
adapter_pint.c
adapter_pfloat.c
adapter_qstring.c
microprotocols.c
microprotocols_proto.c
typecast.c
   Creating library build\temp.win32-2.7\Release\psycopg\_psycopg.lib and object
 build\temp.win32-2.7\Release\psycopg\_psycopg.exp
psycopgmodule.obj : error LNK2019: unresolved external symbol _PQinitOpenSSL ref
erenced in function _psyco_libcrypto_threads_init
pqpath.obj : error LNK2019: unresolved external symbol _PQclear referenced in fu
nction _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQclear
cursor_type.obj : error LNK2001: unresolved external symbol _PQclear
error_type.obj : error LNK2001: unresolved external symbol _PQclear
pqpath.obj : error LNK2019: unresolved external symbol _PQerrorMessage reference
d in function _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQerrorMessage
lobject_int.obj : error LNK2001: unresolved external symbol _PQerrorMessage
pqpath.obj : error LNK2019: unresolved external symbol _PQresultErrorField refer
enced in function _pq_raise
diagnostics_type.obj : error LNK2001: unresolved external symbol _PQresultErrorF
ield
pqpath.obj : error LNK2019: unresolved external symbol _PQresultErrorMessage ref
erenced in function _pq_raise
pqpath.obj : error LNK2019: unresolved external symbol _PQstatus referenced in f
unction _pq_raise
connection_int.obj : error LNK2001: unresolved external symbol _PQstatus
pqpath.obj : error LNK2019: unresolved external symbol _PQgetResult referenced i
n function _pq_clear_async
pqpath.obj : error LNK2019: unresolved external symbol _PQsetnonblocking referen
ced in function _pq_set_non_blocking
pqpath.obj : error LNK2019: unresolved external symbol _PQresultStatus reference
d in function _pq_execute_command_locked
connection_int.obj : error LNK2001: unresolved external symbol _PQresultStatus
pqpath.obj : error LNK2019: unresolved external symbol _PQexec referenced in fun
ction _pq_execute_command_locked
pqpath.obj : error LNK2019: unresolved external symbol _PQgetvalue referenced in
 function _pq_get_guc_locked
cursor_type.obj : error LNK2001: unresolved external symbol _PQgetvalue
pqpath.obj : error LNK2019: unresolved external symbol _PQisBusy referenced in f
unction _pq_is_busy
pqpath.obj : error LNK2019: unresolved external symbol _PQconsumeInput reference
d in function _pq_is_busy
pqpath.obj : error LNK2019: unresolved external symbol _PQflush referenced in fu
nction _pq_flush
connection_int.obj : error LNK2001: unresolved external symbol _PQflush
pqpath.obj : error LNK2019: unresolved external symbol _PQsendQuery referenced i
n function _pq_send_query
pqpath.obj : error LNK2019: unresolved external symbol _PQfname referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQfmod referenced in fun
ction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQfsize referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQftype referenced in fu
nction __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQbinaryTuples reference
d in function __pq_fetch_tuples
pqpath.obj : error LNK2019: unresolved external symbol _PQnfields referenced in
function __pq_fetch_tuples
cursor_type.obj : error LNK2001: unresolved external symbol _PQnfields
pqpath.obj : error LNK2019: unresolved external symbol _PQcmdTuples referenced i
n function __read_rowcount
pqpath.obj : error LNK2019: unresolved external symbol _PQputCopyEnd referenced
in function __pq_copy_in_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQputCopyData referenced
 in function __pq_copy_in_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQfreemem referenced in
function __pq_copy_out_v3
connection_int.obj : error LNK2001: unresolved external symbol _PQfreemem
adapter_binary.obj : error LNK2001: unresolved external symbol _PQfreemem
pqpath.obj : error LNK2019: unresolved external symbol _PQgetCopyData referenced
 in function __pq_copy_out_v3
pqpath.obj : error LNK2019: unresolved external symbol _PQntuples referenced in
function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQoidValue referenced in
 function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQcmdStatus referenced i
n function _pq_fetch
pqpath.obj : error LNK2019: unresolved external symbol _PQresStatus referenced i
n function _pq_fetch
utils.obj : error LNK2019: unresolved external symbol _PQescapeString referenced
 in function _psycopg_escape_string
utils.obj : error LNK2019: unresolved external symbol _PQescapeStringConn refere
nced in function _psycopg_escape_string
connection_int.obj : error LNK2019: unresolved external symbol _PQnotifies refer
enced in function _conn_notifies_process
connection_int.obj : error LNK2019: unresolved external symbol _PQparameterStatu
s referenced in function _conn_get_standard_conforming_strings
connection_type.obj : error LNK2001: unresolved external symbol _PQparameterStat
us
connection_int.obj : error LNK2019: unresolved external symbol _PQprotocolVersio
n referenced in function _conn_get_protocol_version
connection_int.obj : error LNK2019: unresolved external symbol _PQserverVersion
referenced in function _conn_get_server_version
connection_int.obj : error LNK2019: unresolved external symbol _PQgetCancel refe
renced in function _conn_setup_cancel
connection_int.obj : error LNK2019: unresolved external symbol _PQfreeCancel ref
erenced in function _conn_setup_cancel
connection_type.obj : error LNK2001: unresolved external symbol _PQfreeCancel
connection_int.obj : error LNK2019: unresolved external symbol _PQsetNoticeProce
ssor referenced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectStart r
eferenced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectdb refe
renced in function __conn_sync_connect
connection_int.obj : error LNK2019: unresolved external symbol _PQconnectPoll re
ferenced in function __conn_poll_connecting
connection_int.obj : error LNK2019: unresolved external symbol _PQfinish referen
ced in function _conn_close_locked
connection_type.obj : error LNK2019: unresolved external symbol _PQtransactionSt
atus referenced in function _psyco_conn_get_transaction_status
cursor_type.obj : error LNK2001: unresolved external symbol _PQtransactionStatus

connection_type.obj : error LNK2019: unresolved external symbol _PQbackendPID re
ferenced in function _psyco_conn_get_backend_pid
connection_type.obj : error LNK2019: unresolved external symbol _PQsocket refere
nced in function _psyco_conn_fileno
connection_type.obj : error LNK2019: unresolved external symbol _PQcancel refere
nced in function _psyco_conn_cancel
cursor_type.obj : error LNK2019: unresolved external symbol _PQgetlength referen
ced in function __psyco_curs_buildrow_fill
cursor_type.obj : error LNK2019: unresolved external symbol _PQgetisnull referen
ced in function __psyco_curs_buildrow_fill
lobject_int.obj : error LNK2019: unresolved external symbol _lo_open referenced
in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_creat referenced
 in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_create reference
d in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_import reference
d in function _lobject_open
lobject_int.obj : error LNK2019: unresolved external symbol _lo_close referenced
 in function _lobject_close_locked
lobject_int.obj : error LNK2019: unresolved external symbol _lo_unlink reference
d in function _lobject_unlink
lobject_int.obj : error LNK2019: unresolved external symbol _lo_write referenced
 in function _lobject_write
lobject_int.obj : error LNK2019: unresolved external symbol _lo_read referenced
in function _lobject_read
lobject_int.obj : error LNK2019: unresolved external symbol _lo_lseek referenced
 in function _lobject_seek
lobject_int.obj : error LNK2019: unresolved external symbol _lo_tell referenced
in function _lobject_tell
lobject_int.obj : error LNK2019: unresolved external symbol _lo_export reference
d in function _lobject_export
lobject_int.obj : error LNK2019: unresolved external symbol _lo_truncate referen
ced in function _lobject_truncate
adapter_binary.obj : error LNK2019: unresolved external symbol _PQescapeBytea re
ferenced in function _binary_escape
adapter_binary.obj : error LNK2019: unresolved external symbol _PQescapeByteaCon
n referenced in function _binary_escape
build\lib.win32-2.7\psycopg2\_psycopg.pyd : fatal error LNK1120: 63 unresolved e
xternals
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microso
ft Visual Studio 9.0\\VC\\BIN\\link.exe' failed with exit status 1120
An error occurred when trying to install psycopg2 2.6.1. Look above this message
 for any errors that were output by easy_install.
While:
  Installing eggs.
  Getting distribution for 'psycopg2==2.6.1'.
Error: Couldn't install: psycopg2 2.6.1
*************** PICKED VERSIONS ****************
[versions]

*************** /PICKED VERSIONS ***************

**Comment by kalbermattenm** [comment]
You are trying to install version 1.5.x of c2cgeoportal, right ?

**Comment by Comiii** [comment]
Yes.

**Comment by Comiii** [comment]
Is there any tutorial how to install c2cgeoportal  on Windows server?

**Comment by kalbermattenm** [comment]
> Is there any tutorial how to install c2cgeoportal on Windows server?

Nope... because there are so few users which are on Windows (I am...)

For your issue

Could you try to add:
```
allowed-eggs-from-site-packages += psycopg2
```
in the `[buildout]` section of this file: https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/scaffolds/create/buildout.cfg

If this is not working, then maybe one of the core devs should answer...

**Comment by Comiii** [comment]
It's not working. Same error.

**Comment by ochriste** [comment]
mmm, you installed this, yes?
http://www.stickpeople.com/projects/python/win-psycopg/

**Comment by Comiii** [comment]
Yes I install it this 
(env) C:\Python27\env\Scripts>easy_install C:\Python27\env\Scripts\psycopg2-2.6.
1.win-amd64-py2.7-pg9.4.4-release.exe
Processing psycopg2-2.6.1.win-amd64-py2.7-pg9.4.4-release.exe
psycopg2.tests.test_module: module references __file__
psycopg2.tests.test_types_basic: module references __file__
creating 'c:\users\kodzo\appdata\local\temp\easy_install-alvigs\psycopg2-2.6.1-p
y2.7-win32.egg' and adding 'c:\users\kodzo\appdata\local\temp\easy_install-alvig
s\psycopg2-2.6.1-py2.7-win32.egg.tmp' to it
removing 'c:\python27\env\lib\site-packages\psycopg2-2.6.1-py2.7-win32.egg' (and
 everything under it)
creating c:\python27\env\lib\site-packages\psycopg2-2.6.1-py2.7-win32.egg
Extracting psycopg2-2.6.1-py2.7-win32.egg to c:\python27\env\lib\site-packages
psycopg2 2.6.1 is already the active version in easy-install.pth

Installed c:\python27\env\lib\site-packages\psycopg2-2.6.1-py2.7-win32.egg
Processing dependencies for psycopg2==2.6.1
Finished processing dependencies for psycopg2==2.6.1

**Comment by ochriste** [comment]
if you run python in a DOS box (command line, type "python" and return),
can you do "import psycopg2" without error ?

**Comment by Comiii** [comment]
It's not return error:

C:\>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>

**Comment by ochriste** [comment]
the problem here is buildout is trying to compile the psycopg2 from source,
and doesnt seem to see the already installed binaries.

another test you can do is tying to invoque the python executable from your
project buildout folder and try to psycopg2 import command again:
cd <your project>
buildout/bin/python
then the "import psycopg2"

or
cd <your project>
buildout\bin\activate.bat
python
then the "import psycopg2"


you can also try to add
include-site-packages = true
in your project buildout.cfg (which is in your main folder, not in your
buildout/eggs/c2cgeoportal/scaffolds/create/) file, in the [buildout]
section,
where you should already have added the other line Mickael suggested:
allowed-eggs-from-site-packages += psycopg2

other than that, I have no idea what may be wrong with your system.
you dont have several version of python installed on your system, rigth?
