### ISSUE TITLE
Shuldn't we catch the client errors and store them?

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1432]
See also: https://github.com/camptocamp/schweizmobil_re3/pull/406

Also for the server?
http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/pylons/exceptions.html#exception-views

**Comment by elemoine** [comment]
Closure Library includes a logging framework that might be useful. See https://github.com/google/closure-library/tree/master/closure/goog/debug.

**Comment by ybolognini** [comment]
Implemented with Sentry
