### ISSUE TITLE
Deprecated commands in the documentation

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#1434]
Some commands are not longer correct in the 1.6 documentation.

In the [internationalization] (http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/internationalization.html?highlight=install%20po2mo) file, the command ``make -f <user>.mk build install po2mo`` must be replaced by ``make -f <user>.mk build``.

If you search "graceful" in the documentation, you'll find 4 results. Three are just after a ````make build````. This command already calls an Apache's graceful. So, this is useless and needs correction.

In the file [install_application] (http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/install_application.html?highlight=apache/*.conf) we also must remove the instructions to create manually the Apache's .conf file. ``Make build`` already does it.

Thanks to correct that. I don't propose a pull request because I'm soon two weeks in holidays :sunglasses:

**Comment by fredj** [comment]
Can we close this issue ?

**Comment by ger-benjamin** [comment]
yep, thanks
