### ISSUE TITLE
Install problem- can't open file 'bootstrap.py'

### ISSUE THREAD

**Issue by UserGis** [camptocamp/c2cgeoportal#1493]
Hi, I am trying to install c2cgeoportal on Ubuntu 12.04. I install all required components for c2cgeoportal. 
When I try to get python version I am getting this: 
python --version
Python 2.7.3
Now when I run this command:
 python bootstrap.py --version 1.5.2 --distribute --download-base     http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source     http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py

I am getting this error:
python: can't open file 'bootstrap.py': [Errno 2] No such file or directory

**Comment by ochriste** [comment]
just do:
git checkout -b 1.5 origin/1.5

in 1.6 and dev, we dont use buildout anymore

regards
Oliver


> Hi, I am trying to install c2cgeoportal on Ubuntu 12.04. I install all
> required components for c2cgeoportal.
> When I try to get python version I am getting this:
> python --version
> Python 2.7.3
> Now when I run this command:
> python bootstrap.py --version 1.5.2 --distribute --download-base
> http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/
> --setup-source
> http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py
> 
> I am getting this error:
> python: can't open file 'bootstrap.py': [Errno 2] No such file or directory
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/c2cgeoportal/issues/1493>.
> 


-- 
Camptocamp SA
Oliver Christen
PSE A, EPFL
CH-1015 Lausanne

www.camptocamp.com

+41 21 619 10 23 (direct)
+41 21 619 10 10 (centrale)
+41 21 619 10 00 (fax)

---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
