### ISSUE TITLE
Problem installing zc.recipe.egg

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1494]
I am trying to install our project on our production server and I get an error while running `make -f my_file.mk build` the first time:
```
Installing collected packages: cssmin, c2c.cssmin, pyflakes, pep8, mccabe, flake8, pep8-naming, zc.recipe.egg, zc.buildout, z3c.recipe.filetemplate, c2c.template, pyramid-debugtoolbar, c2c.versions
zc.recipe.egg is in an unsupported or invalid wheel
CONST_Makefile:654: recipe for target '.build/dev-requirements.timestamp' failed
make: *** [.build/dev-requirements.timestamp] Error 1
```
Even trying to relaunch the whole thing does not change anything. I always get this error for the installation of `zc.recipe.egg`

To avoid any further self-depression, I tried to run the installation of this egg manually:
```
$ .build/venv/Scripts/pip install zc.recipe.egg
Collecting zc.recipe.egg
Installing collected packages: zc.recipe.egg
zc.recipe.egg is in an unsupported or invalid wheel
```

And... I get the same error.

Has anybody else encountered this error ? I googled a bit, but could not find any helpful information...

The strange thing about that is that this egg is successfully installed on my personal computer and on our dev server... I do not really get what is wrong... Thanks for any advice...

**Comment by kalbermattenm** [comment]
Hmmm... Looks like this is an issue with pip...

I even tried to create an empty virtualenv and then just run `pip install zc.recipe.egg` and it failed with the same error...

So, to resume:
On my personal computer, I am using `pip==6.1.1` -> working
On the dev server, I am using `pip==7.0.1` -> working
On the prod server, pip's autoinstall installed version `pip==7.1.0` -> not working
On the prod server, I forced `pip==6.1.1` -> working

BUT!!! Forcing pip to be installed using a specific version is quite a pain... I had to install `pip==6.1.1` on the system by altering `get-pip.py` as explained here: http://stackoverflow.com/questions/27618094/any-trick-to-make-get-pip-py-install-a-specific-pip-version (last comment), then I had to install my project by launching the base virtualenv command without installing setuptools (altering CONST_Makefile), which threw an error (logical, virtualenv installed itself correctly, but the next command in CONST_Makefile is using pip...), then install pip in my project manually, then relaunched make... quite a pain...

Could somebody at Camptocamp make a test with the latest version of pip (7.1.0, released 2015-06-30) ?

**Comment by ochriste** [comment]
maybe verify that there isnt multiple version of pip installed in the project instance with which you had the problem, as this seem to cause some side effects.

**Comment by kalbermattenm** [comment]
Yeah... This is what I thought... But the project instance was empty in the first place...

I am (or trying too, regarding time...) making a fresh install by isolating the instance completely from the system's Python instance. (which has to be done the same way as described by my previous comment....)

The problem is that setuptools 3.8.x (c2cgeoportal 1.6 is expecting setuptools >= 12 if I am right) is installed on the system's Python instance as this one is needed by the 1.5.x c2cgeoportal instance (and other project). If I updated setuptools, then I break the current 1.5.x instances... which I did yesterday and which is really a bad idea, because this finally crashes the server...

**Comment by ochriste** [comment]
mmm, the packages should get installed in the project venv, it's strange that they get installed in your system's python :/

**Comment by kalbermattenm** [comment]
No, that's not what I meant...

When you run virtualenv, then it makes a copy of your system's local `pip` package, but setuptools 3.8.x does not contain pip, only easy_install, thus I have to first update the system setuptools, which is not a bright idea, as it breaks distribute, which is used by the bootstrap of c2cgeoportal 1.5.x...

On Windows, c2cgeoportal < 1.6 has dependencies which are linked to the system Python instance.

c2cgeoportal >= 1.6, should not have them anymore (I am even sure sure that it does not have), except when you build your project for the first time and run this line of CONST_Makefile: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L685

This is (in my point of view), the only time you need your system Python instance in c2cgeoportal >= 1.6.

I am just hoping I am not writing too many stupid things...

**Comment by ochriste** [comment]
mmm, I just made a test on my windows by creating a new venv and the pip version isntalled by default is a 1.5.6, which is different from my system python's pip which is a 7.1.0.
so it doesnt, at least for me, copy the system python pip in the venv when creating it.
I havent found yet a reason why it would do that for you :/

**Comment by ochriste** [comment]
mmm, unless virtualenv comes with it's own pip archive? I will check that

**Comment by ochriste** [comment]
yeah, thats it, virtualenv has its own installation package of pip and setuptools directly included (in subfolder PythonXX\Lib\site-packages\virtualenv_support)

**Comment by ochriste** [comment]
here is what you can do:
- in your system pyhton, install the virtualenv version which has the correct pip and setuptool version for your project in 1.5
- build a temporary venv
- in that venv, install virtualenv at the lastest version
- build the env for 1.6 using that temporary venv virtualenv

**Comment by kalbermattenm** [comment]
OK, that works !

Now, the other problem...

In your freshly created virtualenv (with virtualenv 13.1.0), are you able to install zc.recipe.egg ?

In my virtualenv, I have this version of pip:
```
D:\Applications\tmp\test2\Scripts>pip -V
pip 7.1.0 from D:\Applications\tmp\test2\lib\site-packages (python 2.7)
```
Trying to install `zc.recipe.egg` throws the following error:
```
D:\Applications\tmp\test2>Scripts\pip.exe install zc.recipe.egg
Collecting zc.recipe.egg
Installing collected packages: zc.recipe.egg
zc.recipe.egg is in an unsupported or invalid wheel
```
Trying to install others eggs, like pyyaml for instance, no problem:
```
D:\Applications\tmp\test2>Scripts\pip install pyyaml
Collecting pyyaml
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |################################| 249kB 660kB/s
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml
  Stored in directory: C:\Users\kalbermattenm\AppData\Local\pip\Cache\wheels\fa\db\f6\dee55793d344f1706dc4a5a693298f0115
241d1085cc212364
Successfully built pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-3.11
```
```

**Comment by kalbermattenm** [comment]
Using any pip version prior to 7.1.0 works...

**Comment by ochriste** [comment]
doesnt work for me either, the problem seems to comes from pip
as a workaround, you can use:
Scripts\easy_install.exe zc.recipe.egg
which works as expected

**Comment by kalbermattenm** [comment]
Hmmm... But I would like to use the automated "make" stuff... and mostly I would like to know why pip does not allow me anymore to install this egg... I will check on the pip github rep if there is any hint there...

**Comment by kalbermattenm** [comment]
But anyway, thanks a lot @ochriste, this thing was driving me crazy ;-)

**Comment by ochriste** [comment]
once the package is installed, and if you dont do a "make cleanall", the make will skip the install of that package

**Comment by kalbermattenm** [comment]
Yeah I know... But I just  would like to understand why this is not working anymore with pip 7.1.0

See https://github.com/pypa/pip/issues/3028

Let's hope for an answer ;-)

**Comment by kalbermattenm** [comment]
OK, I finally some kind of workaround... What I did:
* Uninstall the latest virtualenv version (13.1.0), which contains pip=7.1.0
* Using easy_install, install virtualenv (13.0.3) , which contains pip=7.0.3

Then, running the usual make command (`make -f my_makefile.mk build`) works as it should and everything went alright.

This is only some kind of temporary solution, as it should work with the latest pip version... but it avoids me to do all the manual step described in the other comments of this issue.

Thanks again @ochriste for your help on this one...

**Comment by kalbermattenm** [comment]
Oups... went to fast... 7.0.3 does not work... Trying the same again with pip 7.0.2 (this is really getting on my nerves...)

**Comment by kalbermattenm** [comment]
OK.... I finally made tests by downgrading pip version wise...

The results show that starting with version 7.x of pip, it is not anymore possible to run `pip install zc.recipe.egg`

Thus I have to stick to pip = 6.1.1

**Comment by kalbermattenm** [comment]
@ochriste, just for information, could you tell me which version of pip you are using on your Linux projects ?

**Comment by ochriste** [comment]
7.1.0

**Comment by ochriste** [comment]
I guess it's a Windows python related problem

**Comment by elemoine** [comment]
Just came across the same problem again. It's related to the pip version (recent pip versions use wheels). https://github.com/camptocamp/c2cgeoportal/pull/1435 is directly related as well.

**Comment by sbrunner** [comment]
For 2.0 yes, in 1.6 we can force to use c2c.template==1.2.0dev1

**Comment by elemoine** [comment]
> in 1.6 we can force to use c2c.template==1.2.0dev1

How?

**Comment by sbrunner** [comment]
I don't know if we set REQUIRMENTS to `c2c.template==1.2.0dev1` works, but the simple way (but not the best) is the CONST_versions.txt file ...

**Comment by elemoine** [comment]
You probably mean `CONST_dev-requirements.txt`.

**Comment by sbrunner** [comment]
Effectively :-)

**Comment by kalbermattenm** [comment]
@sbrunner, this was modified in the Luxembourg project, but not in c2cgeoportal 1.6... (only in the master branch)

I would need it in the 1.6 branch. Do you think this would be a problem (otherwise I will just be careful regarding the `CONST_dev-requirements.txt` file when upgrading c2cgeoportal...) ?

**Comment by kalbermattenm** [comment]
This should be backported to c2cgeoportal, otherwise we will always have this issue when re-installing a new version of c2cgeoportal...

**Comment by sbrunner** [comment]
Sorry the issue is so long, then can you open a new issue with a summary?

**Comment by kalbermattenm** [comment]
Should be closed (I cannot close issues...) in favour of https://github.com/camptocamp/c2cgeoportal/issues/1832

**Comment by kalbermattenm** [comment]
Sorry... I am tired... this issue is already closed....
