### ISSUE TITLE
Mapserver variable substitution doesn't work

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1495]
Version 1.6.1 of c2cgeoportal

The mapserver layers that contain a variable to substitute give an error on Postgres. It seems that the variable are not substituted. See code below. 

Thanks

Postgres error : 
STATEMENT:  select "egid",encode(ST_AsBinary(ST_Force2D("the_geom"),'NDR'),'hex') as geom,"gid" from (SELECT t.the_geom, t.gid, t.egid, t.adresse, %s_egid_columns% FROM batiments_egid as t) AS foo where the_geom && ST_GeomFromText('POLYGON((553305.75 145743.999999995,553305.75 146385.000000004,555364.75 146385.000000004,555364.75 145743.999999995,553305.75 145743.999999995))',21781)
syntax error at or near "%" at character 136

Mapserver code (that works on 1.5.4) : 
LAYER
  NAME "batiments_egid"
  METADATA
    "wms_srs" "EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
	"gml_include_items" "all"
	"gml_exclude_items" "gid"
	"gml_types" "auto"	
	"gml_geometries" "the_geom"
	"gml_the_geom_type" "point"	
	"ows_enable_request" "*"
	"default_s_egid_columns" "t.alibi"
	"s_egid_columns_validation_pattern" "^[a-z0-9,._]*$$"	  
  END
  VALIDATION
      ${mapserver_layer_validation}
  END  
  TEMPLATE "ttt"
  TYPE POINT
  TOLERANCE 5
  CONNECTIONTYPE POSTGIS
  PROCESSING "CLOSE_CONNECTION=DEFER"
  CONNECTION "dbname='${vars:db}' host=${vars:dbhost} port=${vars:dbport} user='${vars:dbuser}' password='${vars:dbpassword}'"
  DATA "the_geom FROM (SELECT t.the_geom, t.gid, t.egid, t.adresse, %s_egid_columns% FROM batiments_egid as t) AS foo using unique gid using SRID=21781"

**Comment by kalbermattenm** [comment]
Are your mapfiles `*.map.in` or `*.map.mako` files ?

**Comment by gnerred** [comment]
They are .in files. You think they have to be .mako for the substitution to work ?

**Comment by kalbermattenm** [comment]
Then you should use `${vars:mapserver_layer_validation}` and not `${mapserver_layer_validation}`

If you are using templating files with the `.mako` extension, then use `${my_variable}`

If you are using templating files with the `.in` extension, then use `${vars:my_variable}`

Moreovew, you should probably use `.mako`as `.in` files seem to be deprecated by c2cgeoportal, see https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L20-L40

**Comment by gnerred** [comment]
Thanks you're right. I have set to ${vars:mapserver_layer_validation}, but I still get the same issue.

**Comment by kalbermattenm** [comment]
OK... I did not read everything correctly in your issue...

I think you should move the two last lines of your METADATA into the VALIDATION tag (and remove them from METADATA -> deprecated in MapServer 7!!):

```
VALIDATION
    "default_s_egid_columns" "t.alibi"
    "s_egid_columns_validation_pattern" "^[a-z0-9,._]$$"
END
```
`${mapserver_layer_validation}` contains these two lines for the `%role_id%` substitution variable, and it looks like you are trying to substitute another variable called `s_egid_columns`...

**Comment by asaunier** [comment]
> I think you should move the two last lines of your METADATA into the VALIDATION tag (and remove them from METADATA -> deprecated in MapServer 7!!)

+1

Please note that the validation pattern "metadata" has been renamed as well with MS7. It should be:
```
VALIDATION
    "default_s_egid_columns" "t.alibi"
    "s_egid_columns" "^[a-z0-9,._]$$"
END
```
See the note at http://docs.camptocamp.net/c2cgeoportal/1.6/administrator/mapfile.html#variable-substitution

**Comment by gnerred** [comment]
Thanks a lot @kalbermattenm and @asaunier , now it works :O) !!

This issue can be closed

**Comment by kalbermattenm** [comment]
Thanks @asaunier 

It seems you have good eyes ;-)

**Comment by asaunier** [comment]
> This issue can be closed

Great :)
Don't you have a "close" button at the end of this page as the issue creator?

**Comment by gnerred** [comment]
Yes sorry ;O) closed

**Comment by gnerred** [comment]
In the 1.6.2, it doesn't work anymore.... 

Mapserver config : 
LAYER
  NAME "batiments_egid"
  METADATA
    "wms_srs" "EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
	"gml_include_items" "all"
	"gml_exclude_items" "gid"
	"gml_types" "auto"	
	"gml_geometries" "the_geom"
	"gml_the_geom_type" "point"	
	"ows_enable_request" "*"
  END
  VALIDATION
    "default_s_egid_columns" "t.alibi"
    "s_egid_columns" "^[a-z0-9,._]$$"
  END  
  TEMPLATE "ttt"
  TYPE POINT
  TOLERANCE 5
  CONNECTIONTYPE POSTGIS
  PROCESSING "CLOSE_CONNECTION=DEFER"
  CONNECTION "dbname='${db}' host=${dbhost} port=${dbport} user='${dbuser}' password='${dbpassword}'"
  DATA "the_geom FROM (SELECT t.the_geom, t.gid, t.egid, t.adresse, %s_egid_columns% FROM batiments_egid as t) AS foo using unique gid using SRID=21781"	

Admin config : 
![image](https://cloud.githubusercontent.com/assets/1989467/9677759/0751db68-52de-11e5-9286-5e2e2043d248.png)
![image](https://cloud.githubusercontent.com/assets/1989467/9677773/3bf05cf0-52de-11e5-95ce-7bbb7b1ed551.png)

**Comment by ochriste** [comment]
why the double $ in your regexp ?

**Comment by gnerred** [comment]
Ok I replaced the $$ by $, rebuilt the application, but I have the same problem (secured attributes do not appear when querying).

**Comment by gnerred** [comment]
If you look at comment of @asaunier , you see that he says to put this $$...

**Comment by ochriste** [comment]
mmm, I never had to do that, I guess we have different experience

**Comment by gnerred** [comment]
The config worked well with 1.6.1, and now with 1.6.2 it doesn't work anymore.

**Comment by ochriste** [comment]
mmm, that regexp is still weird, $ indicate a end of line, and [ ] indicate possible characters, but that regexp is missing the characters counter, which should be either *, +, ? or {M,N}
personally I would write it like that : "^[a-z0-9,._]*$"
of course this doesnt mean the problem is there, but it still looks weird to me (you can test with ".*" to see if the problem come from the regexp or elsewhere)

**Comment by ochriste** [comment]
by the way, when you say "it doesnt work", do you mean you always only see "... t.alibi FROM ..." in the sql request when you look at postgres log ?

**Comment by gnerred** [comment]
Yes that's it : 
select * from (SELECT t.the_geom, t.gid, t.egid, t.adresse, t.alibi FROM batiments_egid as t) AS foo where false limit 0
select "gid","egid","adresse","alibi",encode(ST_AsBinary(ST_Force2D("the_geom"),'NDR'),'hex') as geom,"gid" from (SELECT t.the_geom, t.gid, t.egid, t.adresse, t.alibi FROM batiments_egid as t) AS foo where the_geom && ST_GeomFromText('POLYGON((553911.625 146096.875,553911.625 146099.375,553914.125 146099.375,553914.125 146096.875,553911.625 146096.875))',21781)

FYI, the precedent request that select the functionnalities seems to be ok : 
![image](https://cloud.githubusercontent.com/assets/1989467/9678616/484cbc74-52e7-11e5-84e7-15f50a855c16.png)

**Comment by ochriste** [comment]
tested with Stephan on your server: use "^[a-z0-9,._]*$" and rebuild

**Comment by gnerred** [comment]
Fine it works, thanks !
