### ISSUE TITLE
Command 'facter fqdn' returned non-zero

### ISSUE THREAD

**Issue by UserGis** [camptocamp/c2cgeoportal#1499]
I follow the instruction for install on the page:
http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/create_application.html#install-c2cgeoportal

When I try to 
build c2cgeoportal   with:
make build
I have this error:

.build/venv/bin/c2c-template --vars vars.yaml --engine template --files c2cgeoportal/tests/functional/alembic.ini.mako
/bin/sh: 1: facter: not found
ERROR when running the expression ''facter fqdn'': Command 'facter fqdn' returned non-zero exit status 127
make: *** [c2cgeoportal/tests/functional/alembic.ini] Error 1

**Comment by ochriste** [comment]
facter seems to not be available on your system.
I guess the doc should contains some info about that, though im not sure we can do some conditional configuration in the tests.
if you want to run the tests, you need to replace all refernces to 'facter xxx' by some local variables. mmm, maybe define them in your vars.yaml, though im not exactly sure if that will work, as we never call c2c-template directly. in last resort just write them directly in the mako.

**Comment by UserGis** [comment]
Thanks for answering. Just like you had said facter wasn't on the system. I solved problem with this:
sudo apt-get install facter.


Then i continue with installation instructions. 
When I try to build and install aplication with:
make -f gisuser.mk build
.build/venv/bin/c2c-versions CONST_packages.yaml main
tomcat doesn't seam to be installed (required version: 6.0).
No packages found matching deploy.
deploy doesn't seam to be installed (required version: 0.4).
[sudo] password for notroot: 
python-dev doesn't seam to be installed (required version: 2.7).
make: *** [.build/test-packages.timestamp] Error 1

I have tomcat 6.0 installed on system, also I have python-dev 2.7.3

**Comment by ochriste** [comment]
the package checked seems to be hardcoded to use "/usr/bin/apt-cache showpkg <package>"
so it will not work if that command is not available on your system.
the list of package checked is in CONST_packages.yaml,
you should at least edit it to remove/comment the "deploy" package, that package shouldnt be in there. it's something custom we use.

**Comment by ochriste** [comment]
well, each package has it's specific check command in the CONST_packages.yaml.
feel free to adapt the to your system

**Comment by UserGis** [comment]
Ok.Thanks. I change the  CONST_packages.yaml.

Now when I run install  I am getting this:
notroot@ubuntu:/var/www/gisprojekat$ make -f gisuser.mk build
git submodule update --init
You need to run this command from the toplevel of the working tree.
make: *** [.git/modules/gispaket/static/lib/cgxp/HEAD] Error 1

**Comment by ochriste** [comment]
mmm, im not sur why you have a "modules" in that git path
you shouldnt have that.
it should be [.git/gispaket/static/lib/cgxp/HEAD] at best, with the git root folder being "gisprojekat".
the error message means your git root folder is not the "gisprojekat" folder but its parent, i.e. "www", but that will cause you some serious troubles.

your project structure is (or should be) like this:
/var/www/gisprojekat/gispaket/...

when you commited your project in git, you must have done it from *inside* the gisprojekat folder.
from what git say, it looks like you had the following structure when you commited: "some-folder"/modules/gispaket and did the commit from "some-folder"

I would suggest redoing the whole git init/add/commit.

the "git init" must be done *inside* your gisprojekat folder.

**Comment by UserGis** [comment]
Ok. I do git init. Now when try to install I am getting this:
notroot@ubuntu:/var/www/gisprojekat$ make -f gisuser.mk build
git submodule update --init
if [ -e .git/modules/gispaket/static/lib/cgxp/modules/openlayers/HEAD ]; then touch .git/modules/gispaket/static/lib/cgxp/modules/openlayers/HEAD; else git submodule foreach git submodule update --init; fi
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j app.js -o gispaket/static/build
Traceback (most recent call last):
  File ".build/venv/bin/jsbuild", line 9, in <module>
    load_entry_point('JSTools==0.6', 'console_scripts', 'jsbuild')()
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/build.py", line 96, in build
    command()
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/utils.py", line 31, in caller
    return func(args, options, optparser)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/build.py", line 87, in default_merge
    list_only=options.list_only)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 312, in run
    return self.nocat_run(sections, uncompressed, strip_deps, compressor)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 279, in nocat_run
    outputfilename, merged = self.do_section(section, cfg)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 198, in do_section
    merged = self.merge(cfg)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 156, in merge
    files = self.extract_deps(cfg, depmap)
  File "/var/www/gisprojekat/.build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 142, in extract_deps
    raise MissingImport("File from '%s' not found: %s" % (part, fp))
jstools.merge.MissingImport: File from 'first' not found: Ext/adapter/ext/ext-base-debug.js
make: *** [gispaket/static/build/app.js] Error 1

**Comment by ochriste** [comment]
the error means the jsbuild cant find some javascript files it is trying to merge.

please verify that the commands "git submodule update --init" and "git submodule foreach git submodule update --init" worked correctly and that you have now a gisprojekat/gispaket/static/lib/cgxp/ folder containing all the javascript libraries needed (core, dygraphs, ext, ext.overrides, ext.ux, geoext, geoext.ux, gxp, openlayers, openlayers.addins, proj4js, sandbox, styler)

**Comment by UserGis** [comment]
Git command work correctly:
notroot@ubuntu:/var/www/gisprojekat$ git submodule update --init
notroot@ubuntu:/var/www/gisprojekat$ git submodule foreach git submodule update --init
notroot@ubuntu:/var/www/gisprojekat$
But when I go to /var/www/gisprojekat/gispaket/static/lib/cgxp folder is empty and does not containing any file.

**Comment by ochriste** [comment]
mmm, then it's missing the initial cgxp submodule:

git submodule add git@github.com:camptocamp/cgxp.git gisprojekat/gispaket/static/lib/cgxp -b 1.6

**Comment by ochriste** [comment]
redo the two git submodule .. commands after that

**Comment by sbrunner** [comment]
closing
