### ISSUE TITLE
Tomcat 8 MapFishPrint V2 incompatibility

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1503]
seen with Jesse,
in Tomcat 8, it is required that linked files use full path instead of short path,

for example in file WEB-INF/web.xml, the path to the configuration yaml file cant be 

<param-value>config.yaml</param-value>

but must be (for example)

<param-value>/srv/tomcat/tomcat1/webapps/print-<project>/config.yaml</param-value>

otherwise we get some cryptic java error, because the yaml could not be loaded

to confirm with Jesse, but it is possible simply using <param-value>/config.yaml</param-value> could be enough

**Comment by sbrunner** [comment]
Does it will be fixed with the new print war ?

**Comment by ochriste** [comment]
I have not tested yet, I will tell you once I know

**Comment by sbrunner** [comment]
OK :-)

**Comment by ochriste** [comment]
yep it work
Jesse fixed the problem in that version
just so you know, with Tomcat 8, java was not accepting relative path to the config.yaml, so the path had to be the full path.
with his fix, we can use \<param-value\>config.yaml\</param-value\> once again

**Comment by ochriste** [comment]
fixed with http://pypi.camptocamp.net/print-servlet-2.1-SNAPSHOT-IMG-MAGICK-daeea96d2d3b33d6ccf02fe62d81b9c7aa2574a2.war
