### ISSUE TITLE
Print V2 temp folder

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1507]
There is no temp folder if print v2 is used, so there is an error when building the print:

````
cp print/print-servlet-2.1-SNAPSHOT-IMG-MAGICK.war /print-dev.war
cp: cannot create regular file ‘/print-dev.war’: Permission denied
````

I think the PRINT_TMP variable should be before the version test:
https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L242

**Comment by ochriste** [comment]
you must use PRINT_VERSION=2 in your .mk
because the build for MapFishPrint v2 and v3 are different

**Comment by rbovard** [comment]
I already did it, but the assignement is done only with v3, no?

See https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L231

**Comment by ochriste** [comment]
then the makefile should try to run the v3 specific commands, meaning your PRINT_VERSION=2 is ignored for some unknown reason
please verify it is written exactly like that:
PRINT_VERSION ?= 2

**Comment by ochriste** [comment]
then maybe I missread the problem, a moment

**Comment by ochriste** [comment]
yes you are right, I missread the problem, sorry.
it's an error in the makefile
PRINT_TMP ?= /tmp
must be placed before 
ifeq ($(PRINT_VERSION), 3)

**Comment by rbovard** [comment]
Yes exactly :)

**Comment by rbovard** [comment]
Fixed with https://github.com/camptocamp/c2cgeoportal/pull/1481
