### ISSUE TITLE
Database name with a variable

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1509]
In my `vars_<package>.yaml`, i define the variable database with `db: ${instanceid}` but when trying to apply Alembic upgrade script, there is an issue:

````
FATAL:  database "$dev" does not exist
````

That's because in the build `alembic.ini`, the value of URL is
`sqlalchemy.url = postgresql://xxx:xxx@localhost:5432/$dev` and should be
`sqlalchemy.url = postgresql://xxx:xxx@localhost:5432/dev`

So my question is: Is there a way to use a variable in database name?

**Comment by ochriste** [comment]
dont use $ in yaml files,
simply write 
db: {instanceid}

**Comment by rbovard** [comment]
Thanks !
