### ISSUE TITLE
 Problem with sencha-cmd

### ISSUE THREAD

**Issue by UserGis** [camptocamp/c2cgeoportal#1511]
Hi. After install all required packages.  I try to build application. Everything goes ok but when  its start to generate content for mobile I get error  sencha-cmd: not found. I dont now why, I installed sencha cmd 6.0.0.202. 
My ~/.bashrc file contains  this:
export PATH=/opt/bin/Sencha/Cmd/6.0.0.202:$PATH
export SENCHA_CMD_6_0_0="/opt/bin/Sencha/Cmd/6.0.0.202"
When I run sencha in terminal I get this:
notroot@ubuntu:/var/www/gisprojekat$ sencha
Sencha Cmd v6.0.0.202

This is error when I try to build application:
sudo make -f usergis.mk build
[sudo] password for notroot: 
git submodule update --init
Submodule 'gisprojekat/gispaket/static/lib/cgxp' () registered for path 'gisprojekat/gispaket/static/lib/cgxp'
if [ -e .git/modules/gispaket/static/lib/cgxp/modules/openlayers/HEAD ]; then touch .git/modules/gispaket/static/lib/cgxp/modules/openlayers/HEAD; else git submodule foreach git submodule update --init; fi
Entering 'gisprojekat/gispaket/static/lib/cgxp'
Submodule 'core/tests/lib/jasmine' () registered for path 'core/tests/lib/jasmine'
Submodule 'dygraphs/dygraphs/dygraphs' () registered for path 'dygraphs/dygraphs/dygraphs'
Submodule 'geoext' () registered for path 'geoext'
Submodule 'gxp' () registered for path 'gxp'
Submodule 'openlayers' () registered for path 'openlayers'
Submodule 'openlayers.addins/DynamicMeasure' () registered for path 'openlayers.addins/DynamicMeasure'
Submodule 'openlayers.addins/URLCompressed' () registered for path 'openlayers.addins/URLCompressed'
Submodule 'proj4js/proj4js' () registered for path 'proj4js/proj4js'
Submodule 'styler' () registered for path 'styler'
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j app.js -o gispaket/static/build
Writing to gispaket/static/build/app.js (4376 KB)
Done:
gispaket/static/build/app.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j edit.js -o gispaket/static/build
Writing to gispaket/static/build/edit.js (3607 KB)
Done:
gispaket/static/build/edit.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j routing.js -o gispaket/static/build
Writing to gispaket/static/build/routing.js (2996 KB)
Done:
gispaket/static/build/routing.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j api.js -o gispaket/static/build
Writing to gispaket/static/build/api.js (1436 KB)
Done:
gispaket/static/build/api.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j xapi.js -o gispaket/static/build
Writing to gispaket/static/build/xapi.js (3756 KB)
Done:
gispaket/static/build/xapi.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j lang-en.js -o gispaket/static/build
Writing to gispaket/static/build/lang-en.js (33 KB)
Done:
gispaket/static/build/lang-en.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j lang-fr.js -o gispaket/static/build
Writing to gispaket/static/build/lang-fr.js (58 KB)
Done:
gispaket/static/build/lang-fr.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j lang-de.js -o gispaket/static/build
Writing to gispaket/static/build/lang-de.js (56 KB)
Done:
gispaket/static/build/lang-de.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j api-lang-en.js -o gispaket/static/build
Writing to gispaket/static/build/api-lang-en.js (3 KB)
Done:
gispaket/static/build/api-lang-en.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j api-lang-fr.js -o gispaket/static/build
Writing to gispaket/static/build/api-lang-fr.js (3 KB)
Done:
gispaket/static/build/api-lang-fr.js
mkdir -p gispaket/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg -u -j api-lang-de.js -o gispaket/static/build
Writing to gispaket/static/build/api-lang-de.js (3 KB)
Done:
gispaket/static/build/api-lang-de.js
.build/venv/bin/c2c-cssmin  gispaket/static/build/app.css gispaket/static/lib/cgxp/ext/Ext/resources/css/ext-all.css gispaket/static/lib/cgxp/ext/Ext/resources/css/xtheme-gray.css gispaket/static/lib/cgxp/openlayers/theme/default/style.css gispaket/static/lib/cgxp/geoext/resources/css/popup.css gispaket/static/lib/cgxp/geoext/resources/css/gxtheme-gray.css gispaket/static/lib/cgxp/geoext.ux/ux/Measure/resources/css/measure.css gispaket/static/lib/cgxp/sandbox/FeatureEditing/resources/css/feature-editing.css gispaket/static/lib/cgxp/styler/theme/css/styler.css gispaket/static/lib/cgxp/gxp/src/theme/all.css gispaket/static/lib/cgxp/core/src/theme/all.css gispaket/static/lib/cgxp/ext.ux/ColorPicker/ressources/colorpicker.css gispaket/static/lib/cgxp/ext/Ext/examples/ux/css/Spinner.css gispaket/static/css/proj.css gispaket/static/css/proj-map.css gispaket/static/css/proj-widgets.css
Merging gispaket/static/lib/cgxp/ext/Ext/resources/css/ext-all.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/xtheme-gray.css, gispaket/static/lib/cgxp/openlayers/theme/default/style.css, gispaket/static/lib/cgxp/geoext/resources/css/popup.css, gispaket/static/lib/cgxp/geoext/resources/css/gxtheme-gray.css, gispaket/static/lib/cgxp/geoext.ux/ux/Measure/resources/css/measure.css, gispaket/static/lib/cgxp/sandbox/FeatureEditing/resources/css/feature-editing.css, gispaket/static/lib/cgxp/styler/theme/css/styler.css, gispaket/static/lib/cgxp/gxp/src/theme/all.css, gispaket/static/lib/cgxp/core/src/theme/all.css, gispaket/static/lib/cgxp/ext.ux/ColorPicker/ressources/colorpicker.css, gispaket/static/lib/cgxp/ext/Ext/examples/ux/css/Spinner.css, gispaket/static/css/proj.css, gispaket/static/css/proj-map.css, gispaket/static/css/proj-widgets.css to gispaket/static/build/app.css
.build/venv/bin/c2c-cssmin  gispaket/static/build/api.css gispaket/static/lib/cgxp/openlayers/theme/default/style.css gispaket/static/css/proj-map.css
Merging gispaket/static/lib/cgxp/openlayers/theme/default/style.css, gispaket/static/css/proj-map.css to gispaket/static/build/api.css
.build/venv/bin/c2c-cssmin  gispaket/static/build/xapi.css gispaket/static/lib/cgxp/core/src/theme/reset.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/editor.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/pivotgrid.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/menu.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/panel.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/grid.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/debug.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/qtips.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/dd.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/form.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/resizable.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/toolbar.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/slider.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/combo.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/layout.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/dialog.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/core.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/button.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/progress.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/tabs.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/box.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/borders.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/date-picker.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/tree.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/window.css gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/list-view.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/editor.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/pivotgrid.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/menu.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/panel.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/grid.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/debug.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/qtips.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/dd.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/form.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/resizable.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/toolbar.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/panel-reset.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/slider.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/combo.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/layout.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/dialog.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/core.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/button.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/progress.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/tabs.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/box.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/borders.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/date-picker.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/tree.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/window.css gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/list-view.css gispaket/static/lib/cgxp/ext/Ext/resources/css/xtheme-gray.css gispaket/static/lib/cgxp/openlayers/theme/default/style.css gispaket/static/lib/cgxp/geoext/resources/css/gxtheme-gray.css gispaket/static/lib/cgxp/geoext.ux/ux/Measure/resources/css/measure.css gispaket/static/lib/cgxp/gxp/src/theme/all.css gispaket/static/lib/cgxp/core/src/theme/all.css gispaket/static/css/proj-map.css gispaket/static/css/proj-widgets.css
Merging gispaket/static/lib/cgxp/core/src/theme/reset.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/editor.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/pivotgrid.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/menu.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/panel.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/grid.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/debug.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/qtips.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/dd.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/form.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/resizable.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/toolbar.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/slider.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/combo.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/layout.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/dialog.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/core.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/button.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/progress.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/tabs.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/box.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/borders.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/date-picker.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/tree.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/window.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/visual/list-view.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/editor.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/pivotgrid.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/menu.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/panel.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/grid.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/debug.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/qtips.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/dd.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/form.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/resizable.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/toolbar.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/panel-reset.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/slider.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/combo.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/layout.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/dialog.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/core.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/button.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/progress.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/tabs.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/box.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/borders.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/date-picker.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/tree.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/window.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/structure/list-view.css, gispaket/static/lib/cgxp/ext/Ext/resources/css/xtheme-gray.css, gispaket/static/lib/cgxp/openlayers/theme/default/style.css, gispaket/static/lib/cgxp/geoext/resources/css/gxtheme-gray.css, gispaket/static/lib/cgxp/geoext.ux/ux/Measure/resources/css/measure.css, gispaket/static/lib/cgxp/gxp/src/theme/all.css, gispaket/static/lib/cgxp/core/src/theme/all.css, gispaket/static/css/proj-map.css, gispaket/static/css/proj-widgets.css to gispaket/static/build/xapi.css
rm -rf gispaket/static/mobile/build
rm -rf gispaket/static/mobile/archive
cd gispaket/static/mobile && sencha-cmd app build production
/bin/sh: 1: sencha-cmd: not found
make: *** [gispaket/static/mobile/build/production/App/app.js] Error 127
notroot@ubuntu:/var/www/gisprojekat$ sencha-cmd

**Comment by sbrunner** [comment]
You should install sencha ...
