### ISSUE TITLE
Run application

### ISSUE THREAD

**Issue by topgis** [camptocamp/c2cgeoportal#1529]
I set up portal with all install instruction. I work on Ubuntu 14.04 LTS.
I do last step from instruction(crate and populate database with data).

.build/venv/bin/alembic upgrade head
.build/venv/bin/alembic -c alembic_static.ini upgrade head

Now when I try to run http://localhost/mygis, i am getting message Not Found.
mygis is my instanceid

What am I missing?

**Comment by topgis** [comment]
I also include line:
Include /var/www/webgis/apache/*.config in  /etc/apache2/sites-enabled.
var/www/webgis - is my project location path.

**Comment by yjacolin** [comment]
the url should be http://localhost/mygis/wsgi except if you change the default behaviour in your apache config. Don't you?

You can check the Apache log to get more information.
