### ISSUE TITLE
Small icons no more accessible in edit interface since 1.6

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1536]
To reproduce : 
1°/ Go with chrome to http://preprodnew.cartoriviera.ch/edit/?tree_groups=chantiers_planifies_restreints&map_x=560000&map_y=145000&map_zoom=0
2°/ Connect with test/test
![image](https://cloud.githubusercontent.com/assets/1989467/9382941/3cb6fcce-4745-11e5-9caa-eaf2c79c8118.png)

**Comment by sbrunner** [comment]
Your `| n` isn't at the right position ...
https://github.com/camptocamp/cartoriviera_geomapfish/blob/master/cartoriviera/templates/edit.js#L17

**Comment by gnerred** [comment]
Ok thanks a lot :O) ! But I don't think that I did this change ;O)

**Comment by sbrunner** [comment]
It's possible that my fault when I do the migration :-)

**Comment by gnerred** [comment]
No problem :O) !

**Comment by rbovard** [comment]
@gnerred Finally on GitHub!
