### ISSUE TITLE
First load of application in development mode very slow since 1.6

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1537]
Since 1.6, the fisrt load of application is very slow in development mode... It lasts more than 30 seconds, with the message "En attente de preprodnew.cartoriviera.ch". Once loaded, the application goes fast. It doesn't seem to be a problem of infrastructure (network or server), I think it is the application that wait for something, or does a lot of things. If I deactivate sql-alchemy in the loggers, I get the same problem.  

To test : 
http://preprodnew.cartoriviera.ch

**Comment by rbovard** [comment]
Same issue here, any news about this one?

**Comment by sbrunner** [comment]
This wit be a first step to improve the start-up performances:
http://docs.camptocamp.net/c2cgeoportal/1.6/administrator/mapfile.html?highlight=extent#performance-improvement

**Comment by sbrunner** [comment]
On Cartoriviera the WFS capabilities take 12s. and the WMS capabilities 19s. ! And we needs them to start the application...

**Comment by rbovard** [comment]
But why such a difference comparing to 1.5?

**Comment by gnerred** [comment]
Why this was not the case in version 1.5 ? We have no WFS, but WMS does not take so long

**Comment by gnerred** [comment]
;O) @rbovard

**Comment by rbovard** [comment]
:)

**Comment by gnerred** [comment]
Isn't the server able to cache the WFS and WMS capabilities ?

**Comment by ochriste** [comment]
cache usage in development mode ?

**Comment by gnerred** [comment]
Good answer ;O)... So you confirm that this problem of capabilities will not be present in production mode?

**Comment by ochriste** [comment]
well, the first anonymous user to access the projet after a rebuild will not have any cache on first load, but any following user/access will get the wms/wfs getcapability from cache

**Comment by gnerred** [comment]
okay fine. so the remaining question is : why this was not a problem in 1.5 ?

**Comment by kalbermattenm** [comment]
Because there was no development mode running under Apache before...

development.ini was only used when running pserve (thus Python, no Apache...)

If I am right....

**Comment by gnerred** [comment]
Ok thanks !

**Comment by sbrunner** [comment]
> Why this was not the case in version 1.5 ? We have no WFS, but WMS does not take so long

It's due on the Mapserver Update not directly on c2cgeoportal ...

**Comment by sbrunner** [comment]
> Isn't the server able to cache the WFS and WMS capabilities ? 

Yes, it's because of that it's only on the first load

**Comment by gnerred** [comment]
I added the extent propertie, and the first load time passed from 32 sec to 14 sec...

**Comment by asaunier** [comment]
> I added the extent propertie, and the first load time passed from 32 sec to 14 sec...

Yes, there's a huge gain adding this EXTENT parameter to all LAYERs.
Perhaps we should add this tip to the CHANGELOG?

**Comment by sbrunner** [comment]
Already done:
https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L61-L63

**Comment by asaunier** [comment]
Doh! I forgot that I have reviewed this change :P
