### ISSUE TITLE
[Upgrade to 1.6] Tiles configuration

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1546]
Is there something to change when upgrading from 1.5 to 1.6 about tiles configuration? Because without any changes (except the *.in > *.mako), there is a 404 error with the tiles.

**Comment by sbrunner** [comment]
You have a 404 error ? on your testnew server I have en error 403 ...

**Comment by rbovard** [comment]
Try again (I removed some rules)

**Comment by sbrunner** [comment]
You miss to add the rule to create apache configuration:
```
PRE_RULES = apache/mapcache.xml apache/tiles.conf

apache/mapcache.xml: tilegeneration/config.yaml .build/dev-requirements.timestamp
    $(VENV_BIN)/generate_controller --generate-mapcache-config

apache/files.conf: tilegeneration/config.yaml .build/dev-requirements.timestamp
    $(VENV_BIN)/generate_controller --generate-apache-config

clean: project-clean
.PHONY: project-clean
project-clean:
    rm -f apache/mapcache.xml
```
Related documentation: http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/make.html#custom-rules

**Comment by rbovard** [comment]
Thanks, I have never seen this documentation until now...

**Comment by rbovard** [comment]
````
AH00526: Syntax error on line 51 of /var/www/vhosts/nyon-geoportail/private/dev/apache/tiles.conf:
failed to add cache "default": memcache support is not available on this build
````

I think someting is missing on my server?

**Comment by sbrunner** [comment]
Yes, you needs mapcache with the support of memcached, it should be asker to the sysadmins but no one is available now ...

**Comment by rbovard** [comment]
Ok thanks...

@ybolognini Could you handle this please?

**Comment by rbovard** [comment]
It's better with memcache installed :)

Thanks @sbrunner!
