### ISSUE TITLE
WMTS Layers with query layer and a different print layer

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1549]
We have a WMTS layer which we integrated in the Layer tree and want to make it queriable.

We observe 2 problems:
1. When a WMS server URL is given which has the same base URL as the application, the query layers are [](empty) in the viewer.js, although the given WMS layers are queriable.
2. When a WMS server URL is given with another base URL then the application, the query layers are filled correctly, but the local WMS is used and not the given one.

@sbrunner @asaunier don't hesitate to as for an example case, I can reproduce it easily.

c2cgeoportal version: 1.5.4

**Comment by sbrunner** [comment]
Concern code:
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/entry.py#L413-L415
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/entry.py#L422-L447

It's an original simplification that the external WMS can't be queryable...

**Comment by eleu** [comment]
3. If no WMS server URL is given, query does not work.

**Comment by schaettu** [comment]
@eleu:
Probably related: Scale restrictions for external WMS/WMTS in admin interface do not work. Pease confirm.

**Comment by eleu** [comment]
@schaettu scale restriction only apply to the layertree font style for this layer, and not to the visibility in the map for external WMS / WMTS.

**Comment by schaettu** [comment]
@eleu
So there is (at the moment) no way to influence visibility of external WMS/WMTS?
Will this be addressed in GMF 1.6?

**Comment by eleu** [comment]
Re-ping for this issue:

c2cgeoportal 1.6 does not distinguish query layer and WMS layer in layerv1.

If they are different, the query layer is taken for printing event though another layer is configured.

This issue is important to solve.

**Comment by sbrunner** [comment]
Sorry but I  don't understand this issue...

**Comment by ochriste** [comment]
mapserverLayers and queryLayers are not differentiated anymore ?

**Comment by sbrunner** [comment]
Can I have a test-case?
* Permalink
* Actions
* Result
* Excepted result

**Comment by eleu** [comment]
See the complete test case here: https://github.com/camptocamp/schwyz_geoportal/issues/232#issuecomment-253729395

**Comment by ybolognini** [comment]
Done in Schwyz project
