### ISSUE TITLE
[Upgrade to 1.6] Missing language files

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1551]
In upgrade to 1.6 script, the `check_collector?type=all` returns a 404 error about missing language files:

````
Language files: 404 - Not Found (0.0425s)
http://localhost/dev/wsgi/proj/6e0a717fbfd24e6fa0dcf0e131a140e7/build/locale/fr/nyon.json
````

Is there something to define in build instructions to generate this json?

**Comment by sbrunner** [comment]
It's about the ngeo language files, we should disable it by doing the following change in the `vars_<package>` file:
``` diff
 vars:
     ...
     # Checker configuration
     checker:
         ...
-        lang_files: [ngeo, cgxp, cgxp-api]
+        lang_files: [cgxp, cgxp-api]
```
