### ISSUE TITLE
print: caneva size not auto-adapted to the window size

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1570]
in the EPFL Geoportail project, the print caneva doesnt auto-adapt its size anymore.
the caneva size (depending of the selecte print scale) is either undefined or set to the largest possible scale.
it become visible only after selecting a smaller scale

**Comment by ochriste** [comment]
http://geomapfish-demo.camptocamp.net/epfloch2/wsgi/

**Comment by ochriste** [comment]
it seems linked to the initialization of the caneva on first display, because the print form is in an accordion menu

**Comment by asaunier** [comment]
I see no problem with
