### ISSUE TITLE
Access static images in 1.6

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1589]
For some reasons, I access static files from custom HTML pages but I noticed that in 1.6 the scheme changed a bit:
* http://mapfish-geoportal.demo-camptocamp.com/1.5/wsgi/proj/img/edit.png
* http://geomapfish-demo.camptocamp.net/1.6/wsgi/project/90bcdb7ea7504266a81f8e8a165a7d83/img/edit.png

For now, I used this syntax in my mako HTML file `"http://${host}/${instanceid}/wsgi/proj/images/"` but how can I get the `90bcdb7ea7504266a81f8e8a165a7d83`?

Thanks

**Comment by sbrunner** [comment]
The `90bcdb7ea7504266a81f8e8a165a7d83` is generated dynamically than you can't solve all cache issue from static page, but to make it working you can replace it by whatever you want => ``http://geomapfish-demo.camptocamp.net/1.6/wsgi/project/whatever/img/edit.png`` will work :-)

**Comment by rbovard** [comment]
Nice and easy, thanks :)
