### ISSUE TITLE
[Upgrade to 1.6] MapCache doesn't work anymore

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1590]
After the upgrade to 1.6, the tiles served via MapCache return an error.

* http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/dev/theme/cadastre?map_x=507808&map_y=137464&map_zoom=9 __KO__
* http://map.nyon.ch/theme/cadastre?map_x=507808&map_y=137464&map_zoom=9 OK

I noticed the same issue with cartoriviera (ping @gnerred):
* http://preprodnew.cartoriviera.ch/theme/cadastre?map_x=554269.54144902&map_y=145424.32565295&map_zoom=12 __KO__
* http://map.cartoriviera.ch/theme/cadastre?map_x=554269.54144902&map_y=145424.32565295&map_zoom=12 OK 

Do we need to do something for 1.6 since it was working fine in 1.5?

Thanks

**Comment by gnerred** [comment]
+1

**Comment by rbovard** [comment]
`mapcache-tools` version `1.4.0-1+c2c1`

**Comment by gnerred** [comment]
I've installed version 1.6.4, but mapcache does not work. What does the milestone mean ? Will it be fixed in 1.6.5 and not anymore in 1.6.3 ? 
http://preprodnew.cartoriviera.ch

**Comment by sbrunner** [comment]
This is not related on a GeoMapfish release but on our infrastructure, we are working on it :-)

**Comment by gnerred** [comment]
So it will be fixed in 1.6.5 ?

**Comment by sbrunner** [comment]
Issue on mapcache: https://github.com/mapserver/mapcache/issues/131

**Comment by sbrunner** [comment]
We just find the issue on the start of the next week it will be installed on all of our concerned servers :-)

**Comment by gnerred** [comment]
I still have this problem with Mapcache. I have installed 1.6.5. What to do ? Reopen the issue ? Is there a solution ? Thanks

**Comment by ochriste** [comment]
this is a mapserver build issue,
I dont think we have pushed the new Mapserver build on all servers yet

**Comment by gnerred** [comment]
Okay... I plan to put on production the 1.6 next week... Is it possible to push this new MapServer build on my server ?

**Comment by ochriste** [comment]
okay, sorry, I got confused between two different problem.
sbrunner tell me it *should* be fixed with the mapcache 1.4.1-1
but we will check

**Comment by sbrunner** [comment]
Your `apache/tiles.conf` is edited by hand (probably by me to do some tests), you should remove it and build your project again :-)

**Comment by gnerred** [comment]
Ok I just did it, but no changes... 
http://preprodnew.cartoriviera.ch/

**Comment by sbrunner** [comment]
Oh I see, You have a `apache/tiles.conf.mako` but I don't understand why ...
Yhy this file isn't generated with the command `.build/venv/bin/generate_controller --generate-apache-config`?
In your `apache/tiles.conf.mako` the `MapCacheAlias` is commented ...

**Comment by gnerred** [comment]
Those files come from migration. Yes, the tiles.conf is generated with the command you mention, but not at build. Now all is fine, thank you !

**Comment by sbrunner** [comment]
I just do a pull request: #1720 to have a better solution, then with the next version you should remove this mako file.

**Comment by gnerred** [comment]
Thanks excellent !
