### ISSUE TITLE
URL special schema in admin interface

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1591]
According to the doc [1], we can get the server name via keyword `config`

> config: to get the server name from the url, if we use 'config://my_server/icon.png', with the config: servers: { "my_server": "http://example.com/test" } we will get the URL: 'http://example.com/test/icon.png'

My question is: where do we set the config `servers: { "my_server": "http://example.com/test" }`?

Thanks

[1] https://github.com/camptocamp/c2cgeoportal/blob/1.6/doc/administrator/administrate.rst#url

**Comment by sbrunner** [comment]
In the vars files :-)

**Comment by rbovard** [comment]
Thanks :)
