### ISSUE TITLE
View permalink in mobile

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1609]
Is it possible to access a specific view in mobile, like the settings with the permalink `http://mapfish-geoportal.demo-camptocamp.com/1.5/mobile/#settings`?

I think there is a reason for that, but the view name after the `#` is always removed...

Thanks!

**Comment by rbovard** [comment]
Any news on this one? It's just a question, not a feature request :)

**Comment by sbrunner** [comment]
@pgiraud do you have an idea ?

**Comment by rbovard** [comment]
@pgiraud?

**Comment by ybolognini** [comment]
Done in ngeo
