### ISSUE TITLE
[Upgrade to 1.6] Column order in admin panel

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1619]
I noticed that you removed column `order` in admin tables for layers and layergroups, it's quite annoying because it's used to sort layers and layergroups (when sorting will be fixed).

Is it possible to readd this column?

**Comment by sbrunner** [comment]
This column isn't removed, she is moved to "Ordre des liens de l'arbre"...

**Comment by rbovard** [comment]
Ok, thanks. I didn't see that...
