### ISSUE TITLE
[Upgrade to 1.6] Order value not persistent

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1623]
When editing the content of a layer group, the order of items is always reset to 0, 1, 2 etc.

Is it possible to keep the value of order like it was before?

**Comment by sbrunner** [comment]
The order is persistent but it's true that they are rewritten, what's your issue with that?

**Comment by rbovard** [comment]
I use it a lot for sorting all my elements (layers, groups, themes) - if the sort will work again ;)

IE:
* 1000: Theme Cadastre
* 1200: Layer group Cadastre
* 1210: Layer group Points fixes
* 1211: Layer PFP
* 3000: Theme Orthophotos
* 3100: Layer group Rues
* 3101: Layer Fond ASIT VD transparent
* ...

**Comment by sbrunner** [comment]
And now it will be:
```
    1: Theme Cadastre
    2: Layer group Cadastre
    3: Layer group Points fixes
    4: Layer PFP
    5: Theme Orthophotos
    6: Layer group Rues
    7: Layer Fond ASIT VD transparent
    ...

```
Then what's wrong ?

**Comment by rbovard** [comment]
Ok but now with that I lose the order coherence between edited group layers and not edited...

**Comment by sbrunner** [comment]
Temporary yes effectively

**Comment by rbovard** [comment]
It's the reason of my initial question:
> Is it possible to keep the value of order like it was before?

**Comment by sbrunner** [comment]
No, and there isn't reason of that...

**Comment by sbrunner** [comment]
This complicate everything when we add a new layer ...

**Comment by sbrunner** [comment]
Is it ok if we set the order as:
```
    10: Theme Cadastre
    20: Layer group Cadastre
    30: Layer group Points fixes
    40: Layer PFP
    50: Theme Orthophotos
    60: Layer group Rues
    70: Layer Fond ASIT VD transparent
    ...
```
To be easier to add an element behind two others?

**Comment by rbovard** [comment]
I think it's not quite different of 1, 2, 3, 4, etc.

The issue is not the difficulty to add an element between two others (local issue), it's a global issue:

![image](https://cloud.githubusercontent.com/assets/4549666/11113909/d147f5e2-8920-11e5-9e6c-5b1d14bc7a65.png)

In this example, the link between groups `vannes` and `points_reseau` is done via the order value.

Our logic is to use:
* Theme: Nxxx
* Group: xNxx
* Subgroup: xxNx
* Layer: xxxN

Is it more clearer for you?

**Comment by sbrunner** [comment]
After a discus we will add a description fields in the 'layer tree order'
