### ISSUE TITLE
Background layer

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1654]
As in https://map.geo.admin.ch but allays visible

- Affichage sur la carte de widget image (avec text) permettant de sélectionner un layer de background.
- La liste des background est obtenue par le webservice des thème, le résultat sera disponible dans un contrôler.
- La création des layers WMTS doit ce faire avec le même code que ce soit des base layers ou des overlay.
- Dans ngeo il existe déjà une notion de background layers: https://github.com/camptocamp/ngeo/blob/master/src/services/backgroundlayermgr.js

http://camptocamp.github.io/ngeo/master/backgroundlayer.html
http://camptocamp.github.io/ngeo/master/backgroundlayerdropdown.html

**Comment by adube** [comment]
* http://camptocamp.github.io/ngeo/master/examples/backgroundlayer.html
 * http://camptocamp.github.io/ngeo/master/examples/backgroundlayerdropdown.html

**Comment by adube** [comment]
**Question**: est-ce que le service web des thèmes existe déjà ?  Si oui, peut-on s'y connecter maintenant ou avoir un exemple d'utilisation ?  Si non, peut-on avoir un aperçu d'une réponse de requête de thèmes ?

**Comment by sbrunner** [comment]
Yes, here: http://geomapfish-demo.camptocamp.net/2.0/wsgi/themes?version=2&background_layers_group=background
Doc: https://camptocamp.github.io/c2cgeoportal/master/developer/webservices.html

As we previously talk internally it should have an angular service for this webservice, see: https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/themesservice.js

**Comment by adube** [comment]
Thanks.

**Question(s)**: You say that this service has to be used to determine the base layers, but the root content returned appears to be themes.  I recall hearing about a "theme selector".  Is there a relationship between the theme selector and the background layer ?  Shouldn't the theme selector be responsible of querying for themes to the theme service ?

**Comment by sbrunner** [comment]
The service URL is updated :-)

**Comment by pgiraud** [comment]
@adube For now, the idea is to create a Background selector for the mobile version. As designed in the mockups it should be a list with text + thumbnail which appears in a sliding box when clicking on the "background" link in the level 0 in the left menu.
What I would do is follow the ngeo examples as much as possible, but instead of using a select or a bootstrap dropdown, the partial would use a ng-repeat directive. The rest should mostly be HTML in combination with css.

**Comment by adube** [comment]
@pgiraud Understood.

Just to make sure, this is the mockup file I have: https://drive.google.com/open?id=0B3tnRYRfuoYib180LVJ1RzFUWDA

Okay, we're ready to evaluate this as well.  Thanks.

**Comment by adube** [comment]
**Question** : @sbrunner, we need to use a thumbnail for each background layer.  How can we obtain it ?  Is the theme  webservice supposed to be responsible of returning an url or something ?

Thanks

**Comment by sbrunner** [comment]
In all the layer we have a notion of UI metadata, we should use it to add an URL.

**Comment by adube** [comment]
Okay, so just make sure I understood correctly: you will add the thumbnail url in the themes webservice response and I'll be able to use it thereafter.  Is that correct ?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by pgiraud** [comment]
> Just to make sure, this is the mockup file I have: https://drive.google.com/open?id=0B3tnRYRfuoYib180LVJ1RzFUWDA

The document to take into account is the following one: https://docs.google.com/document/d/1ubjfh4hxO05EYJKFOEummEia82jB7TLCJ-S926O5TC4/edit#heading=h.3bbgup6tkvqm
Same images but with additional text.

**Comment by adube** [comment]
@sbrunner Please let me know as soon as the themes webservices returns the thumbnails in the metadata.  Thanks.

**Comment by sbrunner** [comment]
It's done, but the size isn't necessary right ...

**Comment by adube** [comment]
Understood.
