### ISSUE TITLE
Result in a grid

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1655]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231655-Result-in-a-grid

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by svavoi** [comment]
Thanks for the specifications. 
We like the changes made for the actions, the auto select and max feature limit!

Questions:
- Will the sorting of numbers work correctly now? At the moment (1.6) only the sorting of string attributes works fine.
- We are missing the "concatenateTabs" configuration. Will it still be possible? Is this the item "Be able to merge different type name" listed under Features?
- The action and selection buttons are in the screenshot left-aligned but in the prototype right-aligned. What is the plan? We like it more to the left.
- At the moment there exists some more configurations concerning the csv Export like "csvIncludeHeader", "csvSeparator", "csvExportLikeCurrentGrid". Will this still be configurable?
- How are the attributes spread over the width of the grid when there are many attributes (10+)? Does it still work the same or does the width change according to the content of the attribute?

**Comment by vvmalbre** [comment]
Thanks as well from our side!

Here are some remarks and questions:

- Will it still be possible to double-click an attribute to copy it?
- Selection: The following behaviour would be the most logical for me: None of the record is automatically selected in the table. When the user then selects one or more records, changes the tab and comes back, the selected records should be remembered.
- We as are wondering how the width of the attribute columns will behave in the new result grid? Would be nice if the width would consider the content. Maybe there could be set a "maxwidth" for attributes with a lot of text. Could there be integrated an automatic break of the text?
- Is it still possible to adjust the size of the table?
- Would be helpful to have the possibility to define proper buttons to do some more functions with the selected features (in our case f.e. 1:n-service).
- Question for the print: Will all selected records from all tabs appear in the print? This would be really nice.

**Comment by rbovard** [comment]
Ok for me.

Just two remarks about sorting:
* Is it possible to make multiple sorting?
* Maybe it would be nice to be able to reset sorting, so we have three states on click: `ASC`, `DESC`, `reset`

**Comment by ybolognini** [comment]
For this issue we will need to investigate more with @pgiraud (on holidays until Monday 5/23 included) and see what is possible with the new grid. Old ExtJS grid included a lot of functions "automatically". Now we have to check what is possible (sorting, resizing, etc.) with the grid widget we'll use with Ngeo.

**Comment by ybolognini** [comment]
@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

As I said, old ExtJS included several features that aren't available in Bootstrap grid we'll use. Here are the details. Implementing new features is always possible but it's not "automatic" like the ExtJS grid. Please remember that this grid will always be limited in comparison with an Excel sheet!

 * Fixed column widths with minimum column width
 * Horizontal scrolling when table is too wide 
 * No menu to hide/show columns
 
@svavoi 
concatenateTabs, CSV options will be still available. Action and selection buttons aligned to the left. For sorting numbers we have to check.

@vvmalbre 
Yes, still possible to select text to copy. The selection behavior you describe is the one we planned. For the print, we think it's more logical to print what is visible in the grid and highlighted on the map, so only the visible tab.

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

I think it would be good to give some feedback to @ybolognini....

Anyone ?

**Comment by gnerred** [comment]
I will not use result in a grid, so no feedback from my side.

**Comment by rbovard** [comment]
Still the same remarks as I mentioned on 27th April:

> Ok for me.
> 
> Just two remarks about sorting:
> * Is it possible to make multiple sorting?
> * Maybe it would be nice to be able to reset sorting, so we have three states on click: `ASC`, `DESC`, > `reset`

**Comment by svavoi** [comment]
Ok for me. 
Only question left is the sorting of numbers. Would be nice if it will work.

**Comment by ybolognini** [comment]
@rbovard 
Multiple sorting and reset sorting are new features (compared to 1.6). I think they should be discussed, they may be added afterwards.

@svavoi 
Sorting on numbers requires to have the info of the column type. This can be done but as a future improvement.
