### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1656]
* [ ] Unified search - As in LUX and GeoAdmin

### GeoMapFish PSC Minutes
- Décision : résultat recherche avec regroupement comme proposition graphiste
- Décision : fonctionnement recherche (annuler, croix) comme proposé par Pierre

**Comment by fredj** [comment]
Voir https://github.com/camptocamp/ngeo/pull/421

**Comment by sbrunner** [comment]
Replaced by https://github.com/camptocamp/ngeo/pull/421, https://github.com/camptocamp/ngeo/pull/422
