### ISSUE TITLE
Measures and  redlining

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1658]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231658-Measures-and-redlining

**Comment by sbrunner** [comment]
Requires: https://github.com/camptocamp/c2cgeoportal/issues/2040

**Comment by ybolognini** [comment]
PSC:
* In our first specification, we presented the possibility to add a description to the geometry. We thought about that and we would like to remove this feature. Two reasons:
  * This description may be long and it may cause problems as it will be added to permalink
  * This description wouldn't be very visible as the user must click on the geometry to see it
* If we remove the description, then we can merge the two popups and put the styling directly below title

Please answer as soon as possible, so @pgiraud can update the specs and then we can validate specs and start development.

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger

**Comment by kalbermattenm** [comment]
I think that we could stick to how it works in GMF < 2.0... The user can add a label as description...

**Comment by kalbermattenm** [comment]
ping @cedricmoullet What do you think about that regarding your experience with geoadmin ?

**Comment by gnerred** [comment]
+1 for @kalbermattenm . And happy to get all data config in the same window, as asked at our last PSC meeting ;O))

**Comment by svarim** [comment]
+1 for @kalbermattenm Descriptions are not necessarily needed.

**Comment by cedricmoullet** [comment]
I can only say that the possibility to add a popup when clicking on an object is used by the map.geo.admin.ch users. They like to be able to put html code in this popup (image, iframe etc...).

**Comment by rbovard** [comment]
I agree with all of you about @kalbermattenm suggestion.

What @cedricmoullet says is interessant but I think in our case the first idea was to add only text in description, so let's use label for now.

**Comment by gsollberger** [comment]
+1 @rbovard

**Comment by vvmalbre** [comment]
I agree, a description isn't necessary. The use of labels as descriptions is fine.

**Comment by vvmalbre** [comment]
Some feedbacks and questions to the spec:

- When selecting an object in the list and working on it, how do you get back to the list of the objects? Should be done with the back arrow as f.e. in the measuring tool.
- The stroke and opacity sliders are too short; better place them in two lines. A field to enter an exact number would be nice as well.
- When you ask “for desktop and tablet”, what do you mean? Do you implement two different plugins or would you implement a switcher so an integrator can decide “mobile=true” or “mobile=false”?
- Will the layout infos be kept exporting the objects as KML? As for now when you export and import your objects the layout infos are lost. Should be kept.

**Comment by rbovard** [comment]
### Modify vertices

* How is added a new vertice?
* Is it possible to remove vertice?

### Move
* "The user can move the feature by clicking on the "move" button in the contextual menu". Won't be better if it's default action (more or less like it's currently)?

### Rotate
* Any chance to be able to choose rotation point?

**Comment by ybolognini** [comment]
_Copy of the explanation that was sent to PSC-dev_

While thinking more precisely about the redlining feature, we had to change it compared to what was presented during the PSC meeting. Here are the main changes (details are on the specifications page):

- Edition of attributes (title, color) is now in the panel and not in a popup window. This has a lot of advantages: separation between geometry edition and attribute edition, more space to edit geometry, more space if we want to add more attributes or options

- New workflow to edit geometry. We want to reuse the edition of geometry in the future "edit" feature, and for this we need to have an extensible system. We added a small menu when geometry is selected, which contains the actions that can be performed on the geometry.

**Comment by pgiraud** [comment]
> AutoCad approach for actions is nice

Screenshots please!

**Comment by cedricmoullet** [comment]
I simply wanted to say that "We added a small menu when geometry is selected, which contains the actions that can be performed on the geometry." is the AutoCad approach and I find it nice.

**Comment by ybolognini** [comment]
Thanks for the feedback. Here are C2C answers to the comments and questions:

Back to the list when editing attributes @vvmalbre
* When clicking elsewhere on the map, the geometry is deselected and the list is displayed
* But that's right, we also need to add a "back to the list" button to the attributes form (this button will also deselect the selected geometry). @pgiraud will do that

Stroke/opacity sliders @vvmalbre
* That's right, sliders were to short. Specifications have been updated
* We don't think fields with number are needed, redlining editor should stay simple

Desktop/tablet @vvmalbre
* Redlining is for desktop only, but using desktop version on a tablet (with touch) should be possible
* User on tablet will have mobile version by default, but can decide to change to desktop version

KML @vvmalbre
* Not sure I understood the question
* Globally, KML feature will be the same as version 1.6

Add/remove vertices @rbovard 
* A new section in the specifications explain this

Move as default? @rbovard 
* We feel that move feature as a default would interfere with pan (even more with touch)
* Move is at the same level as rotate

Choose rotation point @rbovard 
* We think it would add a lot of complexity
* If really needed we could add it as an enhancement of edit feature

Panel vs. popup @cedricmoullet 
* We also have to think about the future edit feature. This will add a lot of fields and we think it's good to keep them in the panel

**Comment by kalbermattenm** [comment]
For what it is worth... I agree with the explanations given by @ybolognini

**Comment by vvmalbre** [comment]
@ybologini: What I mean: When you draw an object, style it, export it and import it again your style is lost.
