### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1659]
- Possibilité de s’authentifier
- Changer de mot de passe
- Reset du mot de passe
- Demander à l'utilisateur de changer de mot de passe lors du premier login
- Afficher le panel lors de l'ouverture de l'application par un permalien demandant une couche privée (ne comprends pas la détection, doit juste fournir un moyen de le faire)
- Se déconnecter
- Affichage du nom de l'utilisateur connecté
- Remplissage du champ de l'utilisateur par le navigateur (au dernière nouvelle plus possible avec Chrome)
- définir dans les dimensions? le role_id pour la gestion du cache

S’appuie sur la partie serveur:
- Service web de login
- Service web de logout
- Service web de changement de mot de passe
- Service web de reset du mot de passe
- Service web manquant permettant d'obtenir des informations sur l'utilisateur connecter
 * nom de l’utilisateur
 * role_id (pour la gestion du cache)
 * doit changer son mot de passe (boolean)

**Comment by adube** [comment]
**Question**: est-ce que cette tâche comprend du développement de la partie serveur pour l'authentification ?

**Question**: est-ce qu'il y a un mockup pour l'interface de ce panneau ?

**Question**: y a-t-il une différence entre le design de ce panneau entre mobile/tablette/desktop ?

**Comment by sbrunner** [comment]
> Question: est-ce que cette tâche comprend du développement de la partie serveur pour l'authentification ?
No, it's already done here:
geomapfish-demo.camptocamp.net/2.0/*

Doc missing, then quickly:
geomapfish-demo.camptocamp.net/2.0/login.html: login form
geomapfish-demo.camptocamp.net/2.0/login: params: login/password
geomapfish-demo.camptocamp.net/2.0/logout: Logout ...
geomapfish-demo.camptocamp.net/2.0/loginchange: Change password, params: newPassword, confirmNewPassword
geomapfish-demo.camptocamp.net/2.0/loginresetpassword: Send new password, params: login

Sources: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/entry.py#L1246-L1394

Question: est-ce qu'il y a un mockup pour l'interface de ce panneau ?
@pgiraud?

Question: y a-t-il une différence entre le design de ce panneau entre mobile/tablette/desktop ?
@pgiraud?, si possible le minimum...

**Comment by adube** [comment]
@sbrunner I fail tu understand the explanation given for the first question.  Could we discuss this verbally, please ?

**Comment by adube** [comment]
FMI: http://geomapfish-demo.camptocamp.net/1.6/theme/Transport (interface in 1.6).

**Comment by adube** [comment]
FMI: example of asych request with Angular:
https://github.com/camptocamp/ngeo/blob/0d7c65517612119769b446a4b4aaa2d6bda688f2/src/services/print.js

**Comment by adube** [comment]
While not signed in, a "Forgot Password?" link should also be available.  To be discussed with @pgiraud.

**Comment by adube** [comment]
@pgiraud - here's a summary of the questions for you still in progress in this task:

 * Is there a mockup for the UI of the authentication panel(s) ?
 * Is there a distinction between the mobile/desktop/tablet ?
 * The "forgot password" feature would be nice to have, but hasn't been discussed yet.

Thanks.

**Comment by pgiraud** [comment]
@adube I'll get back to you tomorrow with mockups.

**Comment by adube** [comment]
Understood.

**Comment by pgiraud** [comment]
@adube You'll find new mockups in the google drive document. The v2.pdf is also up-to-date.
Don't hesitate to ask me is things are not clear, if I missed something, or if you disagree with the UI/UX.

**Comment by adube** [comment]
@pgiraud : Okay, so here's a summary I would like you to validate

 * all 3 platforms (desktop, mobile and tablet) will use the same components
 * CSS will be used to display them as they should
 * the task at hand covers only the 'panel' itself, not its integration within the toolbar button.

**Question** Would it make sense to create a dummy user for me to be able to test with, one with adube@mapgears.com ?  I'd do all my tests while developing with it.

**Comment by pgiraud** [comment]
> all 3 platforms (desktop, mobile and tablet) will use the same components

Yes, the idea is to get a component that will be shared between the different interfaces.

> CSS will be used to display them as they should

Yes, specific css can be applied so that it adapts specifically. But this styling thing can be taken into account later.

> the task at hand covers only the 'panel' itself, not its integration within the toolbar button.

Right.

**Comment by adube** [comment]
Excellent.  I'll make the estimates right away.

Do you have an answer about my dummy user creation request ?  Thanks.

**Comment by adube** [comment]
@fgravin, I have a technical question for you.  I was asked to use angular's `$http` to do asynchronous requests, but after seeing the [Use goog](https://github.com/camptocamp/ngeo/pull/420#issuecomment-160989737) section in the GMF guideline, I would like to make sure that this is okay.  To me it would mean that I normally should use Closure XHR components to make the queries.

Just checking.  Would you please tell me which one I should use to make async requests ?

**Comment by fgravin** [comment]
You have to use `$http`. We build an angularJs application and we must rely on angular for all this usages. I think the Use.goog thing was more about static functions, and I think this section should be removed, as we are changing direction in ol3 as well.

Use `$http` and take benefit of all angular `services` and `promises` ! ;)

**Comment by adube** [comment]
@fgravin Understood.  Thanks for this great clarification.
