### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1660]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231660-Print

**Comment by vvmalbre** [comment]
Question to the spec:
What’s the idea of being able to change the DPI? Is the idea a user can do so?

**Comment by sbrunner** [comment]
@vvmalbre yes if the server allow it

**Comment by rbovard** [comment]
For me it's a good representation of what we discussed on last PSC, thank you.

Just a question, there is nothing written about interaction between map and print extent (ie: pan and zoom)?

**Comment by sbrunner** [comment]
We pan and zoom the map as usual and the print mask (as for http://beta.geoportail.lu/) stay in place.

**Comment by ybolognini** [comment]
About the DPI, @pgiraud will add the combobox in the specifications page. A list of DPIs can be configured in GeoMapFish (already in 1.6) and the user can choose.

We will also add an example of interaction between map and print extent.

**Comment by kalbermattenm** [comment]
+1 @ybolognini

**Comment by svarim** [comment]
Looks fine for me. Just thought about adding a exit criteria that the style of the redlining features on the print out should correspond the style on the map. Furhermore it is important that the label in print and on the map are exactly the same (what is not the case at the moment).

**Comment by gnerred** [comment]
Ok for me, even if I think that the actual 1.6 GUI (rectangle instead of mask) is much usable... I think we will have complaints from users.

**Comment by gsollberger** [comment]
+1000 @gnerred 
.. a lot of complaints from our rural users ...

**Comment by ybolognini** [comment]
Summary of @pgiraud 's arguments against rotation of mask.
See https://github.com/camptocamp/ngeo/pull/937#issuecomment-216116519
Ping @kalbermattenm @ger-benjamin 

> here are the arguments I have against the rotation of the frame instead of the rotation of map below:
>
>    user may need to lean the head to see what will be printed to have a clear view of what will be printed,
>    after some rotation it's difficult to know where the top of the square is,
>    the square may be truncated, ie. corners may be outside of the visible view, especially at 45°.

Now that I just tested example I'd add one more argument: with the rotating mask it is less coherent because panning pans the map, not the mask. So panning and rotating behave differently.

We can: 
 * Turn the map
 * Turn the mask
 * Let the integrator choose

@ger-benjamin told me that dev is quite simple in the three cases. I would choose third. OK ?

**Comment by gnerred** [comment]
Ok if the integrator can choose.

**Comment by kalbermattenm** [comment]
If it is OK for you, then let the integrator choose....

**Comment by rbovard** [comment]
+1
