### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1661]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231661-Profiles

**Comment by sbrunner** [comment]
Requires: https://github.com/camptocamp/c2cgeoportal/issues/2040

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by rbovard** [comment]
Thanks!

Here are my remarks/questions:
* How is placed the profile chart (overlay of the map, moving pannel like right tools)?
* It's better to have a specific tool for showing profile chart
* We need to have multiple layers (DTM and DMS) like now in 1.6
* The possiblity to export data (PNG, CSV) is very important (see SITN lidar profile)

**Comment by mriedo** [comment]
+1 @rbovard
specific tool is important, function must not be too hidden

Here are some improvements I think would be great ... SITN (Olivier Monod) can help as this will be done in the Lidar profile.
- Possibility to scale X/Y is important ... can be seen in SITN lidar profile
- Possibility to zoom in the profile ...  can be seen in SITN lidar profile
- Possibility to check/uncheck layers (DTM/DMS) in the profile

**Comment by vvmalbre** [comment]
For us it's ok.

**Comment by monodo** [comment]
Just 2 things: 

- Reset zoom button
- Not explicit in the specs but visible on the figures: support polylines

**Comment by mriedo** [comment]
For the polyline drawn for the profile, we should be able to edit the nodes as seen on geoadmin and not go for the non editable line seen on lux geoportal

**Comment by mriedo** [comment]
I believe it's important to have some improvements for the user in the new version and not migrate everything one to one

**Comment by gnerred** [comment]
+1 @mriedo

**Comment by rbovard** [comment]
+1 @mriedo

**Comment by ybolognini** [comment]
@rbovard How is placed the profile chart (overlay of the map, moving pannel like right tools)?

Moving panel like the panel on the right.

@rbovard It's better to have a specific tool for showing profile chart

OK. The profile is designed to be independent from the tool. This means we could also add a button "show profile" to the drawing tools or measures.

@rbovard We need to have multiple layers (DTM and DSM) like now in 1.6

OK. It is included. See chapter "Configuration", value rasterLayers.

@rbovard The possiblity to export data (PNG, CSV) is very important (see SITN lidar profile)

CSV export will be there, like in 1.6. @pgiraud will add it to the specs.
We have to check what is needed for PNG.

@mriedo 
Yes some improvement for the user would be nice, but I guess we have to list the possible improvements and then see what's the effort for each of them. I noted:
 * Scale X/Y
 * Zoom + reset zoom
 * Check/uncheck layers
 
As for the editable polyline, it's OK as profile is designed to be indenpendent from the line drawing.

**Comment by ybolognini** [comment]
Extended profile is planned for 2.2. See https://github.com/camptocamp/c2cgeoportal/issues/2238

**Comment by ybolognini** [comment]
@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Except the CSV export that will be added to the specs and considering enhancements are described in issue #2238 do you validate this specs?

**Comment by gnerred** [comment]
ok for me

**Comment by svavoi** [comment]
ok for me

**Comment by gsollberger** [comment]
ok for me.

**Comment by rbovard** [comment]
Okay for me.
