### ISSUE TITLE
Info bar

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1668]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231668-Map-%28Info-bar%29

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by rbovard** [comment]
Sorry, I missed this one (and I'm not the only one as I can see)...

Typo: the spec name is `Map` but the content is `Info bar`

My remarks / questions:

> The info bar is collapsed by default

I think it's better if integrator can choose default position.

Could we still use some render variables like `prefix` `suffix` `separator `numDigits` like in 1.6? See http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Control/MousePosition-js.html#OpenLayers.Control.MousePosition.Properties

**Comment by vvmalbre** [comment]
+1 @rbovard: Would be good if the integrator could choose the default.

**Comment by gnerred** [comment]
+1 @rbovard

**Comment by mriedo** [comment]
+1 @rbovard

**Comment by ybolognini** [comment]
@rbovard @vvmalbre @gnerred @mriedo 

OK, integrator will be able to configure if infobar is open or closed by default.

Render variables will be added like in 1.6.

**Comment by gsollberger** [comment]
ok for me.
