### ISSUE TITLE
Mobile measure

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1671]
## Features
Bullet points list of features (with checkboxes)

The goal is to add point and line measure to mobile app. Behavior is very similar to GeoMapFish 1.6, see http://geomapfish-demo.camptocamp.net/1.6/wsgi/mobile/ (bottom right). Main difference is that tool activation must be done using right panel and not a permanent button like with version 1.6.

In case of point measure, a call is made to a service (see below) in order to get altitude. This call is made only when panning stops.

* [ ] Tool menu
* [ ] Activate tool
* [ ] Close tool
* [ ] Add a cross in the center of screen
* [ ] Add first point

#### Point

* [ ] Altitude service call (after a short delay)
* [ ] Measure (x/y) (displayed at all time)
* [ ] Measure (z) (displayed at service response)

#### Line

* [ ] Add next point
* [ ] Measure displayed at all time (even when map is being panned)
* [ ] Switch between m/km
* [ ] Start again

## Layout
Mockups and description of UI workflows

Line measure same as http://geomapfish-demo.camptocamp.net/1.6/wsgi/mobile/ (bottom right). Tool activation done via right panel, two levels of menu (first level: measure tools, second level: point, line).

![measure_layout](https://cloud.githubusercontent.com/assets/1180264/12110273/d8303fa6-b38a-11e5-89ba-986c796bf62d.png)

![mobile_measure_length](https://cloud.githubusercontent.com/assets/319774/12171722/68bc5376-b54c-11e5-89a0-6536076d62ee.png)

![mobile_measure_length_2](https://cloud.githubusercontent.com/assets/319774/12171725/6c785be0-b54c-11e5-94b0-028dbace54c1.png)

![mobile_measure_length_3](https://cloud.githubusercontent.com/assets/319774/12171727/6f985a78-b54c-11e5-975c-93f6241ca3d6.png)

![mobile_measure_coordinates](https://cloud.githubusercontent.com/assets/319774/12171729/733bc782-b54c-11e5-8a28-4e03ae36833b.png)

(Don't pay too much attention to styling, colors, and fonts)

#### Line

Measure displayed bottom right of the center cross (like in GMF 1.6)

#### Point

X/Y position displayed bottom right of the center cross (same design as for line). Altitude shown below X/Y position.

## External Resources
Services to be used with description of interfaces

#### Altitude service

Existing service in GeoMapFish.
https://camptocamp.github.io/c2cgeoportal/master/developer/webservices.html#raster
(service configuration: https://camptocamp.github.io/c2cgeoportal/master/integrator/raster.html)

## Architecture

* Create a new class DrawInteractionMobile in ngeo
  * inherits from ol.Interaction
  * provide public methods to trigger draw events (start, add point, end)
* Create a new class MeasureLengthMobile in ngeo
  * inherits from ngeo.interaction.MeasureLength
  * overrides getDrawInteraction method to return a DrawInteractionMobile
* Update ngeo.interaction.Measure for its handleEvent method to manage view:center:change event if mobile.
* Create a directive MeasureManager in gmf that switch between 3 measures interactions.
  * use a ngeoBtnGroup
  * additionnal dev in ngeoBtnGroup are not part of the PR (if we want to combine it with ngeo.ToolActivate)
* Create a directive (as an ngeo example) to show how to use the new mobile interactions.
* Tests
* Examples
* Mobile apps

## Configuration
What is configurable, where and by whom (user, integrator)

* (by integrator) Number of significant digits for
  * line measure
  * x/y position 
* Raster service URL
* Raster layers (default to all)

## Implementation Examples
Existing code, interesting websites

* Ngeo example - http://camptocamp.github.io/ngeo/master/examples/measure.html

## Exit-criteria
What must be tested so one can say 'it's done', for example demo example (with checkboxes)

* [ ] Mobile demo includes new tool 
* [ ] Test cases OK

## Documents
Documents to update: test cases, user doc, dev doc (with checkboxes)

* [ ] New test cases in testbook
* [ ] User documentation
* [ ] Code documentation

**Comment by adube** [comment]
Le lien http://camptocamp.github.io/ngeo/master/measure.html semble incorrect.

**Comment by adube** [comment]
Avez-vous un mockup de à quoi doit ressembler l'outil ?

**Comment by sbrunner** [comment]
@pgiraud?
Globally the tool should hare the same functionality :-)

**Comment by adube** [comment]
@sbrunner Okay, would you please make sure that's the case ?  Thanks.

**Comment by pgiraud** [comment]
> Globally the tool should hare the same functionality :-)

@pgiraud what do you mean? Share the same functionality with what?

**Comment by adube** [comment]
@pgiraud, I suppose what @sbrunner meant is that the mobile measure tool should look like the one featured here: http://geomapfish-demo.camptocamp.net/1.6/mobile/.

See the button at the bottom right.  Should the tool in ngeo look like this ?

**Comment by pgiraud** [comment]
@adube Unless you think of an other example of a good UX for a measure tool in a mobile (touch) device we can go with the same behavior as the one you point (ie. geomapfish 1.6 demo or http://sitn.ne.ch/mobile).
Of course, this behavior is specific to mobile. So this should be coded specifically too. I mean the components, directives and so on should use "mobile" in their name I think.

**Comment by adube** [comment]
@pgiraud The tool demonstrated in the demo is the one with the best UX I've seen so far.  I agree to go with this approach.

I also agree that it should have components/directives with the "mobile" in their names.

With this, We're ready to evaluate the efforts required for this tool.  Thank you.

**Comment by adube** [comment]
This task is now on hold.  More discussion is required regarding the design, as stated by @ybolognini.

**Comment by adube** [comment]
FMI: http://beta.geoportail.lu/theme/main?version=3&zoom=15&X=666357&Y=6423528&lang=en&layers=146&opacities=0.5&bgLayer=basemap_2015_global

**Comment by adube** [comment]
@pgiraud We need to be able to show the result in m or km and allow the user to switch between the 2.  From a UI perspective, how/where do you suggest we show this switcher ?  Thanks.

**Comment by pgiraud** [comment]
I don't think the user should be able to switch from one unit to another. The switch should be automatic. Determined by the system.
The `measureLength` interaction is already doing the job. See http://camptocamp.github.io/ngeo/master/examples/measure.html

**Comment by adube** [comment]
@pgiraud : Undertood.

@fredj I don't think we'll end up using the measure coordinate interaction in our case.
