### ISSUE TITLE
Querying results - CSV export plugin

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1672]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231672-Querying-results-CSV-export-plugin

**Comment by sbrunner** [comment]
Requires: https://github.com/camptocamp/c2cgeoportal/issues/1655

**Comment by ybolognini** [comment]
Specifications are now ready for validation!  (simple link to grid specs)

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by mriedo** [comment]
Ok, perfect.

**Comment by gnerred** [comment]
Ok for me

**Comment by gsollberger** [comment]
Ok for me.

**Comment by vvmalbre** [comment]
Fine for us.

**Comment by svavoi** [comment]
Ok for me.

**Comment by rbovard** [comment]
Okay for me.

**Comment by tsauerwein** [comment]
A first implementation is in https://github.com/camptocamp/ngeo/blob/master/src/services/csvdownload.js. Still to do:

* [ ] Make option `separator` and `quote` configurable.
* [ ] Take remaining configuration options into account: `csvIncludeHeader`, `csvExtension`, `csvEncoding` and `csvExportLikeCurrentGrid`

**Comment by fredj** [comment]
fixed with https://github.com/camptocamp/ngeo/pull/1734
