### ISSUE TITLE
Strange releases...

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1680]
These are quite strange releases...:

https://github.com/camptocamp/c2cgeoportal/releases/tag/z-a0926c7218e9b20b252e727e2286902da0c12a6b

https://github.com/camptocamp/c2cgeoportal/releases/tag/z-5fe8c96826099a677a140b47192e7e032885d176

Was that done on purpose ?

**Comment by sbrunner** [comment]
I'm just doing some tests ...

**Comment by kalbermattenm** [comment]
OK, thanks for your answer. I was quite proud to have a release for one of my own PR... ;-)

**Comment by sbrunner** [comment]
:-)
