### ISSUE TITLE
c2ctool upgrade step2 doesnt replace correctly the "package" and "version" variable

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1693]
The upgrade is nearly done, now you should:
- Test your application.
To continue type:
.build/venv/bin/c2ctool upgrade --c2cgeoportal-url http://pypi.camptocamp.net/internal-pypi/index/%(package)s-%(version)s.tar.gz preprod.mk 1.6.4 --step 3

**Comment by sbrunner** [comment]
No it's right it's replaced later, But the issue is that this argument appears, You should just remove it.
