### ISSUE TITLE
Merger internal external Layer 

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1704]
* [x] Créer table serveur OGC (wms/wfs)
      * id
      * name
      * description
      * url
      * type (mapserver, geoserver, qgis) (principalement print)
      * image_type (image/png, image/jpeg)
      * auth: main/parent/none
      * WFS suport
 * [x] Merger internal external Layer
 * [x] Mettre a jours le webservice de theme v1 (pas de chagement d'API)
 * [x] Mettre a jours le webservice de theme v2 (changement d'API, ajouter une section servers)

**Comment by ochriste** [comment]
can you have a look at db demo_geomapfish_2_0_och2 on the demo server and confirm it seems correct ?

**Comment by ochriste** [comment]
cf https://github.com/camptocamp/c2cgeoportal/blob/merge-internal-external-wms-layers/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/116b9b79fc4d_internal_and_external_layer_tables_.py

**Comment by sbrunner** [comment]
For me `layer_ogc` is an incorrect name shouldn't be `ogc_server` or `server_ogc` ?

**Comment by sbrunner** [comment]
I just see that `is_single_tile` should be in the `ogc_server` table...

**Comment by sbrunner** [comment]
Other little things that should be better:
 * I prefer to fill the table first with internal layers, it makes more sense for me...
 * You can have id collision on the `ogc_server` table because you don't use the sequence here https://github.com/camptocamp/c2cgeoportal/blob/merge-internal-external-wms-layers/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/116b9b79fc4d_internal_and_external_layer_tables_.py#L93 and here https://github.com/camptocamp/c2cgeoportal/blob/merge-internal-external-wms-layers/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/116b9b79fc4d_internal_and_external_layer_tables_.py#L101

**Comment by sbrunner** [comment]
Good job for the first step :-)
