### ISSUE TITLE
Layertree mobile

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1707]
Transparency, Zoomto, Metadata, Legend, Timeslider options as in GM 1.6 MOBILE : I button (metadata & legend)

### GeoMapFish PSC Minutes
- **Réfléchir** à la possibilité de mettre plusieurs colonnes de thèmes
- **Réfléchir** à avoir un feedback lorsqu'une couche ne s'affiche pas à une certaine échelle
- Revoir avec graphiste pour bouton de sélection dans arbre des couches
- Décision : légende dans l'arbre
- Décision : ajouter icône de la thématisation de la couche

## Features
 * [x] Add WMS layers
 * [x] Select / unselect layer / group of layers
 * [x] Add WMTS Layers
 * [x] Manage 'visible by default'
 * [x] Grey when not visible
 * [x] Zoom to visible scale
 * [x] Manage when WMTS source not available
 * [x] Remove layers from map when corresponding theme is closed.
 * [x] Icon of layers appearance
 * [x] Display legend
 * [x] Display metadata

Other todo (technical)
 * [x] Solve recures user template
 * [x] Integrate the new version of the theme web service
 * [x] Integration in mobile application (PR)
 * [x] Use the central service from Florent (PR)
 * [x] Integrate with Theme and WMS browser
 * [x] CSS for metadata in "popup" display mode

## Improvement
 * [ ] One wms layer for allwms layers in internal wms groups

## Layout
(see general mockup)
### to clarifiy
* [ ] Revoir avec graphiste pour bouton de sélection dans arbre des couches
* [x] Décision : légende dans l'arbre
* [x] Décision : ajouter icône de la thématisation de la couche

## External Resources
Services to be used with description of interfaces

None (client only or already done)

## Configuration
What is configurable, where and by whom (user, integrator)

 - default template can be changed (integrator)
 - css can be changed (integrator)
 - User can change the layertree content by the c2cgeoportal's administrator interface

## Implementation Examples
Existing code, interesting websites

* Ngeo example - http://camptocamp.github.io/ngeo/master/contribs/gmf/examples/layertree.html

## Exit-criteria
What must be tested so one can say 'it's done', for example demo example (with checkboxes)

* [x] Mobile demo includes layertree
* [x] Test cases OK (tests in  the layerHelper service)
* [ ] Layertree's apparance and fonctionnalities are validated by the PSC

## Documents
Documents to update: test cases, user doc, dev doc (with checkboxes)

* [x] New test cases in testbook
* [x] User documentation
* [x] Code documentation

**Comment by ger-benjamin** [comment]
Questions:
 - Should we display WMTS with unavailable source ? How ?  Should we retry to load it ?

**Comment by sbrunner** [comment]
We should add it with a user feedback...
