### ISSUE TITLE
Theme selector

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1709]
Flush mode have to be implemented as in GM 1.6

- Affichage de widget image avec text permettant de sélectionner un thème.
- Le thème est charger par l'arbre des couche

**Comment by adube** [comment]
Completed in https://github.com/camptocamp/ngeo/pull/497

@sbrunner you can close this ticket.

**Comment by sbrunner** [comment]
@adube Thanks :-)
