### ISSUE TITLE
Theme selector (add)

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1710]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231710-Theme-selector-%28add%29

**Comment by fgravin** [comment]
Closed with https://github.com/camptocamp/ngeo/pull/497

**Comment by sbrunner** [comment]
camptocamp/ngeo#497 is not the add mode ...

**Comment by vvmalbre** [comment]
Question to the spec:
We actually don’t understand very well what’s the idea of changing from themes to groups? Would this have any consequences on how to create the layer tree? Or can it be kept as it is now? Would be happy to get some more explanations here, thanks

**Comment by sbrunner** [comment]
@vvmalbre witch part of the spec do you speak about?

**Comment by vvmalbre** [comment]
@sbrunner 
Layout section. Maybe it's just concerning the messaging system and nothing in the layer tree at all?

**Comment by sbrunner** [comment]
The issue is that a theme is combine with possibly more than one group, then we can have the following messages on adding the theme 'cadastre' (example) (new style):
first message: "group roads already been added"
second message message: "group buildings already been added"
and if we replace group by theme it's incoherent.
An other possibility is to display the message e.-g.: "roads already been added" without specifying the type...

**Comment by rbovard** [comment]
Hard to comment those specs as I'm not a "add theme" user.

**Comment by ybolognini** [comment]
@vvmalbre 
In "add" mode, when a user adds a theme it actually adds the theme's groups to the layer tree (1.6 and 2.0). A theme can have several groups. That's why we proposed the message "groups a, b, c were already loaded".
But I think @sbrunner 's proposal is good. We could remove the mention to theme or groupe and simply say "a, b, c already loaded".
Anyway, it is always possible to customize the message via the translations system.

**Comment by vvmalbre** [comment]
Ok, thanks. Yes, I think a message without specifying about themes or groups is the best as suggested by @sbrunner

**Comment by gnerred** [comment]
Ok for me. Just keep in mind that it is important for us to be able to have a huge amount of background layers in the list.

**Comment by gnerred** [comment]
Ok for me, even if I think that the actual 1.6 GUI (rectangle instead of mask) is much usable... I think we will have complaints from users.

**Comment by svarim** [comment]
+1 for "a, b, c already loaded"
It would be good to have screenshots or  graphics of the add theme in the specs.
A close all button is essential for closing all selected layers (already ordered for GMF 1.6/2.0; BS).

**Comment by jlap** [comment]
I talked about this to @ger-benjamin  and he already finished pretty much all of the task, only thing left would be the error messages. Am I missing something?

**Comment by sbrunner** [comment]
As I see the missing parts are:
* Don't display the "selected" theme name on the "button"
* Don't have a tick (v) on the "selected" theme 
* Finally with this mode (or component) we shouldn't have the notion of selected theme
* Configure it in the desktop alt demo application: https://github.com/camptocamp/ngeo/tree/master/contribs/gmf/apps/desktop_alt

**Comment by sbrunner** [comment]
Visible here: https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/index.html

**Comment by jlap** [comment]
> Don't display the "selected" theme name on the "button"
> Don't have a tick (v) on the "selected" theme
> Finally with this mode (or component) we shouldn't have the notion of selected theme

I saw the theme add feature in action on another (live) server, where these didn't seem to occur. I sent you a hangout invite so we can chat about it as I'm a bit confused.

**Comment by jlap** [comment]
After talking to @sbrunner, looks like what's left for me is to integrate the add mode to the destop_alt example.

**Comment by sbrunner** [comment]
missing: Showing a message when a group is already loaded
