### ISSUE TITLE
[Upgrade to 1.6.6] mapcache.xml is missing

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1729]
After upgrading to `1.6.6`, the file `apache/mapcache.xml` is missing and broke the build...

````
AH00526: Syntax error on line 51 of /var/www/vhosts/nyon-geoportail/private/dev/apache/tiles.conf:
failed to parse file /var/www/vhosts/nyon-geoportail/private/dev/apache/mapcache.xml. Is it valid XML?
Action 'graceful' failed.
The Apache error log may have more information.
CONST_Makefile:781: recipe for target '.build/apache.timestamp' failed
make: *** [.build/apache.timestamp] Error 1
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 9, in <module>
    load_entry_point('c2cgeoportal==1.6.6', 'console_scripts', 'c2ctool')()
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 105, in main
    c2ctool.upgrade()
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 241, in upgrade
    self.step2()
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 394, in step2
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_dev.mk', 'build']' returned non-zero exit status 2
````

It's probably related to #1720

**Comment by sbrunner** [comment]
I define two times the role to generate the `apache/mapcache.xml` file ...

You should be able to do the following change on the second rule in the `CONST_Makefile`:
``` diff
-apache/mapcache.xml: tilegeneration/config.yaml .build/dev-requirements.timestamp
+apache/tiles.conf: tilegeneration/config.yaml .build/dev-requirements.timestamp
 	$(VENV_BIN)/generate_controller --generate-apache-config
```

**Comment by rbovard** [comment]
Thanks, it's working now :)

PS: shouldn't you tag it as `1.6.6.1` since it's a bug fix?

**Comment by sbrunner** [comment]
Ideally why not but our current build system can do only release named x.y.z ...

**Comment by gnerred** [comment]
I have the same problem, but I'm not able to apply the workaround... 
1°/ I modify the CONST_Makefile as mentionned, commit and push
2°/ I do the migration steps and get the same error in step 2. The step 2 replaces the CONST_Makefile with the original version without workaround... What do I wrong ?

**Comment by sbrunner** [comment]
You should apply the workaround after the step 2 :-)

**Comment by gnerred** [comment]
and redo the step 2 or directly to the step 3 ?

**Comment by gnerred** [comment]
okay, it works if I generate manually the mapcache.xml and then continue with the step 3... Bad release, I will come back to the 1.6.5 for my migration next week...

**Comment by rbovard** [comment]
No, wait for `1.6.7` ;)

**Comment by gnerred** [comment]
If i comes before my migration date, and if I have time to test it...
