### ISSUE TITLE
[Upgrade to 1.6] Default functionalities

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1735]
According to https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L116-L124, some functionalities are now default (see #1611), so I removed them but they are not available in dropdown...

![image](https://cloud.githubusercontent.com/assets/4549666/10666607/e85db4be-78d2-11e5-8c44-c9e95afb24a0.png)

Where can I see if they really are default?

**Comment by sbrunner** [comment]
In the `CONST_vars.yaml` file ...

**Comment by rbovard** [comment]
They are there...
