### ISSUE TITLE
bad upgrade shortcuts

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1745]
I see you implemented some "shortcuts" commands for the upgrade,
but these shortcut are not calling the right commands:

for example:

`make -f och.mk upgrade2`

will trigger:

`.build/venv/bin/c2ctool upgrade ochngeo.mk   --step 2`

instead of 

`.build/venv/bin/c2ctool upgrade och.mk master --step 2`

the .mk name is automatically recoverd from the INSTANCEID (ochngeo in my case) and ignores the mk name passed in parameter,

also the target revision is missing completely

**Comment by sbrunner** [comment]
In the do it's written:
> We considers that your makefile is named `<instanceid>.mk`, if it’s not the case add in your Makefile `UPGRADE_MAKE_FILE = <user.mk>`

It should solve your issue

**Comment by ochriste** [comment]
whats the point of providing the mk file in the upgrade shortcut then ?
the doc at http://docs.camptocamp.net/c2cgeoportal/master/integrator/upgrade_application.html#easy-upgrading-an-application say:

"make -f <makefile> upgrade"

if <makefile> is ignored, that command is misleading and should be changed to "make upgrade"

**Comment by ochriste** [comment]
I think it's highly confusing

**Comment by rbovard** [comment]
> I think it's highly confusing

+1!

**Comment by sbrunner** [comment]
The main issue I have is that I can't get the called Makefile in the Makefile ...

And to make `make upgrade` working I should Create a `Makefile` file that can have the bord effect that `make build` don't return an error, and we shouldn't run it.

And Finally we needs the required Makefile name that is build from information that come from the `och.mk`.

Sorry for confusing but actually I haven't a solution...

**Comment by ochriste** [comment]
ok for the principle, but Im for adding a check when the command is executed which compare the name of the .mk passed in parameter and the one used internaly: if the name are different there should be a user warning/notice telling the user about this.

**Comment by ochriste** [comment]
also, there still the version missing from the underlying command, is that also caused by this mk confusion ?

**Comment by sbrunner** [comment]
Does it will be clearer: #1747?

**Comment by ochriste** [comment]
perfect!
