### ISSUE TITLE
Missing log info when user logs in 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1749]
In 1.5, the Apache error.log contained a line for each user/password connection : 

[Wed Oct 28 09:42:17 2015] [error] 2015-10-28 09:42:17,762 INFO  [c2cgeoportal.views.entry][Dummy-11] User 'gnerred' logged in.

In 1.6 I cannot find this in error log. Did I miss a configuration ?  Thanks

**Comment by rbovard** [comment]
Is it for statistical purpose? If yes, see #1084

**Comment by gnerred** [comment]
Yes but not only. I need to know the date and time of connection of each user. @sbrunner , is it possible to activate this log as in 1.5 ?

**Comment by gnerred** [comment]
And FYI, it seems to me that this log worked in earlier versions of 1.6....

**Comment by rbovard** [comment]
Just tested on my 1.6.6 and I have it:

````
[Thu Oct 29 09:51:00.979329 2015] [wsgi:error] [pid 6664] 2015-10-29 09:51:00,979 INFO  [c2cgeoportal.views.entry][Dummy-2] User 'bovard.r' logged in.
````

**Comment by gnerred** [comment]
In which file ?

**Comment by rbovard** [comment]
`/var/www/vhosts/nyon-geoportail/logs/nyon-geoportail_error.log`

**Comment by gnerred** [comment]
I have 1.6.6, and nothing is written in my error file... @sbrunner, an idea ?

**Comment by gnerred** [comment]
Other info... It works on my preprod application, but not on the prod... So it seems to be a config issue. An idea of which one ?

**Comment by ochriste** [comment]
I have to check but maybe it only log when in debug mode

**Comment by ochriste** [comment]
log.info("User '%s' logged in." % login)

it should be logged if you have at least level "info" for the logger config in your production.ini

**Comment by ochriste** [comment]
I need to confirm with sbrunner, but I think you can try to add the c2cgeoportal logger in your production.ini, as it is in your development.ini
you need to modify the block [loggers] and add the block [logger_c2cgeoportal]

**Comment by gnerred** [comment]
Yes it works if I modify the block [loggers] and add the block [logger_c2cgeoportal]. Can this config affect performance ?

**Comment by sbrunner** [comment]
Yes, but it shouldn't be perceptible, ...

**Comment by gnerred** [comment]
Ok thanks
