### ISSUE TITLE
Build under Windows

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1764]
It should work ...

**Comment by kalbermattenm** [comment]
Yeah...

I am trying to install ngeo (thus also ol3) currently on my computer and I am encountering huge problems with Node and npm...

I will try to make a complete ordered stack of what is not working...

**Comment by sbrunner** [comment]
The «It should work ...» will means that actually it don't :-)

**Comment by ochriste** [comment]
fixed with https://github.com/camptocamp/c2cgeoportal/pull/1945
