### ISSUE TITLE
Geolocation Mobile

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1765]
Bouton sur la carte permettant de ce géolocaliser:
sur mobile:
- click -> track la position
- click -> stop le tracing

La détection desktop mobile est un problème résolu en dehors du composant.

http://camptocamp.github.io/ngeo/master/geolocation.html

**Comment by adube** [comment]
http://camptocamp.github.io/ngeo/master/examples/geolocation.html

**Comment by adube** [comment]
**Question**: Il est expliqué qu'au click du bouton on doit centrer sur la position.  Donc, si je comprends bien, c'est toujours le cas, même si on track ou si on arrête ?  Exemple:

 * bouton inactif
 * premier click: active le bonton, actions:
  * recentre
  * track la position
 * deuxième click: désactive le bouton, actions:
  * recentre
  * arrête le tracking de la position

**Question**: Lorsque la position est modifiée, est-ce que la carte est de quelconque manière "naviguée automatiquement" à l'emplacement de la nouvelle position ?

**Comment by sbrunner** [comment]
I think with the new descriptions it's clearer ...

**Comment by ger-benjamin** [comment]
The previous week, I was stalled on some tasks so I've decided to begin a geolocation directive for GMF.

You can use my work (1 commit, in progress, must be completed), it's on the ngeo branch 'gmf_geolocation' (https://github.com/camptocamp/ngeo/commits/gmf_geolocation).

**Comment by adube** [comment]
@ger-benjamin Thanks.  This looks promising.

@sbrunner In this task, you speak of "tracking".  In #1766, you speak of "centering".  Is there a clear distinction between the two ?  It would seem so.

**Comment by sbrunner** [comment]
When we pan we will cancel the tracking!

**Comment by adube** [comment]
Here's an up-to-date description of the behaviour the tool must have.  It's in French and comes from @ybolognini :

**Mobile**

- Clic sur le bouton, recentrage et affichage du point
- Tracking (le point bouge en direct en fonction du GPS)
- Le point reste lorsqu'on interagit avec la carte
- Clic sur le bouton :
  * Si le point est centré, désactivation de l'outil
  * Si le point n'est pas centré (on a déplacé la carte), recentrage

C'est le fonctionnement qu'on a par exemple sur l'application
smartphone http://ge.ch/sitg/cartes/mobiles

**Comment by adube** [comment]
@sbrunner I created an early PR: https://github.com/camptocamp/ngeo/pull/420.  Please, review.

It features everything described in the wanted behaviours.

The only thing missing is its integration to the mobile application example.  I'll create a second PR for this.

**Comment by adube** [comment]
@sbrunner I ended up updating the gmf mobile app in the same PR.  It will be simpler for you to review everything from the same place.

**Comment by fgravin** [comment]
Juste une question sur le comportement: si on track et qu'on panne, lorsqu'on bouge ça recentre non ?
Sachant que la position d'un GPS change un peut tout le temps même à l'arrêt, cela n'interfère t-il pas avec la possibilité de panner tranquillement ?

**Comment by adube** [comment]
Indeed, it would.

Here's a suggestion: while the user is panning, (i.e. the safest way, I think, is to keep track of the "mousedown" event), we prevent any re-centering of the map due to a change of position.

Please, discuss this with your team and come back with an approval or an alternate solution.

**Comment by adube** [comment]
The PR has been merged in ngeo.  This task can be closed now.  See: https://github.com/camptocamp/ngeo/pull/420
