### ISSUE TITLE
Geolocation Desktop

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1766]
Bouton sur la carte permettant de ce géolocaliser:

sur desktop (effectué):
- click -> centre sur la position
- click -> centre à nouveau sur la position

La détection desktop mobile est un problème résolu en dehors du composant.

http://camptocamp.github.io/ngeo/master/geolocation.html

**Comment by adube** [comment]
http://camptocamp.github.io/ngeo/master/examples/geolocation.html

**Comment by adube** [comment]
#1766 est pour Desktop.  #1765 est pour Mobile.

**Question**: Il ne semble pas y avoir de différence de comportement entre les deux versions.  Est-ce que cette tâche est seulement à propos de l'intégration du bouton dans l'interface Desktop tandis que l'autre est l'intégration dans le Mobile en plus de son développement ?

**Comment by sbrunner** [comment]
Yes, I was a copy-past issue, corrected :-)

**Comment by adube** [comment]
On click, a vector feature will be added at the location and an other for the precision, just like the mobile tool.  On first interaction with the map OR if a new click is made on the tool, those features are removed.

@sbrunner , would you please validate this behaviour ?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by adube** [comment]
Excellent, thanks.

**Comment by adube** [comment]
Here's an up-to-date description of the behaviour the tool must have. It's in French and comes from @ybolognini :

**Desktop**

- Simplement un bouton "outil activé/désactivé"
- Le point reste lorsqu'on interagit avec la carte
- Il faut donc cliquer deux fois sur le bouton pour recentrer si on a
déjà l'outil activé

**Comment by adube** [comment]
@sbrunner Do you know when the `desktop` app will be available ?

**Comment by sbrunner** [comment]
in about two weeks ... in meantime you can create an independent example...

**Comment by adube** [comment]
>in about two weeks ... in meantime you can create an independent example...

Understood.

**Comment by adube** [comment]
The tool has been added in ngeo: https://github.com/camptocamp/ngeo/pull/451

The only thing remaining to do is to add it in the `desktop` app, which doesn't exist yet.
