### ISSUE TITLE
Open a window

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1768]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231768-Open-a-window

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by svavoi** [comment]
It's fine for me.

**Comment by vvmalbre** [comment]
That's fine, no further comments on this.

**Comment by gnerred** [comment]
Fine for me

**Comment by rbovard** [comment]
Okay for me.

Just a question, when the content is bigger than the height, a scrollbar appear like in 1.6?

**Comment by mriedo** [comment]
ok if 
- configuration parameters have to be the same (url, title, width, height) to open the window (title is important if the user clicks on more than one links)
- content has to be scrollable

**Comment by ybolognini** [comment]
@mriedo @rbovard 

Yes, parameters will be the same as in CGXP
Yes, content will be scrollable

**Comment by gsollberger** [comment]
ok for me.

**Comment by sbrunner** [comment]
@adube can we close this?

**Comment by adube** [comment]
Yes

**Comment by sbrunner** [comment]
Welcome back, thanks :-)
