### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1769]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231769-Disclaimer

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by svavoi** [comment]
It's fine for me.

**Comment by vvmalbre** [comment]
There should be the possibility of a modal disclaimer as well, so a user cannot do anything before closing the disclaimer.

**Comment by gnerred** [comment]
+1 @vvmalbre , like it works in 1.6 : http://map.cartoriviera.ch/theme/cadastre_solaire

**Comment by rbovard** [comment]
Those specs are for an equivalent of `cgxp.plugins.Disclaimer` http://docs.camptocamp.net/cgxp/1.6/lib/plugins/Disclaimer.html, what your talking about is `cgxp.plugins.ModalDisclaimer` http://docs.camptocamp.net/cgxp/1.6/lib/plugins/ModalDisclaimer.html

Am I right?

**Comment by mriedo** [comment]
Specs are ok for us

**Comment by ybolognini** [comment]
@vvmalbre @gnerred @rbovard 
Modal disclaimer has its own issue and specs: https://github.com/camptocamp/c2cgeoportal/issues/1770

I will ask for validation of #1770 in a short while.

**Comment by gsollberger** [comment]
ok for me.

**Comment by adube** [comment]
This task has been completed.
