### ISSUE TITLE
Modal disclamer

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1770]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231770-Modal-disclamer

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

This is very similar to non-modal disclaimer #1769 .

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by rbovard** [comment]
Is it possible to have the same optional options (title, width, height) like in https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231768-Open-a-window?

**Comment by ybolognini** [comment]
@rbovard 

Disclaimer is not the same as Open a window. Disclaimer is open when a layer is added.
Options for Disclaimer are set globally for the application (like in CGXP).

**Comment by vvmalbre** [comment]
Generally fine for us, but we have modal disclaimers with a lot of informations and long text. Will the disclaimer automatically fit its size corresponding to its content?

**Comment by ybolognini** [comment]
@vvmalbre 
Like in #1768 content will be scrollable.

**Comment by adube** [comment]
This task has been completed.
