### ISSUE TITLE
Re-architect mobileapp in ngeo

### ISSUE THREAD

**Issue by elemoine** [camptocamp/c2cgeoportal#1774]
The ngeo-based mobile application is being developed in ngeo. Currently, it is a regular example of `contribs/gmf` in ngeo. This means that it uses `ngeo.js` on camptocamp.github.io, which further means that the mobile application code cannot use `goog`. That's a problem, because that doesn't match the way we will develop GMF applications.

So we need to re-architect the mobile application in ngeo, and treat it differently from the regular examples. The mobile application code should be compiled together with OpenLayers and ngeo, and the structure of the mobile application directory should match the structure that we will use in GMF applications.

This is a possible structure:

```
contribs/gmf/apps
contribs/gmf/apps/mobile
contribs/gmf/apps/mobile/less
contribs/gmf/apps/mobile/js
contribs/gmf/apps/mobile/js/main.js
contribs/gmf/apps/mobile/js/maincontroller.js
contribs/gmf/apps/mobile/js/appmodule.js
contribs/gmf/apps/mobile/build
```

**Comment by sbrunner** [comment]
Will be fixed with https://github.com/camptocamp/ngeo/pull/385
