### ISSUE TITLE
Printing: Text elements have a different style on the map than on the printout

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1782]
When I draw a text element on the map and then print it the style of the text element is different.
Where can I find the configuration to change this style?

On the map:
![label_onthemap](https://cloud.githubusercontent.com/assets/5998978/8109493/4485353a-1057-11e5-9580-7b7ba202ee76.png)
On the printout:
![label_onprintout](https://cloud.githubusercontent.com/assets/5998978/8109494/460b4f34-1057-11e5-85a1-b3e325e4bd80.png)

See https://github.com/camptocamp/baselstadt_mapbs/issues/31

**Comment by eleu** [comment]
fixed and will be included in 1.6.7

**Comment by tsauerwein** [comment]
When https://github.com/camptocamp/c2cgeoportal/pull/1759 is merged, yes.
