### ISSUE TITLE
administration interface: sorting

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1783]
Unhappily we first tested only the *layers*-part, where it works well.

If we look at *Layer Group*, we can sort *name* properly, but *tree links order* for example can not be sorted in a correct way. A second example is *group* and *item* in *tree link order*, where sorting does not work as well.

from https://github.com/camptocamp/baselstadt_mapbs/issues/50

**Comment by ochriste** [comment]
this is a limitation of the current admin interface.
there is an offer to redo a new admin interface, where this limitation would be covered.
