### ISSUE TITLE
[Upgrade to 1.6] How to access project specific vars in Python views?

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1791]
In a custom python view, I reached some variables defined in `config.yaml.in` with `request.registry.settings['targetemail']`

What is the synthax to get them in the new `vars_xxx.yaml`? Because now I have this error `KeyError: 'targetemail'`.

Thanks

**Comment by kalbermattenm** [comment]
I think you have to explicitly define them in your make file:

https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/sitn.mk#L12-L37

**Comment by rbovard** [comment]
Thanks a lot @kalbermattenm!
