### ISSUE TITLE
Admin interface - Metadata field is not editable

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1792]
When I create a new layer, the metadata field is not editable, why ? 

![image](https://cloud.githubusercontent.com/assets/1989467/11113495/ba7d3ffa-891d-11e5-846e-7f8b3e26ebc7.png)

**Comment by sbrunner** [comment]
Issue fixed here :-)
https://github.com/camptocamp/c2cgeoportal/pull/1736

**Comment by gnerred** [comment]
Thanks. When the 1.6.7 will be available ?

**Comment by sbrunner** [comment]
I plane to have a 1.6.7.rc1 today :-)
