### ISSUE TITLE
upgrade to 1.6.7rc4 run mapcache

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1810]
Just a feedback from the upgrade at BS:

I had to run after upgrading:
```
rm apache/mapcache.xml
make -f svakom.mk apache/mapcache.xml 
```

Because the background layers could not be found anymore.

**Comment by rbovard** [comment]
Something like #1795?

**Comment by sbrunner** [comment]
If we don't know exactly what's elapsed I can't do anything...

It can be helpful to know it a command failed, with witch error, or the content of the file before remove it ...

**Comment by svakom** [comment]
Additional info:
Some weeks ago we already added this:
https://github.com/camptocamp/baselstadt_mapbs/blob/master/deploy/hooks/post-restore-code#L10-L11
Because we had the same problem when deploying on our Integration and Production-System. (As far as I remember the mapcache.xml was not recreated and still pointing on Development-host.)

**Comment by sbrunner** [comment]
Deployment is a completely different problematic...

**Comment by svakom** [comment]
>It can be helpful to know it a command failed, with witch error, or the content of the file before remove it 

I don't have the file anymore and I didn't see any command failing. I only got this from the mapbs_error.log:
```
[Mon Nov 16 18:02:08 2015] [error] 2015-11-16 18:02:08,255 INFO  [c2cgeoportal.views.entry][Dummy-1] WFS GetCapabilities for base url: http://localhost/svakom/mapserv?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetCapabilities
[Mon Nov 16 18:02:08 2015] [error] 2015-11-16 18:02:08,720 INFO  [sqlalchemy.engine.base.Engine][Dummy-1] ROLLBACK
[Mon Nov 16 18:02:10 2015] [error] [client 10.81.250.247] File does not exist: /var/www/vhosts/mapbs/htdocs/svakom, referer: http://map.geo.dev.bs.ch/svakom/wsgi
[Mon Nov 16 18:02:10 2015] [error] [client 10.81.250.247] File does not exist: /var/www/vhosts/mapbs/htdocs/svakom, referer: http://map.geo.dev.bs.ch/svakom/wsgi
...
```

**Comment by gnerred** [comment]
I have relatively the same problem with background layers, that I can reproduce. If I do a 

make -f preprod.mk clean 

and then a 

make -f preprod.mk build 

I have no more background layers in my application. I do then like proposed by @eleu : 

rm apache/mapcache.xml
make -f preprod.mk apache/mapcache.xml
make -f preprod.mk build

and my background layers are back again.

**Comment by sbrunner** [comment]
Unable to reproduce :-(

**Comment by sbrunner** [comment]
Can be closed?
