### ISSUE TITLE
cant execute alambic upgrade on pre-restore-database

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1815]
the "alembic -c alembic_static.ini upgrade head" command from post-restore-database.mako cant not be executed because the project code has not been put into place when the post-restore-database is running.

the execution order is 1) database, 2) files, 3) code

https://github.com/camptocamp/deploy/blob/master/bin/deploy#L282-L295

**Comment by ochriste** [comment]
after discussion with Fred, we could improve the deploy script to allow to set the execution order

**Comment by sbrunner** [comment]
Or we can simply move the alembic call in the post-restore (global) ?

**Comment by ochriste** [comment]
we must update the static schema before writing over the main scheme, hence we absolutely must run the alembic call in pre-restore
