### ISSUE TITLE
GeoMapFish 2.0 - Phase 1 - Mapgears

### ISSUE THREAD

**Issue by adube** [camptocamp/c2cgeoportal#1816]
Ceci est un "tracking ticket" dans lequel sont listés les tâches de la Phase 1 confiées à Mapgears pour la migration de GeoMapFish à la version 2.0.  Les voici, en ordre inverse de complexité:
- [x] #1671 - Mobile Measure
- [x] #1765 - Geolocation Mobile
  - [x] #1856 - Geolocation recentering when tracking (mobile) 
- [x] #1766 - Geolocation Desktop
- [x] #1659 - Authentication
- [x] #1654 - Background layer
- [x] #1709 - Theme Selector
- [x] #1772 - Query data
- [ ] #1657 - Permalink

**Comment by ger-benjamin** [comment]
I've not asked anybody, but I think that I can close this ticket...
