### ISSUE TITLE
[1.6] - CSS build

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1820]
I am not sure how this works...

But if I make a modification in a CSS file, does make take that automatically into account, or do I have to run `make -f my_file.mk clean` and  `make -f my_file.mk build` ?

**Comment by sbrunner** [comment]
It should work with  `make -f my_file.mk build` if it's not the case it's an issue :-)

**Comment by kalbermattenm** [comment]
Nope... Is not issue... I tested this again and it works... I do not know why I had this problem...

Closing, sorry for the noise...
