### ISSUE TITLE
https - add options to ignore certificate error on localhost

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1826]
we need to ignore certificate error (verify=False) for all request on localhost
because any request done using something like https://localhost/... will fail at the moment

**Comment by jwkaltz** [comment]
This issue is actually a problem in a current upgrade in a specific environment. I re-open and will try to do a PR.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-549
