### ISSUE TITLE
Alembic script naming

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1829]
Shouldn't the name of this file (https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/2b8ed8c1df94_set_layergroup_treeitem_is_as_a_primary_.py) be `2b8ed8c1df94_set_layergroup_treeitem_id_as_a_primary_.py` and also this line (https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/2b8ed8c1df94_set_layergroup_treeitem_is_as_a_primary_.py#L30) be: `"""Set layergroup_treeitem.id as a primary key`  (replace `is` with `id`...)

**Comment by sbrunner** [comment]
First: no for backward compatibility 

Second: fixed here: #1830

**Comment by kalbermattenm** [comment]
No worries ;-)

Thanks ;-)

**Comment by kalbermattenm** [comment]
Thanks for the PR @sbrunner
