### ISSUE TITLE
Add a desktop layout

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#1839]
* [x] Add a new layout in the build architecture (mobile copy)
 * [x] Adapt it as we want to be
 * [x] Don't duplicate code in the Makefile
 * [x] Backport the localization from the mobile layout
 * [ ] Theme selector dropdown content: thumbnails and text could be arranged differently,
 * [ ] Theme selector button: it would be better to have the text aligned left and the caret aligned right,
 * [ ] Tree: it doesn't look like how it was designed.

**Comment by pgiraud** [comment]
The job is done in ngeo. See https://github.com/camptocamp/ngeo/pull/546.

**Comment by sbrunner** [comment]
Last tasks moved to https://github.com/camptocamp/c2cgeoportal/issues/2022
