### ISSUE TITLE
Variables in template

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1845]
Little question: Where is defined the variable `lang` in https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/create/%2Bpackage%2B/templates/index.html_tmpl#L2?

Thanks

**Comment by sbrunner** [comment]
I don't know if I responds wheel, here:
https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/views/entry.py#L881

**Comment by rbovard** [comment]
Mmm ok, thanks for your answer.

Actually to goal of my question was to know how I can use project specifc vars in template files (`index.html` in my case). In `1.5`, I renamed `.html` > `.html.in` but doing the same with mako didn't work.

Do you have a suggestion to achieve this?

**Comment by sbrunner** [comment]
OK then there a documentation here:
http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/customize_ui.html?highlight=registry#advanced-configuration-examples

But it's missing that you should also add this in your project `Makefile` (`<package>.mk`):
```
CONFIG_VARS += viewer
```

**Comment by rbovard** [comment]
Thanks, that's perfect!
