### ISSUE TITLE
Geolocation recentering when tracking (mobile)

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1856]
Maybe it wasn't clear enough, but I don't think that tracking should automatically recenter map when map was panned. Complete process:

 * Geolocation disabled
 * Click on button --> enabled
 * If point centered (map wasn't panned)
   * Click on button --> disabled
   * Tracking --> move point AND recenter
 * If point not centered (map was panned)
   * Click on button --> recenter
   * Tracking --> move point AND DO NOT recenter

That's the way it works in the SITG mobile app.

**Comment by sbrunner** [comment]
To be assign to @adobe

**Comment by adube** [comment]
Understood.

**Comment by adube** [comment]
A PR is up and ready for review: https://github.com/camptocamp/ngeo/pull/471
