### ISSUE TITLE
Layout cross-device tests

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1859]
#### YBI

Ipod 5 / Safari
 * Looks like app is too high for the window. Just after loading the app, the scalebar is not visible. Then, after entering a menu and then a sub menu, it moves down, the scalebar is visible but the search field is hidden. May be linked to the browser's navigation bar

Samsung S5 / Chrome
 * While loading the page, search field and geolocation button are displayed and search field looks distorted. Not bad but would be nice if corrected
 * Open left menu, then click on grayed out map. For a short time, "Mesure tools" is displayed next to "Background"

Ipad 3 / Safari
 * Cannot see the bottom of the page. Scalebar and geolocation buttons are half-hidden. Same as Ipad / Safari?
 * When left menu is open, it is possible to drag the (disabled) map left on top of the menu

Mac / Safari
 * When opening a submenu (slide from right to left), the gray title is disappearing while moving. It becomes white and gray again

Mac / Chrome
 * Layers icon (for left menu) looks different, bolder

#### MBR

Ipod 5 / Safari
- shows the same behaviour for the left menu as described in the second point for Ipad 3 / Safari

Ipod 5 / Safari and Samsung Galaxy Tab4 /Chrome
- it is hard to activate/deactivate the geolocalisation using touch

**Comment by marionb** [comment]
Also:
Ipod 5 / Safari
- shows the same behaviour for the left menu as described in the second point for Ipad 3 / Safari

Ipod 5 / Safari and Samsung Galaxy Tab4 /Chrome
- it is hard to activate/deactivate the geolocalisation using touch
