### ISSUE TITLE
Search cross-device tests on mobile

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1860]
Samsung S5 / Chrome
 * Looks like search doesn't work at all. No results when typing. Then when clicking another button (like zoom button), the search results window is displayed (empty)

Mac+Android+Win10 / Chrome
 * A rectangle highlights the entered text in the search field. In Chrome, this rectangle is displayed over the cross button

Win10 / Edge
 * When page is loaded the first time, string "{{'search...' | translate" is displayed instead of the simple "search..." text
 * When typing a search keyword, two crosses are displayed in the search field instead of one

**Comment by tsauerwein** [comment]
> Samsung S5 / Chrome

Tested on BrowserStack with Samsung Galaxy S5 (physical device) and Chrome, and it looks fine (result list is shown, tap on a result zooms to the result feature).

**Comment by tsauerwein** [comment]
> A rectangle highlights the entered text in the search field. In Chrome, this rectangle is displayed over the cross button

@tonio is also looking into this as part of the CSS re-organization.
