### ISSUE TITLE
The default print template references an unknown TODAY() function

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/c2cgeoportal#1867]
When you create a new site, you have this file created:
`print/print-apps/+package+/A4_Portrait.jrxml`

This file contains this section:
```xml
<textField>
    <reportElement x="300" y="0" width="255" height="20"/>
    <textElement textAlignment="Right">
        <font size="8"/>
    </textElement>
    <textFieldExpression><![CDATA["Le " + new SimpleDateFormat("EEEEE dd MMMMM yyyy", new Locale("fr")).format(TODAY())]]></textFieldExpression>
</textField>
```

When trying to generate a PDF, we get an error about TODAY() not being a function and the print fails. Commenting out this section, the print succeeds.

**Comment by pvalsecc** [comment]
Stupid mistake on my side (forgot to add jasperreports-functions)

**Comment by tsauerwein** [comment]
(And don't forget the JodaTime jar which is required by jasperreports-functions!)

**Comment by pvalsecc** [comment]
Yeah, I've added all 4 of them while I was at it.
