### ISSUE TITLE
set timeout in http() calls

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1879]
by default there no timout in python's httplib2 calls (relying on the socket layer)

https://docs.python.org/2/library/socket.html#socket.getdefaulttimeout

meaning if the service called is taking very long to answer and lots of concurent requests are done, the whole connection pool can be used and appach will die with "MaxClients exceeded" errors.

solution: 

explicitly set a timeout value when instanciating http()

concerned: proxy.py
maybe others

WL 1d

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-523
