### ISSUE TITLE
FullTextSearch: TypeError: node is null if layer_name exists in layertree

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1887]
From BS:

We found a strange behaviour regarding the fulltextsearch. 
As soon as the layer_name attribute in the tsearch table corresponds to a layer name in the layertree, the search field gets an error in the debugger when you are searching for one of these elements and the close button doesn't show anymore.

Select in tsearch view:

```
...
SELECT concat(ln.verkehrsmittel, 'linie ', ln.liniennr) AS label,
               'Liniennetz öffentlicher Verkehr'::character varying AS
                 layer_name,
               NULL::integer AS role_id,
               true AS public,
               to_tsvector('german'::regconfig, concat('ln', ' ', ln.liniennr))
                 AS ts
...
```

To test it:
1. Load layergroup "Liniennetz öffentlicher Verkehr" in layertree
2. search for "ln 36" ("Liniennetz öffentlicher Verkehr" is used as group in the drop down)
3. hit ENTER
--> close button right of the search field doesn't display and in the debugger you get the message 

```
TypeError: node is null
node.expand();
```

**Comment by eleu** [comment]
We cannot find the layer "Liniennetz öffentlicher Verkehr" on http://map.geo.test.bs.ch/ nor on our ref instance (http://basel-debug.infra.internal/). Do you have a test case ?

**Comment by ybolognini** [comment]
Baselstadt issue says "solved"
