### ISSUE TITLE
jar dependency for print broken

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1889]
the result of 
wget http://mirrors.ibiblio.org/pub/mirrors/maven2/joda-time/joda-time/1.6/joda-time-1.6.jar

is an html page, not the jar itself

**Comment by ochriste** [comment]
use http://maven.ibiblio.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.jar

**Comment by tsauerwein** [comment]
See https://github.com/camptocamp/c2cgeoportal/pull/1865
