### ISSUE TITLE
rewrite rule for proj

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1891]
we are missing the following rewrite rule in wsgi.conf.mako
RewriteRule ``^${apache_entry_point}proj/(.*)$ /${instanceid}/wsgi/proj/$1 [PT]``

is it unwanted or simply an oversight ?

**Comment by sbrunner** [comment]
It's not wanted, we just add rules for URL that the user will directly use...

**Comment by ochriste** [comment]
ok, I guess it's project specific then
