### ISSUE TITLE
update tomcat print.war when deploying

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1899]
From BS:

When we deploy our application to Int / Prod the files in the folder ```/srv/tomcat/tomcat1/webapps``` are not getting refreshed. That's why some changes in the print configuration (https://github.com/camptocamp/baselstadt_mapbs/blob/master/print/print-apps/mapbs/config.yaml.in) are not taken into account.

How can we ensure that these files are also refreshed when we do a deploy?
Doing a make -f $TARGET.mk build instead of a make -f $TARGET.mk template-generate?
https://github.com/camptocamp/baselstadt_mapbs/blob/master/deploy/hooks/post-restore-code#L8

**Comment by eleu** [comment]
From BS:

I added following line to the post-restore-code file (https://github.com/camptocamp/baselstadt_mapbs/blob/master/deploy/hooks/post-restore-code#L9):
``` make -f $TARGET.mk print ```
This seems to be what I was missing.
Would it make sense to add it to the standard/demo version?

**Comment by eleu** [comment]
BL has the same wish.

**Comment by sbrunner** [comment]
Already fixed with: #1853
