### ISSUE TITLE
wsgi configfile issue with some instance name

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#190]
If you use an instance name which has an escape code letter as first letter, than Python generates an error when trying to load the application through wsgi. In the buildout\parts\modwsgi\wsgi file, Python omits to escape a backslash because this one is already considered as being an escape code (see tests hereunder with an instance beginning with letter "t" -> escape code \t). 

I don't know if this is only a Windows issue...

```python
>>> configfile = "D:\Applications\Mapfish\test_eric/production.ini"
>>> f = open(configfile, 'r')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
IOError: [Errno 22] invalid mode ('r') or filename: 'D:\\Applications\\Mapfish\test_eric/production.ini'
>>> configfile
'D:\\Applications\\Mapfish\test_eric/production.ini'
>>> configfile2 = "D:\Applications\Mapfish\sitn_intra_dev/production.ini"
>>> configfile2
'D:\\Applications\\Mapfish\\sitn_intra_dev/production.ini'
>>> f = open(configfile2, 'r')
>>> f.close()
```

**Comment by sbrunner** [comment]
We don't use modwsgi anymore
