### ISSUE TITLE
[1.6.7rc6] - Error when compiling js from scratch

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1941]
When doing a `make ... clean` followed by `make ... build` or when installing an instance from scratch, the `build` folder in the `static` folder is removed or does not exist yet.

On Windows (using Cygwin), this might trigger an error when `make`is rebuilding the compiled `app.js` file. It complains that the `build` folder is not existing.

Would it be possible to check if this `build` folder exists and if not create it before compiling/copying `app.js` to this folder ?

**Comment by sbrunner** [comment]
Does it #1943 fix your issue?

**Comment by kalbermattenm** [comment]
Maybe for the mobile (I have not try it out)... But I mainly have this issue for the "desktop" build, thus the `static\build` folder...

**Comment by sbrunner** [comment]
For the main files we already have it ...:
https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L610
it's not working?
Can I have your command log?

**Comment by kalbermattenm** [comment]
I just retried... and it work... don't ask... sorry for the noise...

**Comment by sbrunner** [comment]
:-)

**Comment by kalbermattenm** [comment]
@sbrunner, could you explain me what `mkdir -p $(dir $@)` exactly creates ??

Because, it looks like this is working in one project, but not in another... I know what the `-p`means, but I cannot figure out what `$(dir $@)` stands for ??

**Comment by sbrunner** [comment]
`$@` is the file we want to generate eg: `proj/static/build/app.js`
`$(dir <file>)` is the directory of the fileeg: `$(dir proj/static/build/app.js)`=> `proj/static/build/`

You can also add `@echo $(dir $@)` to see the current value...

**Comment by kalbermattenm** [comment]
OK, thanks ! I am going to look at it more thoroughly on the instance where I get the error...
