### ISSUE TITLE
Recenter on coordinates - Does not work anymore with WGS84

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1956]
From 1.6, it is not possible anymore to recenter map on WGS84 coordinates using the search bar. With LV03 coordinates it works. Can be tested on 

http://map.cartoriviera.ch

With 554171 146114 (OK)

And 6.84165 46.46493 (not OK)

Problem of GMF or configuration missing on my application ? Thanks

**Comment by kalbermattenm** [comment]
I think this is only due to some missing configuration... on http://sitn.ne.ch, it is still possible...

Coming back to you with some conf... I just have to search in our code ;-)

**Comment by kalbermattenm** [comment]
Check this line https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/sitn/templates/viewer.js#L813

I do not know if it is this one which you are missing...

**Comment by gnerred** [comment]
Thanks @kalbermattenm . Do you have 1.6 on sitn.ne.ch ? I checked my viewer.js, and I have the line you mention...

**Comment by gnerred** [comment]
And I also have showCenter: true, but not symbol is shown when recentering, nor on sitn.ne.ch

**Comment by kalbermattenm** [comment]
Yes... (1.6.7rc6)

**Comment by gnerred** [comment]
Has someone of C2C an idea of the problem ? 

FYI, if I enter 560670 145330 in search bar, no server request is send, only JS handels the recentering. If I enter 6.92669 46.45814, a FTS request is send, so it is not considered by the plugin to be a coordinates pair. Thanks

**Comment by ochriste** [comment]
this line return null in your project:
https://github.com/camptocamp/cgxp/blob/1.6/core/src/script/CGXP/widgets/FullTextSearch.js#L163

I will see if I can find why

**Comment by kalbermattenm** [comment]
> And I also have showCenter: true, but not symbol is shown when recentering, nor on sitn.ne.ch

@gnerred, yes... same problem on http://sitn.ne.ch

**Comment by ochriste** [comment]
projectionCodes: ... must be set in your map config, not in the fulltextsearch config

https://github.com/camptocamp/demo_geomapfish/blob/1.6/demo/templates/viewer.js#L479

**Comment by kalbermattenm** [comment]
OK... but then, why does that work on http://sitn.ne.ch ?

In this project the projectionCodes are also defined in the fulltextsearch config, and not in the map config..

**Comment by gnerred** [comment]
Thanks @ochriste , now it works !

Any idea about the other problem (showCenter) ?

**Comment by kalbermattenm** [comment]
I just tried to add projection 2056 to the fulltextsearch...

If I do not add them to: fulltextsearch -> widgetOptions -> projectionCodes, then it does not work.

And adding them to the map config (or not) does not change a thing...

There is something I do not get...

**Comment by gnerred** [comment]
Maybe those projections are added somewhere else in your code ?

**Comment by kalbermattenm** [comment]
See https://github.com/camptocamp/sitn_c2cgeoportal/pull/1114

> Maybe those projections are added somewhere else in your code ?

Hmmm... I search for them... but I can only see them over there...

**Comment by gnerred** [comment]
@kalbermattenm , I think I can close this issue, as the original problem is solved. Ok for you ?

**Comment by kalbermattenm** [comment]
Yes, close it
