### ISSUE TITLE
Layertree layers order should be the same as 1.6 demo

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1968]
The order of the layers in the layertree should be the same as in 1.6.

**Comment by sbrunner** [comment]
Note that the layer order in the 1.6 demo is not always predictable (same order value)

**Comment by ger-benjamin** [comment]
@ybolognini 
This "bug" appears only when layers don't have the same ordering number. This problem will not longer appears because now, in the administrator interface, we always set a different ordering value for each layers.
