### ISSUE TITLE
Zoom button should be deactivated as soon as click is finished

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1971]
Now buttons are grayed when user clicks on it (OK) but they stay grayed until another button is clicked. Buttons should be deactivated as soon as click is finished.

**Comment by fgravin** [comment]
What about removing

```js
ol-zoom button:focus {
  background-color: #cccccc;
}
```

Where do we want to have grey button on focus ?

**Comment by sbrunner** [comment]
Looks good for me :-)
