### ISSUE TITLE
Remove anchor in URL

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1979]
Now, when one opens a menu, an anchor is added to the URL (for instance "#background").

We could remove it as it is not used.

We could also decide that we keep this anchor, but in this case it should be used to open the menu when permalink is used. As opening the menu makes the map gray and not clickable, I would suggest to remove the anchor (a permalink pointing to a disabled map seems weird to me).

PSC validated that we can remove it.

**Comment by kalbermattenm** [comment]
OK... I did not get it at first...

I did turn that in my head in all possible way I could think about, and I do not see why we should keep "interface" information in the permalink... So... for me, we could remove it...

ping @rbovard and Ruth (email), do you think we should ask to the other members of the PSC ?

**Comment by gnerred** [comment]
I also think that this anchor should be removed

**Comment by rbovard** [comment]
For me it's not necessary to keep this anchor, you can simply remove it.

BTW there is an issue with the permalink now, if you reload the page you get a 404.

**Comment by ybolognini** [comment]
@rbovard This problem is only visible on the mobile app ngeo example:

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/

Because it ads "index.html/theme/main?lang=fr" to the URL. But this works on demo server:

https://geomapfish-demo.camptocamp.net/2.0/mobile/theme/main?lang=fr

**Comment by rbovard** [comment]
Thanks for the info
