### ISSUE TITLE
Moving content of Data menu to first panel?

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1980]
During the PSC demo, a question was raised about the position of Theme menu and layertree.

Was there a reason why we put those two features in a sub menu? Was it only to have more space for the layertree (at the time, we also had the Login in that menu)?  Is there a more technical reason?

What would be the effort to move Theme and layertree on the first panel?  Then we would have:
 * Background
 * Theme
 * Layertree
And we could find another place for logo, if needed (About menu somewhere?)

First step: estimate the effort and describe solution. Then PSC will decide.

**Comment by pgiraud** [comment]
Super easy.
See result here https://pgiraud.github.io/ngeo/mobile_left_menu_itms/examples/contribs/gmf/apps/mobile/index.html
