### ISSUE TITLE
Directly come back to layertree when selecting Theme

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1981]
What would be the effort to come back to layertree as soon as a theme is selected? Same for background layer, back as soon as layer is selected. 

Those two submenus could be seen as "mobile dropdowns".

First estimate, then PSC will decide.

**Comment by pgiraud** [comment]
For the background, it should be fairly easy. We need to know when the theme changes in the main controller (abstract controller actually) and hide the nav. I can be done in 2 hours.

For the theme selector, it's a bit trickier. We need to add some stuff in the mobile-nav directive. See https://github.com/camptocamp/ngeo/issues/594 for detailed explanations.
My estimation for this is 1 to 1.5 days.

Both are must-have in my opinion.
