### ISSUE TITLE
Add a cross to close panels?

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#1983]
PSC, see @pgiraud 's comment.

During yesterday's PSC, a question was raised about how to close menu panels. It looks like clicking on map isn't intuitive enough.

What would be the effort to add a cross (to both panels) to close the panel?

**Comment by pgiraud** [comment]
I agree that currently it difficult to know how to come back to the map. However I'm strongly against the "cross" button. It will be add a nth button to the interface and it may add confusion.
After some user testing with my colleagues, it appears that all of them tried to swipe the map back.
I'm convinced that if the "swipe-to-close" works it will be intuitive enough and no one will complain.

See https://github.com/camptocamp/ngeo/issues/549 and https://github.com/camptocamp/ngeo/pull/550

**Comment by kalbermattenm** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger

**Comment by kalbermattenm** [comment]
+1 for @pgiraud proposition. I think that we should avoid as much "cross / text / close / open" button as we can, and rely on the user's experience with his mobile device... (hoping he has any... ;-) )

**Comment by vvmalbre** [comment]
+1 for  @pgiraud as well

**Comment by rbovard** [comment]
+1 for @pgiraud too

**Comment by mriedo** [comment]
+1 for @pgiraud

**Comment by gnerred** [comment]
+1 for @pgiraud

**Comment by svarim** [comment]
I still think that an additional cross would do no harm.
