### ISSUE TITLE
Grey sub-menu title disappears while moving 

### ISSUE THREAD

**Issue by marionb** [camptocamp/c2cgeoportal#1987]
Mac / Safari (mobile layout):
When opening a sub-menu (slide from right to left), the grey title is disappearing while moving. It becomes white and grey again.

**Comment by pgiraud** [comment]
Is it for the mobile application? If yes, we probably need to add a label in github.

**Comment by sbrunner** [comment]
@tsauerwein your working on this issue?

**Comment by tsauerwein** [comment]
Yes, see the PR: https://github.com/camptocamp/ngeo/issues/643

**Comment by sbrunner** [comment]
Thanks :-)
