### ISSUE TITLE
deploy/hooks/post-restore-database.mako file doesn't exist

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/c2cgeoportal#1991]
http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/create_application.html#create-the-new-application indicates to run this command line:
```
$ chmod +x deploy/hooks/post-restore-database.mako
chmod: cannot access `deploy/hooks/post-restore-database.mako': No such file or directory
```

I don't know if the doc is not up to date or a real missing file.

**Comment by sbrunner** [comment]
Effectively, it's `pre-restore-database.mako` pullrequest welcome :-)

**Comment by yjacolin** [comment]
thanks I will do it!
