### ISSUE TITLE
Search results/Drawing elements are not printed if no corners or end points are part of the print area

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1997]
From BS:

If you have search results or customs drawing elements, it is not possible to print out only a small section of them. This is also reproducible on https://geomapfish-demo.camptocamp.net/1.6

1. search for "District de Lausanne"
2. draw a rectangle next to it
2. print out the following print area
![elementsnotshownonprint](https://cloud.githubusercontent.com/assets/5998978/12749799/3651d872-c9b3-11e5-8af6-390ea788a104.png)
--> search result and red rectangle are not shown on print

As soon as you set the print area including corner or end points of a area/line the search results and drawing elements are printed:
![elementsareprinted](https://cloud.githubusercontent.com/assets/5998978/12749920/e11d9c28-c9b3-11e5-8dee-f93be477e4b7.png)

**Comment by svavoi** [comment]
I just tested this issue with 1.6.8 but it is not working. 
Are the changes made in https://github.com/geoext/geoext/pull/121/files really part of the 1.6.8 release?

**Comment by sbrunner** [comment]
Effectively, it will be fixed with: #1099

**Comment by eleu** [comment]
@sbrunner are you sure? the mentioned PR has been merged in 2014 !

**Comment by sbrunner** [comment]
It's on CGXP, I just edit the link :-)
