### ISSUE TITLE
Upgrade to 1.6.7 step 2 

### ISSUE THREAD

**Issue by svavoi** [camptocamp/c2cgeoportal#2005]
When I try to upgrade to the new version 1.6.7 (from 1.6.7.rc6) I get an error while step 2:

```
unzip -t -q print/WEB-INF/lib/jasperreports-functions-5.6.1.jar
make: unzip: Command not found
make: *** [print/WEB-INF/lib/jasperreports-functions-5.6.1.jar] Error 127

```
Any idea what I could do?

**Comment by svavoi** [comment]
I installed unzip on our linux server `sudo apt-get install unzip` and then I could finish step 2.
Maybe it's worth to mention somewhere that unzip is needed?

**Comment by sbrunner** [comment]
Effectively I suppose that's installed everywhere ...
