### ISSUE TITLE
[Desktop] Background selector

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/c2cgeoportal#2012]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232012-%5BDesktop%5D-Background-selector

**Comment by vvmalbre** [comment]
Some feedback to the spec:
We’d prefer the “FAB Speed Dial” version instead of the proposed one. Anyway, maybe it would be possible to prepare the background selector in a way the integrator can choose which behaviour he wants to use?

**Comment by rbovard** [comment]
Seems maybe obvious but is it possible to add an optional tooltip (or text like GeoAdmin) to give user information that's for choosing background?

@vvmalbre What's the "FAB Speed Dial" version?

**Comment by vvmalbre** [comment]
@rbovard Here's an example: https://material.angularjs.org/latest/demo/fabSpeedDial

**Comment by rbovard** [comment]
@vvmalbre Thanks. Effectively, it's interesting and it reminds me what GeoAdmin did.

I also prefer this presentation, it seems more modern and "sexy". What do you think @pgiraud?

**Comment by ybolognini** [comment]
@pgiraud added the thumbnails as in mobile version.

It is always possible to implement a new look, but we think we should keep it simple like the mobile version.

**Comment by gnerred** [comment]
Ok for me. Just keep in mind that it is important for us to be able to have a huge amount of background layers in the list.

**Comment by svarim** [comment]
+1 vvmalbre with the "FAB Speed Dial" version

**Comment by ybolognini** [comment]
I do think the Speed Dial version should be seen as an enhancement. As @gnerred said, we need to have many background layers

**Comment by adube** [comment]
@ybolognini Would you please explain in details what are the tasks to be done ?
