### ISSUE TITLE
Reset of group order when removing another group

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2016]
We have quite a weird bug... In release 1.6.7, when you uncheck a group of a theme in the admin UI, the order of the last group of the theme is reset to zero...

In the image here under, a group in this theme was removed as explained (it was ordered to be about in the middle of the groups in this theme). When doing so, the order of group "Fonds de plan" was set to zero (by some kind of magical process... don't ask...). "Fonds de plan" used to be the last group of the theme (obviously...). All other groups of the theme were not altered.

We think that this is a bug...

![presse-papiers-1](https://cloud.githubusercontent.com/assets/1681332/12911266/811dcbfa-cf11-11e5-864d-e5e75d9416cb.png)

**Comment by kalbermattenm** [comment]
Ordering is really weird / buggy in 1.6.7...

Here under, see what happened when I added layer 472 (treeitem_id) to a treegroup...

On the left is the original order (before adding), on the right the order after adding a layer... Something is wrong here... The whole ordering gets mixed up...
![ordering](https://cloud.githubusercontent.com/assets/1681332/13010192/ec67ca3c-d1a0-11e5-8739-2ad0ae1b23a9.png)

**Comment by kalbermattenm** [comment]
Any news on this one ??

Another thing which would be quite helpful is to enable search on the others columns in the "order" UI menu, because, right know, you can only search for treegroup or treeitem ids...

**Comment by sbrunner** [comment]
Should be fixed ...

**Comment by sbrunner** [comment]
@kalbermattenm do you wave a dump of your database (without geodata)? I don't succeed to reproduce it on our demo...

**Comment by kalbermattenm** [comment]
@ochriste as a brand new dump of the sitn DB.

I should be in your office next week, maybe a good time to have a look on it...
