### ISSUE TITLE
Layout harmonization

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2022]
* [x] Uniformize label fonts and sizes: mainly redlining and print
 * [x] Metadata icon too small
 * [x] Too much cursor changes in layertree https://github.com/camptocamp/ngeo/issues/1134
 * [x] Theme selector dropdown content: thumbnails and text should be arranged differently
 * [x] Theme selector button: it would be better to have the text aligned left and the caret aligned right
 * [x] In measures/redlining, if the lang is 'fr', the buttons (Liste, Exporter, Supprimer) should be on the same line
 * [x] Disclaimers are over selector button and infobar on desktop: find a solution
 * [x] Infobar is too small compared to the rest of application. Uniformize font, remove altitude/coords icons
 * [x] Infobar doesn't react nicely when less space is available: find a solution
 * [x] Remove all rounded corners: infobar, search, background, and everywhere else
 * [x] Remove "name" label in redlining
 * [x] Uniformize font everywhere, go for "small"

**Comment by pgiraud** [comment]
For the position of disclaimer, here are 3 options (for desktop).

Option 1: below layertree
![localhost-3000-contribs-gmf-apps-desktop-theme-osm-lang en baselayer_ref map 3](https://cloud.githubusercontent.com/assets/319774/16084701/fee3cc26-3319-11e6-841c-1c8045d8d5d6.png)

Option 2: right side of background selector button
![localhost-3000-contribs-gmf-apps-desktop- 1](https://cloud.githubusercontent.com/assets/319774/16084718/10f9e33c-331a-11e6-9803-49fbd1f843ca.png)

Option 3: top right corner of the map (less obtrusive technically)
![localhost-3000-contribs-gmf-apps-desktop- 2](https://cloud.githubusercontent.com/assets/319774/16084740/23acbcac-331a-11e6-970e-34652a079e28.png)

@ybolognini opinion?

**Comment by vvmalbre** [comment]
Thanks. I prefer Option 3.
