### ISSUE TITLE
Search coordinates

### ISSUE THREAD

**Issue by fgravin** [camptocamp/c2cgeoportal#2044]
## Questions
Do we support degree minute coord system ? EBO: No

## Features

* [ ] On the search field we can search for coordinates
* [ ] We can search with different coordinates system (configurable)
* [ ] We use the application extent (configurable) to see if the coordinate system is valid
* [ ] The user should be able to inverse the coordinate
* [ ] Add a symbol for point
* [ ] Add a symbol for coordinate

Remarque:
With the projection system EPSG:21781, EPSG:2056, EPSG:4326 and by inversion the coordinates we never had a coverage in the Switzerland :-)

Some info on the coordinate systems (attention: don't implement these hard values. They are just for information):
* EPSG:21781 (Human readable name: LV03): Numbers range from 400'000 to 900'000 (or more) for the East-West-Axis and from 0 to 399'999 for the North-South-Axis.
* EPSG:2056 (Human readable name: LV95): Numbers range from 2000'000 to 2999'999 (or more) for the East-West-Axis and from 1000'000 to 1999'999 for the North-South-Axis.
* EPSG:4326 (Human readable name: WGS84): Numbers range from 0 to 15 for the East-West-Axis and from 30 to 50 (or more) for the North-South-Axis.

Swisstopo has done something like this, see the link in the section below.

## Layout

To be defined (with and without groups...)

## External Resources

no

## Architecture

We need a service that compute a position from the search pattern.
The search query is tested through regexp to determine if it is a degree minute or standard coordinates.
The service should take a config with a list of supported projections. For all this projections, we need to transform the search coordinate to the map projection and see if is is contained in the current extent. If not, we invert, if not we check next projection.
The order of the projections in the config set the priority of the detection.

When we find a position that is in the extent, we return it.

We could externalize  the "multi projection" recognition and conversion in another service (in `ngeo`)because it will be also used by the permalink and the API.

## Configuration

* List of coordinate system
* Style to display the coordinate
* Style to display the point
* Application extent? if we can't get it from the map

## Implementation Examples
* https://github.com/camptocamp/cgxp/blob/master/openlayers.addins/AutoProjection/lib/OpenLayers/Util/AutoProjection.js
* https://geomapfish-demo.camptocamp.net/1.6/
* https://github.com/geoadmin/mf-geoadmin3/blob/8619c8908a550cef4f59b8d0c2f1ad289fcd1169/src/components/search/SearchService.js#L7
* https://map.veloland.ch/

## Exit-criteria

The following should work in the search field:
* 46 6
* 6 46
* 600000 200000
* 200000 600000
* 2600000 1200000
* 1200000 2600000
* 46.5 6.5

**Comment by tsauerwein** [comment]
For ProVeloBern we also have a simple implementation using Typeahead for this:
https://github.com/camptocamp/provelobern_bicyclerouteplanner/blob/8bd0c7c/app/provelobern/static/js/search.js#L97-L103
https://github.com/camptocamp/provelobern_bicyclerouteplanner/blob/8bd0c7c/app/provelobern/static/js/search.js#L155-L172

**Comment by sbrunner** [comment]
Why duplicate things?

**Comment by sbrunner** [comment]
duplicated with: https://github.com/camptocamp/ngeo/issues/696
