### ISSUE TITLE
WMTS layer in layertree: Dimensions is not taken into account

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2047]
http://geomapfish-demo.camptocamp.net/1.6/s/Zbts

-> the layer ch.astra.ausnahmetransportrouten has the values set in dimensions `{"Time": "20141003"}` configured, but the layer is wrongly requested with the default dimension 20150211.

**Comment by sbrunner** [comment]
But the dimension value don't exists in the capabilities ...

**Comment by eleu** [comment]
better example layer:  http://geomapfish-demo.camptocamp.net/1.6/s/8eKh

http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr has the layer `ch.babs.kulturgueter` with two dimensions: 20160101 (default) and 20150101.

The 20160101 (default) is always used even though I specified 20150101 in the admin interface.

**Comment by sbrunner** [comment]
Fixed with https://github.com/camptocamp/cgxp/pull/1088
