### ISSUE TITLE
Central way to display user message

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2072]
Spec: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232072-User-message

**Comment by ybolognini** [comment]
Specifications are now ready for validation!

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by svavoi** [comment]
It's fine for me.

**Comment by vvmalbre** [comment]
That's fine for us as well. (But maybe it would be good if you could use this as well for the last 4 points you discarded).

**Comment by gnerred** [comment]
Ok for me

**Comment by rbovard** [comment]
Okay for me.

Just a question: how does it work when there are several messages at the same time?

**Comment by mriedo** [comment]
ok for me

**Comment by ybolognini** [comment]
@rbovard When we have several messages, they are displayed one of top of the other, the most recent below. Same as Luxembourg geoportal.

**Comment by gsollberger** [comment]
ok for me.
