### ISSUE TITLE
Version 2.0 Routing CGXP interface: change OSRM url to SSL for demo instance

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2123]
https://geomapfish-demo.camptocamp.net/2.0/wsgi/routing?lang=en

-> routing does not work because it is requesting a http page in a https page. The OSRM server also supports SSL (at least it seems so), so you could change the URL.

**Comment by fredj** [comment]
Defined in https://github.com/camptocamp/demo_geomapfish/edit/master/demo/templates/routing.js

http://ows.asitvd.ch/wmts/ should be also changed in the same file

**Comment by eleu** [comment]
same problem also for the overview map... I'll create an issue in the demo repo for the overview map.
