### ISSUE TITLE
update pyramid-ogcproxy

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2154]
Tobias merged the proxy support in pyramid-ogcproxy, so we need the following version in 1.6.x:

https://github.com/elemoine/papyrus_ogcproxy/commit/f223ae4e12acd76455f1ffeab56ed1db67fa1392

**Comment by tsauerwein** [comment]
Back then I even added some information to the docs about how to set the proxy:
https://github.com/tsauerwein/c2cgeoportal/commit/d8b524aa3b03dba700bafbf60c66ddc7a0cf00a2

This commit could be included in the PR for this issue.
