### ISSUE TITLE
Hard-coded path for apache 'graceful' action in c2ctool

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#2170]
Just here: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/c2ctool.py#L349

And that doesn't work on RedHat. Can  we use the `APACHE_GRACEFUL` variable from the makefile ?

**Comment by ochriste** [comment]
il était prévu de rendre ce paramètrages configurable, mais je n'ai jamais
eu/prit le temps de le faire
du coup hack simplement le path dans c2ctool temporairement

**Comment by ger-benjamin** [comment]
Already done.
I've opened this issue to remember that it exists.
But thanks.
