### ISSUE TITLE
Remove theme in URL?

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2178]
Having the theme in the URL like this:

`http://www.example.com/theme/xxx`

causes many problems. With the new architecture we try to have a clear separation between client and server, and this functionality links the client to a mandatory server configuration.

How much is this functionality used?  Is it conceivable to change this kind of URL to:

`http://www.example.com/?map_theme=xxx` ?

Of course we would implement something to be sure old URLs would still work with new version.

**Comment by ybolognini** [comment]
Please see first comment and comment.

ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

**Comment by kalbermattenm** [comment]
> How much is this functionality used?

It is used quite a lot at SITN...

>  Is it conceivable to change this kind of URL to

Yes (and no...), but:

> Of course we would implement something to be sure old URLs would still work with new version.

This would be mandatory for us.

And, personally, I find this `http://www.example.com/theme/xxx` really more aesthetic then what you propose... But I could live with your proposition...

**Comment by vvmalbre** [comment]
The proposition is ok for us, but it's important that old URLs will still work with the new version.

**Comment by rbovard** [comment]
> It is used quite a lot at SITN...

+1 here

> This would be mandatory for us.

+1000

> And, personally, I find this http://www.example.com/theme/xxx really more aesthetic then what you propose...

I thought that this kind of Rest URL were more "modern" than GET parameters (ie http://www.openstreetmap.org/#map=19/46.51773/6.56275). @ybolognini Is there a reason to not go this way?

**Comment by ybolognini** [comment]
@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

@sbrunner found a way to remove the technical problem behind this. We can keep the same as 1.6 with theme in URL
