### ISSUE TITLE
UI metadata are missing in themes.json - Regression in 2.1

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/c2cgeoportal#2208]
UI metadata don't seem to be retrieved in the `themes.json`.

`isExpanded` is missing

Version 2.0
![screenshot from 2016-05-09 11 30 50](https://cloud.githubusercontent.com/assets/319774/15109546/28296312-15dc-11e6-9097-8ddaa34dce35.png)

Version 2.1
![screenshot from 2016-05-09 11 49 00](https://cloud.githubusercontent.com/assets/319774/15109554/3079a130-15dc-11e6-89b3-32092a8673fd.png)

**Comment by sbrunner** [comment]
Fixed with https://github.com/camptocamp/c2cgeoportal/pull/2210
