### ISSUE TITLE
Once logged, no restricted layer appears

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2216]
The restricted layers related to logged user does not appear in layertree. 

To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/
2°/ Log with test/test
3°/ Go to theme "chantiers_planifies" -> layergroup "chantiers_planifies_acces_restreint", containing a lot of layers, does not appear

In 1.6, it works. Do the same steps with https://preprod.cartoriviera.ch/mobile/ to see the difference

**Comment by sbrunner** [comment]
We should add the role in the query string

**Comment by fredj** [comment]
Note: it works in debug mode (the role param is added in the url). it should be a renaming issue.
