### ISSUE TITLE
Problem with V2 ngeo on IE 10 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2218]
Try to open https://geomapfish-demo.camptocamp.net/2.0/mobile/ or https://preprod.cartoriviera.ch/v2/mobile/ in IE 10 : 

CSS3111: @font-face a rencontré une erreur inconnue. 
gmf-icons.eot

**Comment by sbrunner** [comment]
We don't support version before IE 11 ... And neither windows phone ...

**Comment by gnerred** [comment]
Okay... I think some administrations (like our) may have problems with that...

**Comment by gnerred** [comment]
I thought IE 10 was mandatory with Windows 7, but it's not the case, IE 11 can be installed on Windows 7. So this is not a problem anymore !
