### ISSUE TITLE
Admin value isChecked not working

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2219]
No layer is shown by default on https://preprod.cartoriviera.ch/v2/mobile/ , but several are configured to be. For example, layer "camac" has "isChecked" set to "true", but is not checked in application : 

https://preprod.cartoriviera.ch/v2/mobile/theme/amenagement_du_territoire?lang=fr&baselayer_ref=plan_ville_vevey_2000&map_x=554372&map_y=145890&map_zoom=9

**Comment by ger-benjamin** [comment]
Fixed with https://github.com/camptocamp/ngeo/pull/1326
