### ISSUE TITLE
Unused UI metatdata

### ISSUE THREAD

**Issue by fredj** [camptocamp/c2cgeoportal#2224]
`identifierAttributeField` is defined as a UI metatdata but is not used in the code.

**Comment by sbrunner** [comment]
Yes it is: https://github.com/camptocamp/ngeo/blob/4403d705508592a5a69d34c2a140283f8815f6ab/contribs/gmf/src/services/querymanager.js#L82 ...

**Comment by fredj** [comment]
ok, I only searched in c2cgeoportal
