### ISSUE TITLE
Permalink is not compatible between desktop and mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2234]
This permalink, generated on desktop GeoMapfish 2.0, cannot be opened on mobile GeoMapfish 2.0 : 

https://preprod.cartoriviera.ch/v2/s/2SX9 

[from @sbrunner] To resume, now:
* [x] the zoom is ok
* [x] the position is ok
* [x] the theme is ok
* [x] the language is ok
* [x] the background is ok
* [ ] tree_group_layers_* does not work on 2.x ...
* [x] the redirect to mobile don't works

**Comment by sbrunner** [comment]
For the zoom you should configure the application as explain here: https://camptocamp.github.io/c2cgeoportal/master/integrator/ngeo.html#controller-js-file

**Comment by ybolognini** [comment]
@gnerred Does it work with @sbrunner 's tip?

**Comment by gnerred** [comment]
No it doens't

**Comment by sbrunner** [comment]
To resume, now:
* the zoom is ok
* the position is ok
* the theme is ok
* the language is ok
* the background is ok
* tree_group_layers_* does not work on 2.x ...

**Comment by gnerred** [comment]
Not only. If I open on a mobile a permalink generated on the desktop, the permalink is not translated : 

https://preprod.cartoriviera.ch/v2/s/LL5H
->
https://preprod.cartoriviera.ch/v2/wsgi/mobile/theme/cadastre?lang=fr

Like explained in my first message

**Comment by gnerred** [comment]
Ping @rbovard for information

**Comment by sbrunner** [comment]
> Not only. If I open on a mobile a permalink generated on the desktop, the permalink is not translated

I don't understand what you want to say... As I test it's working...

**Comment by gnerred** [comment]
If I open this url https://preprod.cartoriviera.ch/v2/s/LL5H on my mobile (Galaxy S6), the url that is loaded is https://preprod.cartoriviera.ch/v2/wsgi/mobile/theme/cadastre?lang=fr, with no parameters . So I don't get the theme, location and layers that were on my desktop when I created the permalink. On your mobile it works ? I have tested on several mobiles (Android and iOS) with Browserstack, and I always get the same problem.

**Comment by sbrunner** [comment]
Effectively, I have the same issue :-(, thanks for your response :-)

**Comment by olivierSemet** [comment]
@sbrunner @ybolognini 

> tree_group_layers_* does not work on 2.x ...

- It works for 2.1
- For 2.0, this is not implemented **at all**. the permalink service is 3 times bigger (speaking about the number of lines of code) on 2.1 than on 2.0
- task to get this feature ON for 2.0 can be hard to evaluate to me.

**Comment by ybolognini** [comment]
@gnerred 
If I'm not mistaken tree_group_layers_* compatibility wasn't available in 1.6 mobile, right?  As it is quite complex to port the changes made in 2.1 to 2.0, we propose to add it to 2.1 only.
Other issues (including redirect to mobile) were fixed in 2.0.

**Comment by gnerred** [comment]
@ybolognini 
Yes you are right, as group layers do not exist in mobile 1.6. Ok with your proposal.

**Comment by sbrunner** [comment]
So closing, thanks @gnerred
