### ISSUE TITLE
Editing improvements

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2251]
From @svavoi, to be discussed with the PSC
- Display which layers are used to be snapped on and let the user select/unselect them
- Display which fields are mandatory
- Indicate which field caused a constraint error (or any kind of server error)
- Dropdowns with autocompletion
- It would be nice to be able to set attributes read-only for the right panel. For example for attributes that are calculated by a trigger. This values should be greyed out.
- Drawing of multipolygons/multipoints/multiline, could be an additional action like “cut geometry”
- Drawing of an arc or a circle
- Possibility to show area size when you draw a feature
- Possibility to draw a line or a polygon of a specific size
- Possibility to draw rectangular angles (or user defined angles)
- Possibility to set a point to a specific coordinate
- Copy attributes form another geometry
- Copy a geometry from a different (not editable) layer. Maybe they could be configured like snapping layers?
- We have editing layers that hold a lot of attributes (>10 attributes), it would be good to have a possibility to open another window with an additional form (for example an external plugin) to set the non-geometry attributes.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-526
