### ISSUE TITLE
Redlining: azimuth should be displayable and editable

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2258]
On version 1.6, azimuth measure stayed visible after measure was finished. Now with circle redlining, this isn't possible anymore.

Ideally:
 * A new checkbox in circle properties "display azimuth"
 * If azimuth isn't displayed, same behavior as now
 * If azimuth is displayed, then editing will be only possible by clicking on the line/circle intersection. Editing an azimuth should be the same as adding a new circle

**Comment by ybolognini** [comment]
See specs in https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231658-Measures-and-redlining

**Comment by ybolognini** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Please have a look at the specs and validate

**Comment by rbovard** [comment]
Okay for me, just a question:
Are the values displayed in real time like in 1.6?

**Comment by svavoi** [comment]
Looks good to me.

**Comment by gnerred** [comment]
Ok for me

**Comment by vvmalbre** [comment]
Fine for us.

**Comment by ybolognini** [comment]
@rbovard 
Yes, values are displayed in real time.
