### ISSUE TITLE
Error while make (new version 2.0.0)

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2261]
```
...
info closure-util Reading build config
info closure-util Getting Closure dependencies
ERR! closure-util Could not find base.js
CONST_Makefile:801: recipe for target '.build/mobile.js' failed
make: *** [.build/mobile.js] Error 1
```

Seen on the instance of @BenjaminZaugg and @marionb, OK on the instance of @eleu .

Might it be a permission problem?

Workaround: disable mobile in <user>.mk:
```
MOBILE ?= FALSE
```

**Comment by sbrunner** [comment]
I should be able to connect to the server to investigate it ...

**Comment by eleu** [comment]
you now shoud have access

**Comment by JanSterren** [comment]
we made a "cleanall" and after that we could build our instances again and it's wokring now. So this could be closed.

**Comment by eleu** [comment]
@JanSterren the problem is not solved, you are just using a workaround (deactivated mobile) so you can move on with the layers integration work.

**Comment by sbrunner** [comment]
Any news?

**Comment by JanSterren** [comment]
not from our site, we still use `MOBILE ?= FALSE`

**Comment by JanSterren** [comment]
Is there any way we can get the mobile version, because in the next time we want to publish one Instance.

**Comment by eleu** [comment]
@JanSterren can you remove `MOBILE ?= FALSE` and test again, since your instance has been updated to a new version in the meantime?

**Comment by JanSterren** [comment]
The installation is working now, and the mobile version is showing up aswell.

**Comment by fredj** [comment]
@eleu can we close this issue?

**Comment by eleu** [comment]
yes
