### ISSUE TITLE
Search for coordinates containing decimal values with marker

### ISSUE THREAD

**Issue by marionb** [camptocamp/c2cgeoportal#2294]
When typing `46.5 6.5` in the search field it recentre after typing `6` and a click mouse click on the search field is needed to be able to type the `.` and then again to type the `5`

This is concerning the [spec # 696](https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%23696-Search-for-coordinates-with-marker#exit-criteria) tested on the [demo](https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/desktop_alt/).

**Comment by pgiraud** [comment]
As discussed with @sbrunner, we propose that when the system is able to find coordinates in the search input, we add an item in the search results for the given coordinates. The marker and the recentering should happen only when the user clicks/touches the result item.

![page_2](https://cloud.githubusercontent.com/assets/319774/16585831/fd79de80-42c2-11e6-991f-542f829c63dc.png)

**Comment by fredj** [comment]
> As discussed with @sbrunner, we propose that when the system is able to find coordinates in the search input, we add an item in the search results for the given coordinates.

+1

FYI, that's haw it works in https://map.veloland.ch
