### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2309]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232309-Right-click

**Comment by ybolognini** [comment]
ping @rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Please have a look at the specs and validate

**Comment by gnerred** [comment]
For me it is important to be able to add additionnal links, using X and Y (or Lon and Lat) variables. It seems to me that the template proposed allows that, right ? If you confirm I validate.

**Comment by rbovard** [comment]
Don't forget the properties `rasterLayers` and the method `handleServerData()`.

**Comment by rbovard** [comment]
@gnerred 
> For me it is important to be able to add additionnal links, using X and Y (or Lon and Lat) variables. It seems to me that the template proposed allows that, right ? If you confirm I validate.

For me it's defined in:
`{coord_21781_eastern}` `{coord_21781_northern}`
`{coord_4326_eastern}` `{coord_4326_northern}`

**Comment by svavoi** [comment]
We would like to see both LV95 and LV03 Coordinates in the contextual information. Is there a way to add them in the `getContet ` function? 
Anyone else is interested to display them both or is it only us?

**Comment by sbrunner** [comment]
We have a configuration with the list of projections than it should be OK :-)

**Comment by sbrunner** [comment]
Spec / Configuration / point 2: And a coordinate list

**Comment by svavoi** [comment]
Great! If this is possible then everything is fine for me.

**Comment by gnerred** [comment]
Ok all fine for me too

**Comment by vvmalbre** [comment]
Fine for us. 
Just a question: What happens, when you click on a point without height (e.g. outside of the canton)? Do the fields just remain empty, don't they appear or is there an info that for the given point isn't any data available?

**Comment by ybolognini** [comment]
@rbovard 
The handleServerData() function was specific to the 1.X infrastructure, but we will have similar behavior in 2.1.

@vvmalbre 
We could hide the field or display a message "data not available". I personally think the second option is the best.
