### ISSUE TITLE
Get list of layers for given theme and role_id

### ISSUE THREAD

**Issue by petzlux** [camptocamp/c2cgeoportal#2323]
I am trying to build a layers list for indexing in elasticsearch. There I would need to include also if access to the layer is restricted per role_id and if the layer is public (dependant on if theme is public).

The best method I have found so far is using `themes()` [https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/entry.py#L1185] like so:

``` python
    layers = []
    roles = DBSession.query(Role).all()
    for role in roles:
        role_layers = []
        req = Request.blank('/themes?interface=desktop&version=2&role_id='
                            + str(role.id))
        req.registry = request.registry
        req.user = None
        req.remote_addr = '127.0.0.1'
        entry = Entry(req)

        themes = entry.themes()['themes']
```

Problem is, the resulting theme layer trees that I want to parse do not contain all elements. Is there a better method of getting all Layers for a given theme and role id ?

**Comment by sbrunner** [comment]
Effectively, the role_is is used only to separate cache per role :-)

This can be a good start point: 
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/theme2fts.py

**Comment by sbrunner** [comment]
This is fixed?
