### ISSUE TITLE
Translations of l10nv1tov2 - not all texts are translated 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2344]
I have run the script l10nv1tov2 to migrate my translations from V1 to V2. Different elements are not translated : 

- Text "Background", "Themes" and name of background layers from the left menu
- Different texts from the right menu

Are those translations to be made manually ?

**Comment by sbrunner** [comment]
Yes the `l10nv1tov2` script is create to don't have to redo the translation of the layer name and attributes name...
