### ISSUE TITLE
Some layers are not migrated to ngeo with themev1tov2

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2345]
Desktop application V2.0.0rc6 : https://preprod.cartoriviera.ch/v2/theme/routes_trafic
![desktop](https://cloud.githubusercontent.com/assets/1989467/16380428/519a3fa2-3c77-11e6-8743-4b709b022af7.png)

Mobile application V2.0.0rc6 : https://preprod.cartoriviera.ch/v2/mobile/theme/routes_trafic?lang=fr&baselayer_ref=plan_cadastral_201605
![mobile](https://cloud.githubusercontent.com/assets/1989467/16380439/65db8494-3c77-11e6-9fc3-18f11c58988d.png)

Layer "Dispositifs manif. actuels" is missing

**Comment by gnerred** [comment]
Any idea about this issue ?

**Comment by sbrunner** [comment]
He isn't in the WMS GetCapabilities..., You can see that in the errors: https://preprod.cartoriviera.ch/sbrunner/wsgi/themes?interface=mobile&version=2&background=background_mobile

**Comment by gnerred** [comment]
You mean in the capabilities of V2 ? This layer is in the capabilities of V1 : 

https://map.cartoriviera.ch/main/wsgi/mapserv_proxy?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities

So it seems that it hasn't been migrated correctly, not ? Here below the mapfile of V2, that contains this layer. What could be wrong ? This same mapfile works in V1

LAYER
    NAME "v_dispositifs_manif_actuels"
	GROUP "dispositifs_manif_grp"
    METADATA
      "wms_srs" 			"EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
	  "wms_name"            "v_dispositifs_manif_actuels"
      "wms_server_version"  "1.1.1"
      "wms_format"          "image/png"
   	  "gml_include_items" "all"
	  "gml_types" "auto"	
    END
    TYPE RASTER
	CONNECTION "http://www.cartoriviera.ch/qgis/qgis_mapserver.fcgi?MAP=/var/sig/qgis/dispositifs.qgs&transparent=true"
	CONNECTIONTYPE WMS    
	#OPACITY 90
	STATUS ON
  PROJECTION
      "init=epsg:21781"
  END
  EXTENT 540000 130000 580000 160000
END

LAYER
    NAME "v_dispositifs_manif_actuels_interrogation"
	GROUP "dispositifs_manif_grp"
    METADATA
      "wms_title" "v_dispositifs_manif_actuels_interrogation"
	  "wms_srs" "EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
      "gml_include_items" "no_osr,type_montage,support,nom_manif,date_debut_manif,date_fin_manif"
	  "gml_types" "auto"	
	  "gml_geometries" "the_geom"
	  "gml_the_geom_type" "point"	
	  "ows_enable_request" "*"
    END
    TEMPLATE "ttt"
    TYPE POINT
    TOLERANCE 25
    CONNECTIONTYPE POSTGIS
    PROCESSING "CLOSE_CONNECTION=DEFER"
    CONNECTION "dbname='${db}' host=${dbhost} port=${dbport} user='${dbuser}' password='${dbpassword}'"
    DATA "the_geom FROM signalisation.v_dispositifs_manif_actuels USING UNIQUE gid USING SRID=21781"    
	OPACITY 0
	STATUS ON
	CLASS
		SYMBOL "circle"
		COLOR 255 0 0
		SIZE 20
	END	
  PROJECTION
      "init=epsg:21781"
  END
  EXTENT 540000 130000 580000 160000
END

**Comment by gnerred** [comment]
And this layers exists in desktop application : 

https://preprod.cartoriviera.ch/v2/theme/routes_trafic

And not in ngeo mobile : 

https://preprod.cartoriviera.ch/v2/mobile/theme/routes_trafic

**Comment by sbrunner** [comment]
This layer is configured to be on QGIS server ...

**Comment by gnerred** [comment]
Yes this is normal. And the layer "zones_manif_grp" (Zones manif. actuelles) is configured exactly the same way and is visible in mobile ngeo (see first message of this discussion) : 


LAYER
    NAME "v_zones_manif_actuelles"
	GROUP "zones_manif_grp"
    METADATA
      "wms_srs" 			"EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
	  "wms_name"            "v_zones_manif_actuelles"
      "wms_server_version"  "1.1.1"
      "wms_format"          "image/png"
   	  "gml_include_items" "all"
	  "gml_types" "auto"	
    END
    TYPE RASTER
	CONNECTION "http://www.cartoriviera.ch/qgis/qgis_mapserver.fcgi?MAP=/var/sig/qgis/dispositifs.qgs&transparent=true"
	CONNECTIONTYPE WMS    
	#OPACITY 90
	STATUS ON
  PROJECTION
      "init=epsg:21781"
  END
  EXTENT 540000 130000 580000 160000
END

LAYER
    NAME "v_zones_manif_actuelles_interrogation"
	GROUP "zones_manif_grp"
    METADATA
      "wms_title" "v_zones_manif_actuelles_interrogation"
	  "wms_srs" "EPSG:900913 EPSG:54004 EPSG:3785 EPSG:4326 EPSG:9814 EPSG:21781"
      "gml_include_items" "lieu,destinataires,reserve_de,reserve_a,date_de_pose,type_zone,nom_manif,date_debut_manif,date_fin_manif"
	  "gml_types" "auto"	
	  "gml_geometries" "the_geom"
	  "gml_the_geom_type" "polygon"	
	  "ows_enable_request" "*"
    END
    TEMPLATE "ttt"
    TYPE POLYGON
    TOLERANCE 25
    CONNECTIONTYPE POSTGIS
    PROCESSING "CLOSE_CONNECTION=DEFER"
    CONNECTION "dbname='${db}' host=${dbhost} port=${dbport} user='${dbuser}' password='${dbpassword}'"
    DATA "the_geom FROM signalisation.v_zones_manif_actuelles USING UNIQUE gid USING SRID=21781"    
	OPACITY 0
	STATUS ON
	CLASS
		OUTLINECOLOR 255 0 0
	END	
  PROJECTION
      "init=epsg:21781"
  END
  EXTENT 540000 130000 580000 160000
END

**Comment by sbrunner** [comment]
Why do you paste mapserver layer definition and mapserver get capabilities, it it's normal that the layer is on QGIS server?

**Comment by sbrunner** [comment]
> And the layer "zones_manif_grp" (Zones manif. actuelles) is configured exactly the same way 

No he is configured to be on mapserver ...

**Comment by gnerred** [comment]
Ah ok you mean the database configuration... You're rigth thanks, the prolem is now solved.

**Comment by sbrunner** [comment]
:-)
