### ISSUE TITLE
No background layer with ngeo on mobile device

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2351]
With version 2.0.0rc6, the mobile ngeo application does not show the background layers on several mobile phones. If the ngeo application is opened on a desktop PC, it works. 

To test : http://preprod.cartoriviera.ch/v2/ -> open on a mobile (tested on several real devices and on browserstack) -> no background layers

http://preprod.cartoriviera.ch/v2/mobile/ -> open on a desktop -> OK

**Comment by sbrunner** [comment]
Have you an example of phone that don't works?
On my phone it's working ...

**Comment by gnerred** [comment]
Samsung Galaxy S6 with Android 6 (my phone)
Tested on browserstack with several Galaxy and Nexus, same problem

**Comment by pgiraud** [comment]
Note: the list in the background selector is empty.

**Comment by pgiraud** [comment]
This may not be related but in there's the following error in the console on Android (Galaxy S7).
```
mobile.js:105 Mixed Content: The page at 'https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&map_x=555222&map_y=172438&map_zoom=0' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ows.asitvd.ch/wmts?service=wmts&request=getcapabilities'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by gnerred** [comment]
Thanks @pgiraud , it was related. I removed the background layer that caused this mixed content error, and now it works. It seems that mobile phones are less happy with this type of warning than desktop PC.
