### ISSUE TITLE
Login does not work with ngeo on mobile device

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2352]
With version 2.0.0rc6, the mobile ngeo application does not show the secured layers on several mobile phones. If the ngeo application is opened on a desktop PC, it works.

To test : http://preprod.cartoriviera.ch/v2/ -> open on a mobile (tested with browserstack and real Android mobile) and connect with user/password (see with D. Gnerre if you do not remember password) -> no secured layers are shown

http://preprod.cartoriviera.ch/v2/mobile/ -> open on a desktop -> OK

**Comment by sbrunner** [comment]
Have you an example of phone that don't works?
On my phone it's working ...

**Comment by gnerred** [comment]
Sorry, cache problem, it working indeed
