### ISSUE TITLE
CORS issue with feature edit requests

### ISSUE THREAD

**Issue by adube** [camptocamp/c2cgeoportal#2368]
When trying any of the "Insert", "Update" or "Delete" requests as described in https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%231662-Editing#saving-changes from `localhost` or `github.io`, we get CORS errors:

> XMLHttpRequest cannot load https://geomapfish-demo.camptocamp.net/2.1/wsgi/layers/113. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.

This is a blocker for https://github.com/camptocamp/ngeo/pull/1459

**Comment by sbrunner** [comment]
As I see the content-type is wrong, it should be `application/json`...

**Comment by sbrunner** [comment]
This is fixed?

**Comment by adube** [comment]
Yes

**Comment by sbrunner** [comment]
Thanks :-)
