### ISSUE TITLE
Conflicts in CONST_ files (1.6 - 2.0) on a merge

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2371]
Hello

I have a lot of conflicts in the `CONST_` files when trying to rebase my `2.0` branch with my master which is in `1.6.8`.

Am I missing something or the `2.0.0` branch is not up-to-date?

Thanks in advance.

**Comment by sbrunner** [comment]
You can do
```bash
git checkout --ours <CONST_files>
```
To keep the file as they was in the destination branch (2.0)

**Comment by rbovard** [comment]
Ok but it will keep the changes you fixed in `1.6.8` like the WMTSCapabilities fix (see #2098)?

(My 2.0 was from 1.6.7)

**Comment by sbrunner** [comment]
this commit is in: `2.1.0.dev11 2.1.0.dev10 2.1.0.dev9 2.1.0.dev8 2.1.0.dev7 2.1.0.dev6 2.1.0.dev5 2.1.0.dev4 2.1.0.dev3 2.1.0.dev2 2.1.0.dev1 2.0.0rc6 2.0.0rc5 2.0.0rc4 2.0.0rc3 2.0.0rc2 2.0.0.rc1 2.0.0rc1 2.0.0.dev14 1.6.8 1.6.8rc2 1.6.8rc1`
then it should already be in your 2.0 version :-)

**Comment by rbovard** [comment]
Ok thanks a lot for the details.

Just for my information, was I doing something wrong?

**Comment by sbrunner** [comment]
No, thoes files can be modified on booth branch the it can create some conflicts

**Comment by sbrunner** [comment]
https://confluence.camptocamp.com/confluence/display/GeoSupport/CONST+Git+Merge
