### ISSUE TITLE
Not all elements are translated

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2376]
In right panel `Login` is translated but not `Measure tools`

Looking in po file, I noticed the key word `fuzzy`:

```
#: nyon/templates/mobile.html:112 nyon/templates/mobile.html:117
#, fuzzy
msgid "Measure tools"
msgstr "Mesure"

#: nyon/templates/mobile.html:113 nyon/templates/mobile.html:133
msgid "Login"
msgstr "Connexion"
```

Is it there a reason for this keyword?

**Comment by sbrunner** [comment]
Yes it's normal, You should remove the line with `fuzzy`, it will be added when the source string will changed :-)

I should add some doc about it,

**Comment by rbovard** [comment]
It's what I did ;) But I didn't know why it was there.

You're right, the doc is a bit short https://camptocamp.github.io/c2cgeoportal/2.0/integrator/internationalization.html#ngeo-and-server
