### ISSUE TITLE
Modifications in translations file

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2377]
Is it normal that after some builds the content of PO file is changed (and need to be commited)?

**Comment by sbrunner** [comment]
What kind of changes?

**Comment by rbovard** [comment]
See https://github.com/camptocamp/nyon_c2cgeoportal/pull/569/commits/ef0b31030f871b3cffc2beb077b47fabe758b0c0

I edited two values in measure controller and the translation file is changed...

**Comment by sbrunner** [comment]
The impression I have is that you import the strings from v2, commit it directly, and on an other build it will reorder everything, If yes it's normal.

**Comment by rbovard** [comment]
Yes I used the import tool, but on all changes I do the content of this file is changed...

**Comment by sbrunner** [comment]
The first time it's normal, and you should commit those changes...

**Comment by rbovard** [comment]
Yes, I did.

For instance a previous commit https://github.com/camptocamp/nyon_c2cgeoportal/pull/569/commits/808cd1bd15b556732571cf16db53a0453a0171ff

Then I edited the measure controller and the file was changed __again__ https://github.com/camptocamp/nyon_c2cgeoportal/pull/569/commits/ef0b31030f871b3cffc2beb077b47fabe758b0c0

**Comment by sbrunner** [comment]
Effectively it's a bord effect of the argument `--sort-output`, I will remove it...

**Comment by rbovard** [comment]
@sbrunner Is it really fixed? Because I have a lot of edits in the translations without editing them:
* https://github.com/camptocamp/nyon_c2cgeoportal/pull/569/commits/2ee777f917fd8aa770f5e349275c33a328896f83
* https://github.com/camptocamp/nyon_c2cgeoportal/pull/569/commits/c4fb3308672bfe3489d10bdb30071c7839f7e6ab

**Comment by sbrunner** [comment]
For me yes, on your tow commit the first one looks suspect, the second one looks good :-)

**Comment by sbrunner** [comment]
I'm based on what's I see on the demo, if you continue to have strange diff, reopen it :-)
