### ISSUE TITLE
Adminstrating layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2378]
According to https://camptocamp.github.io/c2cgeoportal/2.0/administrator/administrate.html#layers

> In the version 2 we split the layer table in 3 tables: ‘layer_internal_wms’, ‘layer_external_wms’, ‘layer_wmts’, and we copy the previous layer table in ‘layerv1’.

Is it really the case for desktop layers? Or do we need to maintain the two versions?

**Comment by sbrunner** [comment]
You should maintain the two version...

**Comment by rbovard** [comment]
Ok, it's what I thougt.

Thanks to update the docs in this way :)
