### ISSUE TITLE
A lot of errors when the DB is bounced

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/c2cgeoportal#2382]
If you stop and restart the DB and you have configured apache to have 5 processes, the first five client queries will have error 500.

Maybe we want to add something like that:
http://docs.sqlalchemy.org/en/rel_0_9/core/pooling.html?highlight=reconnect#disconnect-handling-pessimistic

What do you guys think?

**Comment by tsauerwein** [comment]
I've set this up for c2corg. I think it is a good idea to do this fast additional query to avoid that users are seeing unnecessary errors.

**Comment by sbrunner** [comment]
+1
