### ISSUE TITLE
Backgroundlayer querying in ngeo ? 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2383]
How to query a backgroundlayer in ngeo mobile 2.0 ? 

https://github.com/camptocamp/cartoriviera_geomapfish/issues/11

**Comment by gnerred** [comment]
I found this, what does it mean exactly ? I don't undestand... 

"To make the WMTS queryable you should add those Metadata: ogcServer with the name of the used OGC server, layers or queryLayers with the layers to query (groups not supported)."

**Comment by sbrunner** [comment]
As it explained you should ass two UI metadata ...
I don't understand what you don't understand ...

**Comment by gnerred** [comment]
Okay, now I see what you mean... What is the name of the OGC server ? An URL ? Could you please provide an example ? Where do we have to enter those metadata in admin interface, in "Couches" or "Couches WMTS" ?

**Comment by sbrunner** [comment]
The name defined int the admin interface for the object "OGC Server" or in french "Serveur OGC" :-)

**Comment by gnerred** [comment]
Yes, but my question was : what data do I have to enter in the OGC server field (http://...)? And in which topic is it ? "Layer" ou "WMTS Layer"

**Comment by sbrunner** [comment]
neither, "OGC Server"

**Comment by sbrunner** [comment]
the url is in the "OGC Server", where you put a name
and the name will be in the "OGC server" UI metadata of the WMTS Layer.

**Comment by sbrunner** [comment]
@gnerred is it working now?

**Comment by gnerred** [comment]
I will try it later today, not have had the time until now...

**Comment by gnerred** [comment]
@sbrunner it doesn't work... Do I something wrong ? See images attached 

![image](https://cloud.githubusercontent.com/assets/1989467/16913772/3c872acc-4ced-11e6-939b-38bf81ad96a1.png)

![image](https://cloud.githubusercontent.com/assets/1989467/16913793/59cb0cca-4ced-11e6-8332-354e477282f5.png)

**Comment by gnerred** [comment]
to test 
https://preprod.cartoriviera.ch/v2/mobile/ and use "Plan cadastral" as background layer

**Comment by sbrunner** [comment]
The layer `plan_cadastral_201607` is a LayerV1 ... it should be a WMTS Layer...

**Comment by gnerred** [comment]
It is a WMTS layer too 
![image](https://cloud.githubusercontent.com/assets/1989467/16977775/69381394-4e58-11e6-9b0b-74991808abb1.png)

**Comment by sbrunner** [comment]
You have booth with the same name and you linked the metadata to the wrong one...

**Comment by sbrunner** [comment]
In the metadata editing we should prefix the item with the type ...

**Comment by gnerred** [comment]
How ? Which type ? The item is a dropdown list

**Comment by gnerred** [comment]
Okay now I undestand, I will try....

**Comment by gnerred** [comment]
I've prefixed the name and pointed the metadata to the right one. I've modified the layergroup "background_mobile". But now I have no more the plan_cadastral in my background layers... 
https://preprod.cartoriviera.ch/v2/mobile/ 
![image](https://cloud.githubusercontent.com/assets/1989467/16981238/f5a09d36-4e69-11e6-8f49-209b4cb542be.png)

**Comment by sbrunner** [comment]
It's not the first one on your screenshot?

**Comment by sbrunner** [comment]
Yes but it's no more on the application :-(

**Comment by sbrunner** [comment]
I should have a look ...

**Comment by gnerred** [comment]
:O)

**Comment by gnerred** [comment]
if the attribute "name" of the WMTS layer is not the same as the layername in the wmts capabilities, ngeo does not show the background layer, even if the attribute "layer" of the WMTS layer is set correctly.

**Comment by ybolognini** [comment]
@gnerred 
This can be considered as a bug in 2.0, it shouldn't take the "name" of layer as the WMTS layer. This was already corrected in 2.1 and it would take some time to correct in 2.0. Tests/bugfixes on 2.1 should start in August and will go much faster than 2.0 tests (not in parallel with big development), can you wait for 2.1?

**Comment by gnerred** [comment]
No I would like to go in production with 2.0 (desktop CGXP and mobile NGEO). I think other users have the same strategy, as discussed last meeting. Waiting 2.1 will delay greatly the migration to 2...

**Comment by ybolognini** [comment]
Choosing 2.1 doesn't mean migrating your desktop to Ngeo. CGXP desktop will live in parallel of Ngeo desktop. For EPFL project for instance, we have c2cgeoportal server, Ngeo mobile and CGXP desktop (all in master versions).

**Comment by gnerred** [comment]
So when is planed a release of 2.1 ? Or RC ?

**Comment by ybolognini** [comment]
Beta release for Monday's User Group meeting. Then we'll focus on bugfixing. Goal for RC1 is week 38

**Comment by sbrunner** [comment]
Can we close it?

**Comment by gnerred** [comment]
Sorry, but I have not tested yet if the background querying works (lot of problems with installation of 2.1...). I will test soon and give you a feedback.

**Comment by sbrunner** [comment]
Reopened :-)

**Comment by gnerred** [comment]
@sbrunner , I tried to configure WMTS layer querying on https://preprod.cartoriviera.ch/v2/mobile/, but it doesn't work... What did I wrong ? 
![image](https://cloud.githubusercontent.com/assets/1989467/19681605/4fd7439a-9aaa-11e6-92ad-de51d9a3bbf6.png)

**Comment by sbrunner** [comment]
The ogcServer is wrong, it should be "source for image/png" or "source for image/jpeg".

By the way the OGCServers named "source for https://preprod.cartoriviera.ch/tiles/1.0.0/WMTSCapabilities_preprod.xml image/png" and "source for https://ows.asitvd.ch/wmts?service=wmts&request=getcapabilities image/png" should be removed...

**Comment by gnerred** [comment]
Ok thanks, I set "source for image/jpeg", but it still doesn't work. 
https://preprod.cartoriviera.ch/v2/mobile/

**Comment by sbrunner** [comment]
This should be fixed in the next rc :-)

**Comment by gnerred** [comment]
When is planed the next RC ?

**Comment by sbrunner** [comment]
In about 10 days :-)
