### ISSUE TITLE
Permalink does not work anymore on ngeo mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2385]
1°/ Go to https://preprod.cartoriviera.ch/v2/mobile/
2°/ Activate some layers -> the permlalink (browser URL) is not updated

**Comment by marionb** [comment]
The permalink in browser URL is changing for version 2.1 when modifying (activatin/deactivatin) the initial state of a layer in a layer group. In general I think the this commit https://github.com/camptocamp/ngeo/commit/9510f57b86088d10690b479b766cb3808f5e8df3 in version 2.1 that fixes this.
(Tested on the demo: https://geomapfish-demo.camptocamp.net/2.1/mobile)

**Comment by sbrunner** [comment]
We speak about the version 2.0 ...

**Comment by sbrunner** [comment]
It had work before this commit ...

**Comment by gnerred** [comment]
+1 @sbrunner
