### ISSUE TITLE
Raster service in ngeo

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2406]
Where is raster service in ngeo ? The c2cgeoportal 2.0 documentation seems to still contain Sencha touch documentation : 

https://camptocamp.github.io/c2cgeoportal/2.0/integrator/mobile.html

In 1.6 : 

![image](https://cloud.githubusercontent.com/assets/1989467/16797684/e815ffa2-48e8-11e6-834f-2834f5e83144.png)

**Comment by ybolognini** [comment]
@gnerred 
Raster results are visible in measures results (point). During some PSC meeting (I could find it in my notes) we said that this information was more "measures" than "query".
Of course you're right about documentation. It should be updated.

**Comment by gnerred** [comment]
Ok that's fine. Could you please provide something to help in the configuration ?

**Comment by sbrunner** [comment]
Can it be closed on 2.1?

**Comment by gnerred** [comment]
Il found the doc. I will confirm once tester.

**Comment by gnerred** [comment]
Sorry, I thought I found the doc, but it was not the good one... Where is the doc to configure a raster service on ngeo mobile ? Thanks

**Comment by sbrunner** [comment]
Some documentation about the template should be added in this file: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/src/directives/contextualdata.js

**Comment by gnerred** [comment]
Thanks, I wait for a doc. At this time, my ngeo mobile app returns something, but I don't know which data is queried and where to configure UI : 
![image](https://cloud.githubusercontent.com/assets/1989467/19648761/82ffa8a4-9a03-11e6-892b-446e92753b64.png)
