### ISSUE TITLE
WMTS queries requires a MXSCALEDENOM in the queried layer

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#2459]
To reproduce the issue, create a WMTS layer (wmts_layer) with a bound layer to query (layer_q).
 
This layer (layer_q) must have a MAXSCALEDENOM attibut in the LAYER. Else, the layer will be not queriable. In the Themes.json object (received by the client), the wmts layer definition will not have any value in the "query_layers" field.

MINSCALEDENOM seems not require.

Found in GMF 1.5.3 but seems always in the newer version.

**Comment by sbrunner** [comment]
On WMTS?
