### ISSUE TITLE
QGIS Layers in GeoMapFish 2.0 mobile not working

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2462]
When one integrates a QGIS layer in GMF 2.0 (and probably also GMF 2.1), the /themes request shows a `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1053: ordinal not in range(128)` error for a _wms_getcap_cached URL get:

![image](https://cloud.githubusercontent.com/assets/1632411/17848184/52030620-6852-11e6-986d-879399e1a798.png)

with the end of the message:
![image](https://cloud.githubusercontent.com/assets/1632411/17848197/667b3802-6852-11e6-8717-472bc2fe749c.png)

Probably because of a encoding problem because there is a <City> tag with an Umlaut in the GetCapabilites ([example](http://78.155.22.98:81/eleu/qgisserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities))

Probably reproducible with a QGIS layer in GMF Demo.

**Comment by ger-benjamin** [comment]
Can we have an url to see the reponse (your images) / configuration by ourselves ?

**Comment by eleu** [comment]
The example is only showing the GetCapabilities. I have now checked the "public" checkbox in the test-Theme in my instance, which makes the error visible on firebox / dev tools for the example instance on (the protected server of) http://78.155.22.98:81/eleu/mobile

**Comment by ger-benjamin** [comment]
I don't currently know why the execution pass there:

https://github.com/camptocamp/c2cgeoportal/blob/0489db8ee3db1a14dfe951444552510de513f0df/c2cgeoportal/views/entry.py#L160-L161

But it seems that this line cause the error: `resp.get("content-type")` If I remove it that works (this is currently used to indicate the source of an error, but cause itself an error...)

I search further...

**Comment by ger-benjamin** [comment]
@eleu  If you can configure the response of the server as `application/vnd.ogc.wms_xml` and not `text/xml`, the problem will be resolve (except a poor error message).

@sbrunner If message can be in text (`text/xml`), content should be `content.decode('utf-8')` (always in the error string substitution, line 161, in the entry.py (see my previous link)). I leave you do that. I don't know enough the code to know if some more adaptation must be done.

Probably you'll do both to resolve this issue.

**Comment by ger-benjamin** [comment]
(Oh and yes, that in the 2.1 too)

**Comment by eleu** [comment]
btw, the [mapserv_proxy](http://78.155.22.98:81/eleu/wsgi/mapserv_proxy?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities) is also returning `text/xml`

**Comment by eleu** [comment]
I tried Apache ForceType in apache/qgisserver.conf, but it does not help... http://httpd.apache.org/docs/2.2/mod/core.html#forcetype

**Comment by eleu** [comment]
In apache/qgisserver.conf.mako, set the following in the <Location> tag:

```
Header set Content-Type "application/vnd.ogc.wms_xml"
```

I will test now further...

**Comment by eleu** [comment]
This fixes (at least temporary) the bug.

Thanks for the help @ger-benjamin and @fredj

**Comment by ger-benjamin** [comment]
Nice catch. That's what is expected by the entry.py code.
But please, don't close the issue, I think we need at least a better error message...
