### ISSUE TITLE
wget closure-linter, error 404

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#2472]
c2c geoportal version 2.0 point on `http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz` but that seems no more available...

See: Makefile: https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L155

**Comment by gberaudo** [comment]
@sbrunner, do we still have a use of the closure linter?

**Comment by sbrunner** [comment]
no...

**Comment by sbrunner** [comment]
Not on 2.1 but on 2.0 yes...
