### ISSUE TITLE
WMSBrowser does not work when a file named  sogis_orthofoto.wms is returned

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2475]
Reproducible on https://geomapfish-demo.camptocamp.net/1.6/

-> add WMS -> insert the URL http://geoweb.so.ch/wms/sogis_orthofoto.wms

I suspect the file name to be the reason for the problem, as similar WMS services like wms.geo.admin.ch are working.

**Comment by sbrunner** [comment]
Réponse du serveur:
Cookies im Browser deaktiviert
Ihr Browser akzeptiert keine Cookies. Um die Webseite zu nutzen, aktivieren Sie bitte die Option Cookies in den Browsereinstellungen.

**Comment by sbrunner** [comment]
Should be fixed with: https://github.com/elemoine/papyrus_ogcproxy/pull/6

**Comment by eleu** [comment]
how can I use this fix in a c2cgeoportal project?

**Comment by sbrunner** [comment]
The fix is available in this package and version: https://pypi.python.org/pypi/papyrus_ogcproxy/0.2

This can be change in the versions file (`versions.cfg` or `CONST_versions.txt`).
