### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by COLABORATI** [camptocamp/c2cgeoportal#2477]
The URL to the demos which are referenced [here](https://camptocamp.github.io/c2cgeoportal/2.0/index.html) are broken. 
Please handle your demo sites like real customer sites, broken demos gives a very bad impression of your project.

**Comment by ochriste** [comment]
thank for reporting the problem, we will fix it asap.
in the meantime you can see the demo there https://geomapfish-demo.camptocamp.net/2.0/
( https://geomapfish-demo.camptocamp.net/2.0/?grid )

**Comment by fredj** [comment]
https://github.com/camptocamp/c2cgeoportal/commits/master/doc/index.rst.mako

**Comment by ponceta** [comment]
I would add a link to http://geomapfish.org/ to the banner since http://geomapfish.org/ is referencing the github repo (cross referencing).
@kalbermattenm is it possible to update the demo version on http://geomapfish.org/?

**Comment by kalbermattenm** [comment]
https://github.com/geomapfish/geomapfish.github.io
