### ISSUE TITLE
Upgrade from 1.6.8 to 2.1.0.dev14 no folder /tmp/<projectname> exists

### ISSUE THREAD

**Issue by svavoi** [camptocamp/c2cgeoportal#2481]
I just run the following steps to upgrade to 2.1.0dev14 from 1.6.8 and everything seemed ok:

```
make -f svavoi.mk update
make -f svavoi.mk build
export VERSION=2.1.0.dev14
make -f svavoi.mk upgrade_v2
```

But now I cannot follow the first step in the changelog.diff for Version 2.0.0  because the folder /tmp/<projectname> doesn't exists:

> +1. Get the new and heavily modified files for ngeo integration:
> +
> -    at that point, the following folder should exist: /tmp/mapbs/
>   +
> -    cp /tmp/mapbs/.jshintrc .
> -    cp /tmp/mapbs/lingua-client.cfg .
> -    cp /tmp/mapbs/lingua-server.cfg .
> -    cp /tmp/mapbs/apache/wsgi.conf.mako apache/
> -    cp -r /tmp/mapbs/mapbs/static-ngeo mapbs/
> -    cp /tmp/mapbs/mapbs/templates/mobile.html mapbs/templates/

Where can I find this folder? Or are these steps not necessary anymore to upgrade to 2.1?

**Comment by sbrunner** [comment]
This is because the folder `/tmp/<project>` is moved to `CONST_ create_template` between 2.0 and 2.1.

**Comment by svavoi** [comment]
Thank you!
