### ISSUE TITLE
missing db table referenced in main.layer.geo_table break build

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2501]
if a database table, referenced in the "geo_table" attribute of the "main.layer" table, does not exist, the build break with error: 
No such table '<geo_table>' for layer '<layer_name>'.
make: *** [epfl_authgeoportail/locale/epfl_authgeoportail-client.pot] Error 1

 (<...> values have been replaced here)

**Comment by sbrunner** [comment]
You don't have this catch?
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/lib/lingua_extractor.py#L185-L186

**Comment by ochriste** [comment]
quite likely caused by the older c2cgeoportal version used (2.1.0.dev13), before the recent update, as I cant seem to be able to reproduce it anymore.

**Comment by sbrunner** [comment]
Thanks :-)
