### ISSUE TITLE
Add a background layer with query

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2552]

**Comment by sbrunner** [comment]
Done

**Comment by ochriste** [comment]
done where ?

**Comment by sbrunner** [comment]
On test server

**Comment by ochriste** [comment]
so in the db of the demo project on the test server ?
is there some doc how to do it / what to write in the interface admin to do that?

**Comment by sbrunner** [comment]
Here...: https://github.com/camptocamp/ngeo/blob/master/contribs/gmf/externs/gmf-themes.js :-/
