### ISSUE TITLE
Missing requirement closure_linter

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2564]
There is 404 error when running `make upgrade` (for closure_linter)

```
make -f instance_v2.mk upgrade
.build/venv/bin/pip install -r CONST_dev-requirements.txt 'tilecloud-chain>=1.0.0dev' 'c2c.cssmin>=0.7dev6' http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
Collecting http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
  HTTP error 404 while getting http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
  Could not install requirement http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz because of error 404 Client Error: Not Found for url: http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
Could not install requirement http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz because of HTTP error 404 Client Error: Not Found for url: http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz for URL http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
```

**Comment by kalbermattenm** [comment]
Yeah... I add this one too...

It is because of that line: https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L158-L160

I just removed the whole block and reran `make`...

Whatever you modify in CONST_makefile while be overwritten afterwards.... thus it does not really matter ;-)

**Comment by kalbermattenm** [comment]
> Whatever you modify in CONST_Makefile while be overwritten afterwards.... thus it does not really matter ;-)

By the upgrade process....

**Comment by rbovard** [comment]
Thanks for the tip @kalbermattenm!

**Comment by sbrunner** [comment]
Can we close it?

**Comment by rbovard** [comment]
Depending of the cause of this issue...

It's now fixed for @kalbermattenm and I, but someone else could also encounter this one no?

**Comment by kalbermattenm** [comment]
This only happens if you migrate from version 2.0 to 2.1....

**Comment by rbovard** [comment]
2.0 is a mandatory step to 2.1!

**Comment by sbrunner** [comment]
not exactly it's because you migrate from a 2.0rc, it you use the 2.0.0 yon don't have the issue :-)

**Comment by rbovard** [comment]
Ok, now I got it!

(so I won't migrate to 2.1rc to avoid those kind of issues with the 2.1.0...)
