### ISSUE TITLE
Desktop cgxp interface route issue with 2.1.0RC1

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2571]
Here the error, a route issue : 

https://preprod.cartoriviera.ch/v2/

**Comment by sbrunner** [comment]
in the file cartoriviera/templates/desktop.html
this
```
<script type="text/javascript" src="${request.route_url('viewer', _query=extra_params)}"></script>
```
should be replaced by:
```
<script type="text/javascript" src="${request.route_url('desktop', _query=extra_params)}"></script>
```

**Comment by gnerred** [comment]
Ok thanks, now I have a token problem

https://preprod.cartoriviera.ch/v2/

**Comment by sbrunner** [comment]
:-)

**Comment by sbrunner** [comment]
I miss the `.js` in may comment (I just edit it :-) )

**Comment by gnerred** [comment]
Ok, now it is an error 500 :O(

**Comment by sbrunner** [comment]
If you need the ogcproxy you should add "papyrus_ogcproxy" in the dependencies in your "setup.py" file, if not you should remove it in the desktop.js file.

[to be documented]

**Comment by gnerred** [comment]
Where do I add it in setup.py ?

**Comment by sbrunner** [comment]
In the `install_requires` (about line 20)

**Comment by gnerred** [comment]
Done, rebuiled, but still error 500  https://preprod.cartoriviera.ch/v2/

But still this error too during the build : 
Unable to DescribeFeatureType from URL /qgis/qgis_mapserver.fcgi?map=/var/sig/qgis/distribution.qgs&transparent=true&VERSION=1.1.0&REQUEST=DescribeFeatureType&SERVICE=WFS
No such table '' for layer 'separateurs_hydro'.
CONST_Makefile:686: recipe for target 'cartoriviera/locale/cartoriviera-client.pot' failed
make: *** [cartoriviera/locale/cartoriviera-client.pot] Error 1

**Comment by gnerred** [comment]
Still error 500, even after a rebuild without error

**Comment by sbrunner** [comment]
In the OGC server table you have two entry for QGIS server, and one have an invalid URL...

**Comment by gnerred** [comment]
Ok, I corrected, there are no more invalid URLs in OGC server table (if I understood well the problem), but still an error 500
https://preprod.cartoriviera.ch/v2/

**Comment by sbrunner** [comment]
OK, I miss to say that you should set ogcproxy_enable to true in your vars_cartoriviera.yaml file :-)

**Comment by gnerred** [comment]
Ok I did it like below, but still error 500 : https://preprod.cartoriviera.ch/v2/
............
vars:

    # ogcproxy
    ogcproxy_enable: true

    # Database name
    db: cartoriviera_preprod
............

**Comment by sbrunner** [comment]
And an other miss is to add `CONFIG_VARS += ogcproxy_enable` in your project make file `cartoriviera.mk`.

**Comment by gnerred** [comment]
https://preprod.cartoriviera.ch/v2/wsgi/_debug/view/1476079310

**Comment by sbrunner** [comment]
This time it's an other error :-)

I remove this line 
```
        externalWFSTypes: ${externalWFSTypes | n},
```
in the desktop.js file and now it's working

[Should be added in the changelog]

**Comment by gnerred** [comment]
Ok thanks, my desktop CGXP is now working on GMF 2.1 :O)
