### ISSUE TITLE
Connexion does not work in 2.1.0RC1

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2572]
When I log in ngeo mobile interface, no secured layers are show, as if I was not connected. If I try to log off, I get the error "Impossible de se déconnecter" in UI

https://preprod.cartoriviera.ch/v2/mobile/

When I log in with admin account, I get this... 

![image](https://cloud.githubusercontent.com/assets/1989467/19181009/6f71bd28-8c6a-11e6-8c36-8ee8690918ad.png)

**Comment by sbrunner** [comment]
Should be tested after #2571 is solved :-)

**Comment by sbrunner** [comment]
In the `cartoriviera.mk` file you should set `VISIBLE_WEB_HOST` to `preprod.cartoriviera.ch` :-)

[to be documented]

**Comment by gnerred** [comment]
Okay, now connection works... Should I close this issue or do you want to keep it for documentation ?

**Comment by sbrunner** [comment]
We keep it for documentation :-)
