### ISSUE TITLE
Background layers lost in 2.1.0RC1 in mobile ngeo

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2573]
Before migration from 2.0 to 2.1, background layers were OK in ngeo mobile. Now they disappeared... 

https://preprod.cartoriviera.ch/v2/mobile/

**Comment by fredj** [comment]
There's an error in the console:
```
The themes contain some errors:
The Layer 'tp_arret_train' cannot be directly in the theme 'default_mobile' (0/1).
Unable to find the Group named: background, Available Groups: recensement_architectural, background_mobile, signalisation, codes_immeubles_grp, train, bus_nouveau, cadastre_solaire_thermique_eau_chaude, tourisme, police_statistiques, couverture_du_sol, llavaux, chantiers_planifies_publics, cadastre_solaire_thermique_chauffage, bus, cadastre_solaire_pv, sites_pollues, reseaux, enquetes_stationnement, oeuvres_art, test2, ttt, photographies_aeriennes, orthophotos, pc_abris, eau_potable, lidar_2012, installations_sportives, infrastructures, sondages, cff, lidar_2001_relief, conduites, antennes_telephonie_mobile, autres_tubes_communaux, incendie_secours, vannes, mobilite, inspectorat_des_chantiers, cablecom, cadastre, zones_tampon_bti, perturbations_trafic, infrastructures_plans, radars, statistiques_dernier_mois_vols, telereseau, interventions, police_radars, telecom_swisscom, teledis_blonay, cartes_indicatives_dangers, cartes_dangers, dispositifs_manifestations, test, signalisation_stationnement, protection_civile, vmcv, conduites_zones_pression, amenagement_du_territoire, mobilite_douce, lidar_2001, assainissement, voirie_dechets, abonnements, enquetes_bti, tourisme_vie_locale, publicite, cartes_dangers_ttp, photos_historiques_vevey_grp, cadastre_valais, plans_ville_historiques_montreux, pc_alarmes_a_la_population, arbres_group, fuites, electricite, trafic_journalier_moyen_par_an, trafic_journalier_moyen_total, plans_ville_historiques_saint_legier, sige_enquetes, routes_cantonales, plans_ville_historiques_la_tour, problemes_sur_dp, jazz, police_interventions, stationnement_bateaux_grp, statistiques_dernier_mois, vie_locale, chantiers_planifies_par_annee, chantiers_planifies_par_etat, plans_ville_historiques_vevey, chantiers_planifies_restreints, chauffage_a_distance, affectations_plans_speciaux, cartes_phenomenes_glissements, hydrantes, chantiers_planifies_par_type_travaux, incivilites, rn, lidar_2012_hauteurs, lidar_2012_ombres, lidar_2012_relief, eau_potable_sige, gaz, assainissement_plans
The Layer 'tp_arret_bus' cannot be directly in the theme 'default_mobile' (0/1).
The Layer 'tp_ligne_train' cannot be directly in the theme 'default_mobile' (0/1).
The Layer 'tp_ligne_bus' cannot be directly in the theme 'default_mobile' (0/1).
```

**Comment by gnerred** [comment]
These layers are defined like that in 1.6. Does it mean that 2.1 does not support that anymore ? An idea of a workaround ? We cannot apply manual changes in content of schema main of 2.1, because they will be overrided when final migration will be done.

**Comment by sbrunner** [comment]
No, you should have an intermediate group :-)

And for the initial issue You should have a group names background :-)

**Comment by gnerred** [comment]
Ok I have now intermediate groups and a group named "background". But I still have no background layer in mobile ngeo... : https://preprod.cartoriviera.ch/v2/mobile/ 

Several errors can be seen in console : 
mobile.js:129 TypeError: Cannot read property 'children' of null
mobile.js:129 TypeError: Cannot read property 'TileMatrixSetLink' of null
mobile.js:129 TypeError: Cannot read property 'url' of undefined

**Comment by gnerred** [comment]
Here the debug : https://preprod.cartoriviera.ch/v2/wsgi/_debug/view/1476079310

**Comment by ger-benjamin** [comment]
These errors come from the following backgrounds layer:

 - plan_cadastrale_201607
 - plan_ville_201607
 - ortho_2013_2

(Deactive them and you will be able to choose and see working backgrounds)

I suspect that they should use another ogcServer that the default one. Because the TileMatrixSetLink come from a not found capabilities for this specific layer name (and so, a wrong capabilities url come from a miss specified ogcServer)

Can you verify ?

**Comment by gnerred** [comment]
Yes you are right. I have now replaced layers 201607 by 201610, which exist, and removed layer ortho_2013_2. But I still have errors on background layers... https://preprod.cartoriviera.ch/v2/mobile/

**Comment by ger-benjamin** [comment]
The last error come from the WMTS layer "plan_ville_201607" Perhaps that's the same problem as above (201607 -> 201610 ?)

**Comment by gnerred** [comment]
Sorry my fault, I did not rename properly the layers. Now it works ! But there still remains a js error at loading :
mobile.js:129 TypeError: Cannot read property 'children' of null

**Comment by gnerred** [comment]
No, forget my last message ...

**Comment by gnerred** [comment]
I cleaned the layers, but the js error remains : 
mobile.js:129 TypeError: Cannot read property 'children' of null

**Comment by ger-benjamin** [comment]
That come from the permalink. Perhaps it's a bug of ngeo.
I should to test that...

**Comment by ger-benjamin** [comment]
Mhh that seem to work now... I can reproduce the issue. Was that the cache.. ?
Can you reproduce it ?

**Comment by gnerred** [comment]
I have tried different browsers and I always get this js error, even in Browserstack (see console)...

**Comment by ger-benjamin** [comment]
I don't know where, but somewhere the default theme is defined as "Demo".

So if you navigate for the first time on your geoportal, the loaded theme will be "Demo". This theme doesn't exist. So there is your error. Set the theme manually to avoid the error.

I search for this "default_theme: Demo"...

**Comment by ger-benjamin** [comment]
Can you try to add "functionalities" to "update path" in vars (here https://github.com/camptocamp/cartoriviera_geomapfish/blob/v2/vars_cartoriviera.yaml#L258 )

**Comment by gnerred** [comment]
Thanks, now it works. In the installation process, the mobile.html has been replaced by the one in the base template. That's why there was this default theme.
