### ISSUE TITLE
Backport Ability to log the last update to a feature (#2156) to GMF 1.6

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2582]
### Functionality descripton

During editing, the user and date should be saved together with the changes into the database, in the same table as the geodata. 
- The logs are filled when a new feature is created and when a feature is changed
- The field date is of type Timestamp
- The field user is of type String
- be able to configure if a table is logged or not.
- if a table is logged, it can be assumed that the fields “date” and “user” are present.
- The customer will create the fields “date” and “user” in the geotables.

Reasons for this option (and why we do not do a generic Metadata table): If the table has a constraint of NOT NULL values, which is filled by a trigger from the log table, it is not possible to fill from this second transaction, because the first state will be incoherent.
### To Do

The developements have already be done in GMF 2.0 by @fredj. As the customer cannot install GMF 2.x due to infrastruction restrictions, he needs this feature in GMF 1.6.x. Therefore you need to backport the PR #2156 to the 1.6 branch.

The feature is installed / testable in GMF 2.x here: 
- Login admin/c2c
- Layer "Polygon": https://gmf-test.sig.cloud.camptocamp.net/baselstad/edit/?map_x=542000&map_y=154000&map_zoom=3&tree_group_layers_Edit=polygon&tree_groups=Edit
- Configuration in the admin interface (UI Metadata): https://gmf-test.sig.cloud.camptocamp.net/baselstad/wsgi/admin/LayerV1/71/edit

Developement server: gmf-test.sig.cloud.camptocamp.net

**Comment by eleu** [comment]
what is the state of this issue? thanks for an update.

**Comment by fredj** [comment]
Should be fixed with #2627. @eleu can we close this issue ?

**Comment by eleu** [comment]
I need to test.

**Comment by eleu** [comment]
Ok, I tested and it works. Closing this issue.
