### ISSUE TITLE
Disable geometry check for a layer (GMF 1.6)

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2583]
Exclude some layers from the geometry check (st_issimple PostGIS) usually done for editing layers.

The proposition was to configure the excluded layers in the editing plugin c2cgeoportal config (probably in UImetadata):

All layers will be validated with the PostGIS function:

```
geometry_validation: true
```

All layers will be validated with the PostGIS function except the layers layer_a und layer_b:

```
geometry_validation: all_except:
- layer_a
- layer_b   
```
### To Do
- Implementation in GMF 1.6

Developement server: gmf-test.sig.cloud.camptocamp.net

**Comment by juliensam** [comment]
The geometry_validation is already present at the project level:
```
vars_<project>.yaml:
     ...
     layers:
        geometry_validation: True
```
Do we need to override that with a c2cgeoportal config or should we reuse that configuration?

**Comment by sbrunner** [comment]
The `geometry_validation` will be the default value.

We will add a `geometry_validation` in the layer (UI)metadata (not in the config).

**Comment by eleu** [comment]
what is the state of this issue? thanks for an update.

**Comment by juliensam** [comment]
This is waiting on #2627 to land which is waiting for the test.

**Comment by juliensam** [comment]
Got this working locally by setting geometry_validation="False" in UIMetadata. I just want to make sure that its what we want. Note that the False value will be a string here since UIMetadata column is a string here.

**Comment by juliensam** [comment]
Oh! and as soon as the other PR lands, I'll open one for this one (with all its tests this time).

**Comment by fredj** [comment]
fixed with #2644 ? can we close this issue ? (ping @eleu )

**Comment by eleu** [comment]
I need to test.

**Comment by eleu** [comment]
OK tested and it works. I am closing this isssue.
