### ISSUE TITLE
Display of one of the background layers is slow in ngeo mobile

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2584]
I have several background layers in my ngeo mobile application : https://preprod.cartoriviera.ch/v2/mobile/ 
- Plan ASITVD - gris (remote)
- Orthophoto 2014 (local)
- Plan cadastral (local)
- Plan de ville en perspective (local)

The third one (Plan cadastral) displays slow when navigating on map. The same tiles display quickly in 1.6 : https://preprod.cartoriviera.ch/mobile/?theme=default_mobile&baselayer_ref=plan_cadastral&map_x=556337.74942002&map_y=146070.93774166&map_zoom=3&tree_layers=

**Comment by fredj** [comment]
This layer is loaded as a single tile WMS, the others are loaded as WMTS tiles

**Comment by gnerred** [comment]
Euh.. in my admin interface, the checkbox is not checked for the layer
![image](https://cloud.githubusercontent.com/assets/1989467/19239007/61927b1a-8f04-11e6-8655-81a52240e6b0.png)

**Comment by gnerred** [comment]
Nor for the OGC source
![image](https://cloud.githubusercontent.com/assets/1989467/19239045/94814286-8f04-11e6-91bf-766aacb73eb9.png)

**Comment by sbrunner** [comment]
> Euh.. in my admin interface, the checkbox is not checked for the layer ...

This is a v1 layer not a v2 layer ...

**Comment by gnerred** [comment]
In my 2 screenshots, you can see V1 and V2 version of that layer. In both cases, unique tile is not checked. No one of the OGC server has the unique tile checked.

**Comment by gnerred** [comment]
After a new full migration process of DB, the issue disappeared... I close.

**Comment by sbrunner** [comment]
:-)
