### ISSUE TITLE
[Admin Interface] Set search default parameters

### ISSUE THREAD

**Issue by ponceta** [camptocamp/c2cgeoportal#2589]
Is it possible to redefine default parameters for search tooltip?

Eg: search layer:

![image](https://cloud.githubusercontent.com/assets/8614223/19438313/88dbe68c-9479-11e6-9b9c-0be3781e64e9.png)

to 

![image](https://cloud.githubusercontent.com/assets/8614223/19438320/937e8252-9479-11e6-9c02-1e6cc189659e.png)

If yes, where should I look for?

**Comment by sbrunner** [comment]
No :-(

**Comment by ponceta** [comment]
To keep in mind for the reshaping of admin interface! @sbrunner
