### ISSUE TITLE
ObjectEditing: Access via iFrame

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2590]
Requirements description:
- We want to open the GIS part in an iFrame of the foreign application (for instance LeiNa).

Work to do:
- The iFrame will be integrated into a foreign domain name. We expect that some CORS issues need to be solved.
- Add a permalink that contains an attribute with:
  - the creation date
  - the user
  - the object to edit (its foreign key ID as data)

**Comment by sbrunner** [comment]
@eleu can we close it, isn't it managed on Jira?

**Comment by eleu** [comment]
We can close it. It is not managed on Jira AFAIK, but the issue is done. Thanks to all!
