### ISSUE TITLE
ObjectEditing: Security

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2591]
Requirements description:
- All functionalities apply to protected and public layers.
  - Editing only on protected layers
  - Copy / Delete from also for non-edit and public layers
- The foreign application passes an encrypted BLOB with the authorisation information to the iFrame when the iFrame is opened. The BLOB contains object IDs (list or token “all”), the time stamp and role (for other role specific configurations) that can be accessed by this user.
- Multidomain Mode
- The session won’t be invalidated once the user quits the GIS application.

Work to do:
- Create a view to:
  - decrypt the blob data.
  - verify that the user exists.
  - verify that the bunk data isn't outdated.
  - return the cookie, the role, the data.

**Comment by sbrunner** [comment]
@eleu can we close it, isn't it managed on Jira?

**Comment by eleu** [comment]
we can close it. It is not managed on Jira AFAIK, but the issue is done. Thanks to all!
