### ISSUE TITLE
ObjectEditing: Editing of a Single Object

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2592]
Requirements description:
- In difference to the existing editing, the Object Editing will only concern editing of one object at once. Depending on the ID passed when opening the Object Editing, only this object (multipolygon, in future also multi-line and multipoint) will be editable.

Work to do:
- Create a custom interface, along with the existing interfaces “view” and “edit”
- onunload Event: saves the changes if the window / iFrame is closed.

**Comment by adube** [comment]
Specs (in progress): https://github.com/camptocamp/c2cgeoportal/wiki/spec-2592-oe-single-object-edit

**Comment by adube** [comment]
This task is more related to the base setup, i.e. the initial creation of the applications.  The "on unload" event should be moved to a separate task.  @eleu I created an other task for that: #2599.  Would you please link it to this project?  It would seem that I can't.

**Comment by adube** [comment]
@fredj I will need help for the 'building of the JS' portion.  This is not urgent, as this task will only be done in a couple weeks.  This is just a 'heads up'.

**Comment by eleu** [comment]
done, but still need to test.
