### ISSUE TITLE
ObjectEditing: Access and Centering

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2593]
Requirements description:
- The URL contains a foreign key ID
  - If the foreign key has an entry in the geodata DB, the application zooms on this object
  - If the foreign key is not found, zoom on the coordinates passed in the URL
  - Or on the WFS Permalink in the URL
    ![image](https://cloud.githubusercontent.com/assets/1632411/19468677/06ef36a2-9518-11e6-91b5-5ed382b70797.png)
- Changes in the geometry should be visible immediately on the map.

Work to do:
- In the client part:
  - call the view
  - fetch the return
  - mark as login with the user
  - open the editing tool
  - get the feature
  - center on it
- Offer two tool groups on the right side (maybe this is no work, and only configuration):
  - Query tool
  - Editing tools (details see below)

**Comment by adube** [comment]
Specs (in progress): https://github.com/camptocamp/c2cgeoportal/wiki/spec-2593-oe-access-and-centering

**Comment by adube** [comment]
This task has a high priority.

**Comment by eleu** [comment]
done, but still need to test.
