### ISSUE TITLE
ObjectEditing: Edit Tools

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2594]
Requirements description:

![image](https://cloud.githubusercontent.com/assets/1632411/19468812/b409b6aa-9518-11e6-9121-553274834fa3.png)

The Object Editing should offer specific editing tools described in the following: 
- [All geometry types] Modify vertices by clicking on the geometry

Buttons (exclusive, On/Off, directly visible in the interface, not second level actions):
- [Multipolygon/Multiline/Multipoint] Draw/Add. If overlap: add to existing polygon (merge). This functionality is primarily used for multipolygons.
- [Multipolygon] Triangle: draw a triangle with a specific size by clicking on the map (used for marking of non-defined surfaces). If the triangle overlaps an already drawn geometry-part, it is merged (same behaviour as the above Draw/Add functionality).
- [Multipolygon/Multiline/Multipoint] Draw (Eraser): draw geometries that erase a part of the object geometries (used for doughnuts). This functionality is primarily used for multipolygons.
- [Multipolygon/Multiline/Multipoint] Modify surface: select layer from predefined list to copy from, click on one object of this layer. 
  - The object can come from a non-editable layer. 
  - If the geometry overlaps with an existing geometry, merge. 
  - The layer has to be a the same geometry type as the edited object (primarily used for multipolygons).
  - The layer to copy from has to be selected in a combobox list before clicking in the map to select the geometry.
- [Multipolygon/Multiline/Multipoint] Modify surface: select layer from predefined list to delete from, click on one object of this layer.
  - The object can come from a non-editable layer.
  - The layer has to be a the same geometry type as the edited object (primarily used for multipolygons).
  - The layer to copy from has to be selected in a combobox list before clicking in the map to select the geometry.

Buttons (exclusive, On -> Action, directly visible in the interface, not second level actions):
- [All geometry types] Revert last action(s): all actions that are not yet saved to the server can be reverted. The not yet saved objects have to be colored differently than the saved objects.
- [All geometry types] Delete all: delete the entire object (all parts of the multipolygon). Check if the user has the right to delete the object (with BLOB info from the foreign application).
- [All geometry types] Save: Save the modifications on the server side. Check if the user has the right to save the object (with BLOB info from the foreign application). If the geometries are invalid (overcrossings, etc.), an error message is returned (according to default PostGIS “is valid” rules).

Work to do:
- Draw-Add: no special implementation notes
- Triangle: Config:
  coordinates [[dx, dx], ...] where dx and dx will be the difference from the clicked point in projection unit.
- Delete from:
  - combobox to select the layer
  - do a mapfish protocol query (attention! we also want to delete from non-editable layers!)
  - delete the feature (server call)
- Copy from
  - combobox to select the layer
  - do a mapfish protocol query (attention! we also want to delete from non-editable layers!)
  - copy the feature
- Eraser:
  - draw a geometry
  - remove it (server call)
- Undo: no special implementation notes
- Delete all: no special implementation notes
- Save: no special implementation notes

**Comment by adube** [comment]
Note: right-clicking on a feature should show a menu **without** the 'move' option.  See: #2595.

**Comment by adube** [comment]
Specs (in progress): https://github.com/camptocamp/c2cgeoportal/wiki/spec-2594-oe-edit-tools

**Comment by adube** [comment]
This task has the second highest priority.

**Comment by sbrunner** [comment]
@eleu can we close it, isn't it managed on Jira?

**Comment by eleu** [comment]
we can close it. It is not managed on Jira AFAIK, but the issue is done. Thanks to all!
