### ISSUE TITLE
ObjectEditing: Disallow Moving of a Polygon

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2595]
Requirements description:
- With the current editing tools, it is possible to move the polygons. It should be possible to disable moving for an entire project / for the Object Editing.

Work to do:
- Allow to disable the moving of polygon button. Only Rotate and Delete will be available when a user right-clicks the geometry.

**Comment by adube** [comment]
@eleu We won't need to have an option to disable the moving of polygon.  We will have a new directive that assembles all the components from NGEO and GMF required to do the editing of OE, in which we will simply not have the "move" button.

You can close this.

We'll add this detail in the specs of the "editing tools".
