### ISSUE TITLE
ObjectEditing: View a subset of objects [no editing!]

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2597]
Requirements description:
- Administrator can view a subset of objects
- The list of objects to show are passed in the URL or in POST, and can be in different layers
- The number of objects IDs to pass can be large, 160 to 1000 Objects with a Object-ID length of about 9 characters.

Work to do:
- We want to use the WFSPermalink functionality in order to show these objects
- The WFSPermalink has though to be changed so we can also do PostMessage, so we can pass more than 160 objects. Draft:
  
  ```
  <html>
  <body>
      <iframe id="iframe" src="https://<url-leina-gis>"></iframe>
      <script>
      window.onload = function() {
          var iframe = document.getElementById('iframe').contentWindow;
          iframe.postMessage({
              "action": "open",
              "ids": [1, 2, 3, 4]
          }, "*");
      };
      </script>
  </body>
  </html>
  ```

**Comment by eleu** [comment]
done, but still need to test.

**Comment by eleu** [comment]
@sbrunner is this done? something has been done [here](https://github.com/camptocamp/ngeo/pull/2058), but I don't think the server side has been done. Can you list here what need to be done in detail and re-open?

**Comment by sbrunner** [comment]
Witch server part?

**Comment by sbrunner** [comment]
For be there isn't a server part, and nothing is done for that on this pull request ...

**Comment by sbrunner** [comment]
@eleu can we close it, isn't it managed on Jira?

**Comment by eleu** [comment]
we can close it. It is not managed on Jira AFAIK, but the issue is done.
