### ISSUE TITLE
ObjectEditing: Create a "Hub" example

### ISSUE THREAD

**Issue by adube** [camptocamp/c2cgeoportal#2600]
For the ObjectEditing project, we will use
- the GMF demo server
- the "Editing" theme
- the "Polygon" layer

Features in the polygon layer are the ones we'll have to work with in the OE Editor.  The idea behind this task is to create a "Hub" example in which we would have:
- a list of feature ids in a combobox, which get retrieved using a request to the server
- a list of pages (examples, applications)
- ~~a list of roles~~
- a "run" button

On "run", the selected page is opened in a new window (as-if we had opened an iframe).

The main reason behind this is that the GMF demo server is played with a lot, i.e. we can't assume that certain feature ids are always present and hardcode them in the examples / applications.  The Hub example would be useful for that.
## Technical details

Here's the plan I suggest.

1) In the example, we hardcode the following layers from the "Editing" theme: Polygon, LineString, Point.  If we wanted to avoid hardcoding, we'd have to use the theme service to get the themes, loop in all themes and look for editable layers, see which ones are editable, probably do DescribeFeatureType request to identify the 'id' (I may be wrong), and from there we'd have our layers.  From there, we create the list of layers in html.

2) For each layer, we do a WFS GetFeature request to retreive all features and collect theirs ids.  We create one list of features per layer in html.  The one visible is the layer we have selected.

3) We create a list of urls for each examples we want to run.  For now, we'll use an existing example of GMF that has no relation to OE, just to test the layers.

4) Hardcode a list of roles, for now: (adube, admin)

5) Create a run button that compiles the selected choices ~~\+ a timestamp~~ and opens the url in a new tab.

We will have a 'layername' in addition of the required parameters that are encrypted.  That will be for development purpose to be able to test points, lines and polygons.  In the real app, we should configure the one we want and not use the url.

**Comment by adube** [comment]
@eleu  Would you please assign this to the ObjectEditing project?

**Comment by eleu** [comment]
sounds good, have I understood right that the "hub" is the simulation of the third party application that will be used to access the object editing? So hardcoding is only done in this "third-party-application simulation"?

**Comment by adube** [comment]
Yes, that would be the purpose of this example.  It would be the point of entry in GMF to be able to load a OE page by having to select a feature id first.  You understood correctly.

**Comment by adube** [comment]
This task is completed. See the example live here:

https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/objectediting-hub.html

@eleu You can close this task as completed and move it in the completed section of the ObjectEditing project.
