### ISSUE TITLE
Print V2 not working with GMF 2.1

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2611]
When trying to print on the desktop CGXP, I get a 404 not found on the https://preprod.cartoriviera.ch/v2/wsgi/printproxy/info.json

To reproduce, try to print : https://preprod.cartoriviera.ch/v2/

**Comment by sbrunner** [comment]
The print version 2 support is removed here: https://github.com/camptocamp/c2cgeoportal/commit/a50785fdbed902387ad972e1ba36a1115190b3aa
It's possible that we make it a bit to early...

**Comment by gnerred** [comment]
What ? Print V2 is no more possible ? It was planned to keep it working in 2.1...

**Comment by sbrunner** [comment]
I can revert it, but it will be removed in 2.2...

**Comment by gnerred** [comment]
Yes thanks if you can revert it. The 2.1 migration is heavy enough, so I will appreciate to do the migration of print later... ;O)
