### ISSUE TITLE
Make build change detection wrong after deploy

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2618]
when using the deploy package to deploy the project from one server to another, the code in the Makefile which detect if a ressource has changed and need to be rebuild always detect the source has changed, even if it wasnt the case,
possibly because of the copy/rsync of the code or the change of owner (deploy user take ownership)
as a result, after a deployment, we always have a full build triggered and it takes a very long time for nothing

**Comment by svavoi** [comment]
Is this an issue that will be solved soon? or is there a workaround for it?
It is really annoying that the deploy makes a full build and takes a very long time.

**Comment by sbrunner** [comment]
Is it working if we add the config 
```
rsync_args = --recursive --links --compress --perms --times --delete --chmod=ug+rw,Dg+s
```
in the `deploy.cfg.mako` file?

**Comment by svavoi** [comment]
I've added the line in the deploy.cfg.mako in the [main] section:

```
[main]
hookdir = %(here)s/hooks/
# to update the static schema, we need to deploy the code first
restore_order = code,database,files
rsync_args = --recursive --links --compress --perms --times --delete --chmod=ug+rw,Dg+s
```

But it didn't show an effect. There is still a built of all the .mako files.

**Comment by sbrunner** [comment]
Building all the mako files is normal, because it can be infra dependent ...

**Comment by svavoi** [comment]
True... thanks for pointing it out. 
It is just very slow when you have 170 .map.mako files... Would be nice if it would be faster.

**Comment by sbrunner** [comment]
It is possible to store a temporary file the generated strings, @ochriste is it possible to do a test on how many times it takes?
