### ISSUE TITLE
Another error during upgrade to 2.1.0rc4

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2639]
After doing : 

export VERSION=2.1.0rc4
make -f v2.mk upgrade

I get the following error : 

Successfully installed c2cgeoportal-2.1.0rc4
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
.build/venv/bin/c2ctool upgrade v2.mk  2.1.0rc4

================================================================
Failed downloading the c2cgeoportal CONST_versions_requirements.txt file from URL:
http://raw.github.com/camptocamp/c2cgeoportal/2.1.0rc4/c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
The upgrade is impossible
CONST_Makefile:1220: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1

**Comment by kalbermattenm** [comment]
Same for me...

**Comment by sbrunner** [comment]
Sorry for the confusion, 
The version should be `2.1.0.rc4` (with a dot before rc) :-)
