### ISSUE TITLE
Psycopg2 in CONST_versions_requirements

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2641]
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt#L27

Hmmm... this is not good for Windows... Why was this added again, as it is already defined in https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_requirements.txt#L7 and https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt#L2 ?

**Comment by sbrunner** [comment]
It's an error :-)
