### ISSUE TITLE
Next error in step 1 upgrading to rc4

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2645]
Now I get this error:

```
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) ERREUR:  la colonne ┬½ auth ┬╗ contient des valeurs NULL
 [SQL: 'ALTER TABLE main_internet2.ogc_server ALTER COLUMN auth SET NOT NULL']
CONST_Makefile:1244: recipe for target 'upgrade1' failed
make: *** [upgrade1] Error 1
```

What is `auth` supposed to be ?

**Comment by kalbermattenm** [comment]
And why are all this columns set to `NOT NULL`..........

**Comment by sbrunner** [comment]
> What is `auth` supposed to be ?

For internal WMS: `Standard auth` :-)
For external: `No auth`
For internak Geoserver: `Geoserver auth`

> And why are all this columns set to NOT NULL..........

To don't throw errors on the runtime :-)

**Comment by kalbermattenm** [comment]
But what should put as data into that column ? `Standard auth` ?

And shouldn't that be part of the migration process...?

**Comment by sbrunner** [comment]
> But what should put as data into that column ? `Standard auth` ? 

Yes :-)

> And shouldn't that be part of the migration process...?

Yes it can... (event it for people that do the standard migration from 1.6 to 2.1 will not be inpacted)
