### ISSUE TITLE
Print V2 doesn't work in 2.1.0.rc4 on CGXP

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2647]
Version 2.1.0.rc4

To reproduce : https://preprod.cartoriviera.ch/v2/  and try to print

**Comment by sbrunner** [comment]
Should be fixed on our side ...

**Comment by gnerred** [comment]
So I have to wait next rc... ?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by rbovard** [comment]
@sbrunner @ybolognini Please improve the tests of your RC, it's very annoying and time consuming to have those kind of issues on every releases.
