### ISSUE TITLE
Time in Query

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2652]
See specifications here (to be confirmed/validated): 

https://docs.google.com/document/d/1lprBtD_52AjcOk-6jvABEX_xJn5uE9C4qrdzatj2TZE/edit#heading=h.xxfcan43wtj4

**Comment by fredj** [comment]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232652-Time-in-Query
