### ISSUE TITLE
Message if no full-text search results

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2653]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232653-Message-if-no-full-text-search-results

**Comment by fredj** [comment]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232653-Message-if-no-full-text-search-results

**Comment by ybolognini** [comment]
@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Specs show how we'll implement it (validated by @svavoi)
