### ISSUE TITLE
Keep "switch to desktop" functionnality

### ISSUE THREAD

**Issue by ponceta** [camptocamp/c2cgeoportal#2705]
Hi,

I'm currently testing geomapfish on ipad devices and larger mobiles screens and there is still a need to be able to redirect to the desktop version to access more functionnalities. (print, draw, share).

![image](https://cloud.githubusercontent.com/assets/8614223/20961925/7edf34e8-bc67-11e6-8ba6-fd21972e5527.png)

But it could be more discreet.

There are some/all touch pc which actually get the mobile version from GMF 1.6 as default when passing the standard url. Detection engine parameters should be improved.

```
"sur la 2.1 avec un notebook Win10 tactile :
-          Chrome -> version mobile + pas de lien pour retourner sur desktop
-          FF,IE et Edge -> version desktop" 
```

**Comment by sbrunner** [comment]
Fixed by https://github.com/camptocamp/ngeo/pull/2428
