### ISSUE TITLE
Print V2 still doesn't work with 2.1.0.dev25

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2715]
Go to https://preprod.cartoriviera.ch/v2/theme/cadastre and try to print -> error 500

**Comment by sbrunner** [comment]
You have two issue in your code:

* the print_url in the vars file should ends with a '/'
* you remove the `print_template` from `admin_interface.available_functionalities` in your `vars` file...

**Comment by gnerred** [comment]
Fine now it works thanks !

But I think you did the second modification, when you tried to debug ;O)

**Comment by rbovard** [comment]
I just bumped into the same issue, is it documented somewhere for the trailing `/`?

**Comment by sbrunner** [comment]
Yes, it's documented here: https://camptocamp.github.io/c2cgeoportal/2.1/integrator/legacy_print.html

**Comment by rbovard** [comment]
Okay, thanks.
