### ISSUE TITLE
Issue when renaming role

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2722]
When renaming a role, the users with this role lose it.

Project:
* GeoMapFish version: 1.6.8

Steps to reproduce:
* Log in the admin interface
* Create a new role
* Put an user in this role
* Rename the role
* Edit the user --> The role is set to `None`

**Comment by sbrunner** [comment]
This trigger should solve youe issue:

``` sql
CREATE OR REPLACE FUNCTION on_role_name_change()
  RETURNS trigger AS
$$
BEGIN
 IF NEW.name <> OLD.name THEN
 UPDATE main_static."user" SET role_name = NEW.name WHERE role_name = OLD.name;
 END IF;
 RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER on_role_name_change AFTER UPDATE ON main.role FOR EACH ROW EXECUTE PROCEDURE on_role_name_change();
```
