### ISSUE TITLE
[1.6.9][Edge] Multitouch non supporté

### ISSUE THREAD

**Issue by ponceta** [camptocamp/c2cgeoportal#2724]
Le zoom multitouch sur Edge abouti à un zoom client sur mobile et desktop.

Ref https://github.com/camptocamp/pully_geomapfish/issues/57

N'est pas lié à la 1.6, ~~encore en vigueur en 2.1~~

Edit : Corrigé sur 2.1 (fonctionnel sur 2.1 demo desktop et mobile)

**Comment by ybolognini** [comment]
Serait-il possible d'avoir des précisions sur le hardware (+version Edge) utilisé ?

Je viens de tester sur un Sony Vaio touchscreen Edge 25.1 et il me semble que tout fonctionne correctement.

**Comment by ponceta** [comment]
Samsung Galaxy TabPro

Windows 10 / Microsoft Edge 38.14393.0.0 / Microsoft EdgeHTML 14.14393

Corrigé sur 2.1 Apparemment (fonctionnel sur 2.1 demo)

**Comment by sbrunner** [comment]
Is it fully working, If not reopen it.
