### ISSUE TITLE
ogcproxy failed with mapserv string within an url 

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/c2cgeoportal#2746]
Project:

* GitHub URL: pully_geomapfish
* Infrastructure description URL:
* Host: sigip.ch, map.nyon.ch, ...
* GeoMapFish version: 1.6.x (x >= 9)

Open an URL in "open an external WMS":
* OK: https://map.nyon.ch/prod/wsgi/ogcproxy?url=https%3A%2F%2Fwms.geo.admin.ch%2F%3Flang%3Dfr%26service%3DWMS%26request%3DGetCapabilities%26version%3D1.1.1&_dc=1484222843602&service=WMS&request=GetCapabilities
* FAILED: https://map.nyon.ch/prod/wsgi/ogcproxy?url=https%3A%2F%2Fwww.sigip.ch%2Fmain%2Fwsgi%2Fmapserv_proxy%3Fservice%3DWMS%26request%3DGetCapabilities%26version%3D1.1.1&_dc=1484222860898&service=WMS&request=GetCapabilities

Result:
The second url failed with a 404 error on ogcproxy service.

@sbrunner said that mapserv string could interfer with the ogcproxy service or so.

**Comment by yjacolin** [comment]
This is not a bug but a security "feature".

**Comment by asaunier** [comment]
> This is not a bug but a security "feature".

This is done here: https://github.com/camptocamp/c2cgeoportal/blob/1.6.11/c2cgeoportal/__init__.py#L374-L384
