### ISSUE TITLE
Upgrade 1.6 to 2.1.0rc7

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#2756]
Upgrade demo 1.6 to 2.1.0rc7 with ngeo for all interfaces and printv3
Current test url: https://testgmf.sig.cloud.camptocamp.net/bge (no background layer for now)

## 1) Minor note: 
- [x] Why ngeo release are named: `2.1.0-rc.7` and in c2c `2.1.0rc7`

## 2) upgrade:
 - No errors
 
## 3) upgrade2:

- [x] **3-A) Warnings**
````
.build/venv/bin/treeitem_uniquename
No handlers could be found for logger "c2cgeoportal.pyramid_"
/home/bgerber/demo_geomapfish/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value 'osm_time-2'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/bgerber/demo_geomapfish/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:219: SAWarning: Unicode type received non-unicode bind param value 'Enseignement-2'. (this warning may be suppressed after 10 occurrences)
````

**3-B) After to apply the changelog and do a new upgrade2**

- [x] *3-B-1) ``.build/venv/bin/themev1tov2``*
````
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) null value in column "image_type" violates not-null constraint
DETAIL:  Failing row contains (134, http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr, ch.astra.ausnahmetransportrouten, ch.astra.ausnahmetransportrouten, 21781_26, null).
 [SQL: 'INSERT INTO main.layer_wmts (id, url, layer, style, matrix_set, image_type) VALUES (%(id)s, %(url)s, %(layer)s, %(style)s, %(matrix_set)s, %(image_type)s)'] [parameters: {'style': u'ch.astra.ausnahmetransportrouten', 'image_type': None, 'layer': u'ch.astra.ausnahmetransportrouten', 'url': u'http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr', 'matrix_set': u'21781_26', 'id': 134}]
````

Problem with several wmts layers (perhaps it's because of our demo layers (layers demo 1.6 distorded by multiple updates tests...))

- [x] *3-B-2) Unable to login properly*

I can login to see the admin interface but got a 403 on each actions. I also can't login properly in the ngeo interface (can login but i'm not logged in after a refresh and can't log out).

## 4) upgrade5:

- [x] *4-A) Error when checkers don't pass*

````
  File "/home/bgerber/demo_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 210, in test_checkers
    self.project["host"], self.project["checker_path"], check_type
ValueError: expected ':' after format specifier

````

## 5) upgrade6:

 - No errors

Done !

**Comment by sbrunner** [comment]
1) The booth npm and pip don't use the same versions nomoclature...

**Comment by ger-benjamin** [comment]
3-B-2: Works fine now, I has some spaces after the demo.mk `VISIBLE_WEB_HOST` variable.
