### ISSUE TITLE
Possible update improvements

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2773]
* Be able to configure witch files the project manage (with regex support)
* Save the upgrade process in a temporary file
* Be able to build a changelog tasks related to the managed files
* Automatically removes the old files

**Comment by ger-benjamin** [comment]
- Better explanation text for the ngeo.diff can be good too.
 - And keep somewhere the diff (ngeo.diff and the others) can be good too. If we forge somethings, the diff are lost after the next upgrade step...

**Comment by ybolognini** [comment]
Done in 2.3
