### ISSUE TITLE
Clear all button in layertree

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2801]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232801-Clear-all-button-in-layertree

**Comment by fredj** [comment]
https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232801-Clear-all-button-in-layertree

**Comment by ybolognini** [comment]
@rbovard @gnerred @svarim @vvmalbre @mriedo @gsollberger @svavoi @cedricmoullet @kalbermattenm

Specs show how we'll implement it (validated by @svavoi)
