### ISSUE TITLE
Android Web browser compatibility

### ISSUE THREAD

**Issue by ybolognini** [camptocamp/c2cgeoportal#2803]
See https://github.com/camptocamp/ngeo/issues/2214

**Comment by ger-benjamin** [comment]
It works on Android v5.02 - Internet ('native' browser v3.2.38.35-1_...)

So, I thinks that's specific to 'Internet' on android 4.x

**Comment by ybolognini** [comment]
@ger-benjamin @sbrunner 
Solution validated by PSC: find a way to display a message "Please upgrade to Chrome" when using an Android Browser

**Comment by sbrunner** [comment]
Can we close #2214?
