### ISSUE TITLE
Suspicious relativ path to build the project standalone

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#2824]
Appears on c2cgeoportal master (20 feb 2017)

I've tried to to a make build on the project but these two lines make issues: 
 - https://github.com/camptocamp/c2cgeoportal/blob/daca42c1b3469531b7dc176ed3ffa5d368ede658/Makefile#L1 (`/build` shouldn't be `build` ?)
 - https://github.com/camptocamp/c2cgeoportal/blob/daca42c1b3469531b7dc176ed3ffa5d368ede658/Makefile#L61 ?

Absolute path... that's not false ?

**Comment by sbrunner** [comment]
The first is correct because now we compile c2cgeoportal with docker, the second isn't...

**Comment by ger-benjamin** [comment]
Ok... so for the first line, we should adapt the documentation, because doing a `make build` doesn't work (see: https://github.com/camptocamp/c2cgeoportal/blame/b0d1b14a864231a9d9d2007a8740d301f84e8bf4/doc/developer/server_side.rst#L23)

**Comment by sbrunner** [comment]
+1, thanks :-)

**Comment by fredj** [comment]
had the same issue, the doc should probably be updated with:
```
BUILD_DIR=./build make build
```

**Comment by fredj** [comment]
For the second issue, what about:
```diff
diff --git a/Makefile b/Makefile
index 71e46a1..a927e5d 100644
--- a/Makefile
+++ b/Makefile
@@ -58,7 +58,7 @@ APPS_FILES = $(APPS_HTML_FILES) $(APPS_JS_FILES) \
        $(addprefix $(APPS_PACKAGE_PATH)/static-ngeo/images/,favicon.ico logo.png background-layer-button.png) \
        $(APPS_PACKAGE_PATH)/static-ngeo/components/contextualdata/contextualdata.html
 
-C2C_TEMPLATE_CMD = $(BUILD_DIR)/venv/bin/python /usr/local/bin/c2c-template --vars $(VARS_FILE)
+C2C_TEMPLATE_CMD = $(BUILD_DIR)/venv/bin/python $(BUILD_DIR)/venv/bin/c2c-template --vars $(VARS_FILE)
 
 
 .PHONY: help

```

**Comment by sbrunner** [comment]
No, it should be:
```bash
./docker-run make build
```
:-)

**Comment by sbrunner** [comment]
After reflection for me booth are correct, but the build should be done in docker :-)

**Comment by sbrunner** [comment]
Can that be closed?

**Comment by ger-benjamin** [comment]
For me, yes
