### ISSUE TITLE
Use pytest in place of nose

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2841]
Because nose isn't anymore maintained ...
https://github.com/nose-devs/nose/

**Comment by sbrunner** [comment]
First test: https://github.com/camptocamp/c2cgeoportal/tree/pytest

**Comment by sbrunner** [comment]
Also related to: https://github.com/camptocamp/c2cgeoportal/tree/codacy-coverage

**Comment by ybolognini** [comment]
Done in 2.3
