### ISSUE TITLE
Checker for cgxp viewer

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2847]
According to the doc, it's possible to add checker for ngeo desktop querying `desktop` route but is there a way to use the cgxp version?

Because the interface has no name: `add_interface(config)`

**Comment by sbrunner** [comment]
The default interface name is `desktop` :-)

We can see it here: https://camptocamp.github.io/c2cgeoportal/2.1/integrator/legacy_cgxp.html?highlight=add_interface#back-to-the-ngeo-interface
here: https://camptocamp.github.io/c2cgeoportal/2.1/integrator/ngeo.html?highlight=add_interface#add-a-new-interface
and here: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/pyramid_.py#L89-L91 😛

**Comment by rbovard** [comment]
Cool, thanks @sbrunner I didn't notice the default values...
