### ISSUE TITLE
Add a mecanism to remove a temp file

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2871]
Would it be possible to add something to delete the {package}-client.pot in the `local` of the package (if this file already exists), before creating it.

I quite often get the error here under and manually deleting the file resolves the problem, but I would prefer if the build system would take care of that....

```
WindowsError: [Error 183] Cannot create a file when that file already exists
CONST_Makefile:708: recipe for target 'sitn/locale/sitn-client.pot' failed
make: *** [sitn/locale/sitn-client.pot] Error 1
```

**Comment by kalbermattenm** [comment]
https://github.com/camptocamp/sitn_c2cgeoportal/pull/1378/commits/1dbf934359b1d41c6a737ad4937b7f1749c63f9a

Would you accept such a PR ?

**Comment by sbrunner** [comment]
Yes with a comment that's for `WindowsError` :-)
