### ISSUE TITLE
Ngeo package.json not updated when running c2cgeoportal upgrade

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2879]
when updating the project gr_webmap from c2cgeoportal 2.2 to 2.2.0-dev.9,
the package.json was not updated correctly,
I got an old version of the file, version 2.1.1

I had to manually get the right version of the package.json from git girectly

**Comment by sbrunner** [comment]
...? It should be, I can't understand why with those informations...

**Comment by ger-benjamin** [comment]
I'm not sure, but I think that I had a similar problem with the Basel Stadt GMF (from 2.1.0rc4 to 2.1.2).
Finally I've copied manually the package.json in the CONST_create_template folder

@ochriste You say that you take the package.json from git (Github ?). But it is the same file as in your CONST_create_template folder ?

**Comment by ybolognini** [comment]
Obsolete with 2.3
