### ISSUE TITLE
package.json comes from where?

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2880]
I cant find that file,
neither package.json_tmpl

so where does it comes from?

**Comment by sbrunner** [comment]
It's the "merge" result from the current one and the file that come from the egg https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/c2ctool.py#L380-L394, witch one is imported from ngeo https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/import_ngeo_apps.py#L145-L169...
