### ISSUE TITLE
Background layer warning

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2887]
In GMF >= 2.x, if one does not want to use the background layer selector (`gmf-backgroundlayerselector`), then c2cgeoportal should not complain about it:
```
Unable to find the Group named: background, Available Groups: gp_general, ...
```

Or is there a way to turn that specific warning off ?

**Comment by sbrunner** [comment]
int the theme request (here: https://github.com/camptocamp/demo_geomapfish/blob/master/demo/templates/desktop.html#L315), remove the `background` int the query.
=> 
```
module.constant('gmfTreeUrl', '${request.route_url('themes', _query={"interface": "desktop", "version": "2"}) | n}'); 
```
I hope that's working :-)

**Comment by kalbermattenm** [comment]
+1, thanks a lot for the hint @sbrunner !
