### ISSUE TITLE
Fulltextsearch problem - Secured search does not work anymore with QGIS quickfinder

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2892]
Version 2.1.2

QGIS quickfinder plugin uses GMF FTS service to search and locate objects within QGIS. Until version 1.6, the plugin worked well with secured and non secured search. Since 2.1.2, only non secured search works, secured one does not. Is there a special special config (Apache or something else) that I missed during migration ? Secured search works well in GMF CGXP and NGEO mobile. 

Concerned code in plugin is here : https://github.com/3nids/quickfinder/blob/master/core/geomapfish_finder.py#L50-L56 
ping @3nids 

Thanks

**Comment by gnerred** [comment]
@3nids you have to set the referrer in the request you make (dixit @sbrunner ). Could you please test ?

**Comment by 3nids** [comment]
yep, it works with referer, thanks!

**Comment by gnerred** [comment]
Cool :-)
