### ISSUE TITLE
make clean in deploy pre-restore-database.mako will kill the project if only deploying db

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2900]
in https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako#L11
we do a make clean

but if we only deploy de database and not the project code, the project is not rebuilded because we only do a selective build:

https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako#L41

as a result, after deploying the bd, the project is dead and must be rebuilded manually

**Comment by sbrunner** [comment]
Obsolet with Docker
