### ISSUE TITLE
Encoding issue in admin interface

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2907]
Should we move that:

https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/apache/application.wsgi.mako#L7-L8

To here:

https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/%2Bpackage%2B/__init__.py_tmpl#L8

In order for both, Apache and pserve, to work on the admin pages.

**Comment by sbrunner** [comment]
I don't know, I don't like to generalize something consider dangerous...

**Comment by kalbermattenm** [comment]
OK, thus I close that and it is any way now in the "c2cgeoportal" issue history if anyone needs to make it work via pserve ;-)
