### ISSUE TITLE
Workflow to add metadata in admin interface

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2924]
Is it possible to document the workflow to add [metadata](https://camptocamp.github.io/c2cgeoportal/master/administrator/administrate.html#metadata) on a new layer please?

For example set those values to a new layer:
* `metadataUrl`
* `iconUrl`
* `legend`
* `isLegendExpanded`

It seems a little confused for me, we need to add all metadata one by one? And for the edition it's seems time wasting to edit all metadata of a given layer...

I know that there is plans to create a new admin panel, but I want to be sure I've understood the workflow about metadata correctly...

**Comment by rbovard** [comment]
BTW are all the metadata values documented somewhere?

**Comment by sbrunner** [comment]
It should be documented here: https://camptocamp.github.io/ngeo/master/apidoc/gmfThemes.GmfMetaData.html :-/

**Comment by sbrunner** [comment]
Yes should fix the API document generation to have this page :-)
