### ISSUE TITLE
themev1tov2 tool doesn't keep column description

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2925]
The tool *themev1tov2* doesn't keep `main.layergroup_treeitem.description`

For memory, this column was introduced following this discussion: https://github.com/camptocamp/c2cgeoportal/issues/1623#issuecomment-160919395

**Comment by rbovard** [comment]
I noticed this column because I absolutely need it, but are you sure that there is not other forgotten columns?

**Comment by rbovard** [comment]
Thanks for fixing this but are you sure that all fields are kept?

**Comment by sbrunner** [comment]
I do my best for having all the fields but it's not exclude that an other field is missing :-/

**Comment by rbovard** [comment]
Thanks, it's working.
