### ISSUE TITLE
Secured layers are visible in GetCapabilities

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2929]
There is a regression in `2.1.4` compared to `1.6.8` because secured layers are visible in GetCapabilities.

* Without login
  * Private layers are in GetCapabilities --> **WRONG**
  * I can add them in QGIS and only the legend is displayed (no data) --> The legend should be protected no?
* With login
  * Private layers are shown in GetCapabilities --> **OK**
  * I can add them in QGIS and the data and the legend are displayed --> **OK**

On `1.6.8` it's fine:
* Without login
  * Private layers are not in GetCapabilities --> **OK**
* With login
  * Private layers are in GetCapabilities --> **OK**
  * I can add them in QGIS and the data and the legend are displayed --> **OK**

Original post: https://github.com/camptocamp/c2cgeoportal/issues/2921#issuecomment-300499084

**Comment by sbrunner** [comment]
Duplicated with #2921

**Comment by rbovard** [comment]
No it's not the same, in my case the secure layers are visible without login and @gnerred has trouble to see secure layers with login.

I've volontary opened this issue to keep those issues distinct.

**Comment by sbrunner** [comment]
> I can add them in QGIS and only the legend is displayed (no data) --> The legend should be protected no?

no, we never do this

**Comment by rbovard** [comment]
Ok, thanks for the info.

BTW could you please reopen this issue, since @ger-benjamin is working on it.

**Comment by rbovard** [comment]
Thanks, it's working.
