### ISSUE TITLE
MapfishPrint 3.8 - class override - ThreadPoolJobManager has been moved to new impl subfolder

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#2936]
when using MapfishPrint 3.8
in https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/print/WEB-INF/classes/mapfish-spring-application-context-override.xml 
the path to ThreadPoolJobManager is now 
org.mapfish.print.servlet.job.impl.
instead of
org.mapfish.print.servlet.job.

**Comment by jwkaltz** [comment]
With PR https://github.com/camptocamp/c2cgeoportal/pull/3097, the new configuration will be included in c2cgeoportal
(there are PR for older versions of c2cgeoportal as well)
