### ISSUE TITLE
Error when printing external WMS (QGIS server) layers

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2958]
Print V 3
GMF V 2.1

A Java error "is denied" is thrown when trying to print external WMS layers (from QGIS server) layers. To reproduce : 

1°/ Go to https://preprod.cartoriviera.ch/s/vBFG
2°/ Click on the print button
3°/ Click on "Imprimer PDF" -> http://127.0.0.1/qgis/qgis_mapserver.fcgi?TRANSPARENT=true&TRANSPARENT=true&MAP_RESOLUTION=254&BBOX=554365.05%2C145408.75%2C554929.4500000001%2C145683.75&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=1375&REQUEST=GetMap&LAYERS=export_wastewater_structure&STYLES=&MAP=%2Fvar%2Fsig%2Fqgis%2Fexport.qgs&SRS=EPSG%3A21781&WIDTH=2822 is denied.

Is there a special access to configure to avoid this "is denied" error ?

**Comment by sbrunner** [comment]
> 1°/ Go to https://preprod.cartoriviera.ch/s/vBFG

=> 404 not found ...

**Comment by gnerred** [comment]
Yes, my preprod is no more working because of the issue concerning migration from 2.1.2 to 2.1.4...

**Comment by gnerred** [comment]
@sbrunner , my preprod is now running again, you can test

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by sbrunner** [comment]
Here there is a missing en entry for qgis server:
https://github.com/camptocamp/cartoriviera_geomapfish/blob/master/print/print-apps/cartoriviera/config.yaml.mako#L54-L55 :-)

**Comment by gnerred** [comment]
I've tried with the following configurations, but I get the same problem at each time (at this time, the last one is configured) : 

                - !localMatch
                  pathRegex: http://127.0.0.1/qgis

                - !localMatch
                  pathRegex: /${__import__('re').escape(instanceid)}/qgis

                - !localMatch
                  pathRegex: /${__import__('re').escape(instanceid)}/qgis/qgis_mapserver.fcgi

**Comment by ochriste** [comment]
essaie
- !localMatch
                  pathRegex: "/qgis"

**Comment by ochriste** [comment]
err, more likely

pathRegex: "/qgis/.*"

**Comment by gnerred** [comment]
Great thanks @ochriste , it works :O) !

**Comment by sbrunner** [comment]
or :-)

                - !localMatch
                  pathRegex: /qgis/qgis_mapserver.fcgi
