### ISSUE TITLE
Error while upgrading from GMF 2.12 to 2.1.4

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2959]
When trying to upgrade from 2.1.2 to 2.1.4, I get the error below, and the shell freezes... I had to do a CTRL+C to get back cursor... 

export VERSION=2.1.4
make -f preprod.mk upgrade
.....
node_modules/.bin/npm install --force
npm WARN npm npm does not support Node.js v0.10.29
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'

**Comment by rbovard** [comment]
Thanks @gnerred! I had the same issue just on build and didn't understand what's going on, see https://github.com/camptocamp/c2cgeoportal/issues/2934#issuecomment-302083481.

So there is something else @yjacolin @sbrunner (*I'm not crazy*)

**Comment by yjacolin** [comment]
We are investigating. Remi should confirm soon that the upgrade make the build working correctly, we will upgrade yours after this confirmation.

**Comment by rbovard** [comment]
It builds with the nodejs upgrade.

**Comment by gnerred** [comment]
Ok thanks, I wait for your update

**Comment by gnerred** [comment]
FYI, it is not even more possible de reinstall the previous 2.1.2, I always get this same error...

**Comment by rbovard** [comment]
Yes, the build is broken on all c2c managed servers because of this strange nodejs issue...

It's not related to the GMF version.

**Do not rebuild your prod instance!**

**Comment by gnerred** [comment]
OK Thanks @rbovard  ;O)

**Comment by yjacolin** [comment]
@gnerred could you test it? We will upgrade all server next week but we upgraded your this morning.

**Comment by gnerred** [comment]
The bug is fixed, thanks !
