### ISSUE TITLE
Symbols and labels are too small when printing external QGIS server layers 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2962]
When prining an external WMS QGIS server layer, size of lines, labels and symbols are too small in PDF file. To reproduce : 

1°/ Go here : https://preprod.cartoriviera.ch/s/ffKo
2°/ Click on print button
3°/ Click on "Imprimer en PDF"

Related to https://github.com/camptocamp/ngeo/issues/2654 ?

**Comment by sbrunner** [comment]
This is fixed with ngeo :-)

**Comment by gnerred** [comment]
Ok thanks, so let's close this issue and keep opened the one in ngeo.
