### ISSUE TITLE
Search group order

### ISSUE THREAD

**Issue by fredj** [camptocamp/c2cgeoportal#2963]
It should be possible to change the order of the search groups.

A simple solution would be to be able to define "top" groups.

For example, if the top groups are:
```
top = ['a', 'b', 'c']
``` 
and the search groups:
```
groups = ['z', 'b', 'f', 'a']
``` 
The new group would be:
```
groups = ['a', 'b', 'z', 'f']
``` 
the members of the top groups are shifted up.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-547
