### ISSUE TITLE
2.1.4 -> 2.2.0rc2 - loginuser route error

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2991]
I am trying to upgrade from 2.1.4 to 2.2.0rc2 and I always get an error 500 with a `loginuser` route (see image), but I do not get why... ?

![image](https://user-images.githubusercontent.com/1681332/27371922-ef381440-5662-11e7-9e93-07ce4dced2ed.png)

**Comment by kalbermattenm** [comment]
It might be related to https://github.com/camptocamp/ngeo/blob/658ae09361435d12caa72afb23381260081717b4/contribs/gmf/src/services/authenticationservice.js#L146 as well...

Because this line produces an URL with two slashes, which ends up to a not found web error.

Changing it to:
```
const url = `${this.baseUrl_}${gmf.AuthenticationRouteSuffix.IS_LOGGED_IN}`;
```
resolve it, but not the index out of range on the server side, of course. I tricked this one with an ugly patch (as usual...):

in `cacheversion.py`:
```
def __call__(self, request):
        path = request.path_info.split("/")
        if len(path) > 1 and path[1] in CACHE_PATH:
            # remove the cache buster
            path.pop(2)
            request.path_info = "/" .join(path)

        response = self.handler(request)

        if len(path) > 1 and path[1] in CACHE_PATH:
            response.headers["Access-Control-Allow-Origin"] = "*"
            response.headers["Access-Control-Allow-Headers"] = "X-Requested-With, Content-Type"

        return response
```

**Comment by fredj** [comment]
Previously we used `goog.uri.utils.appendPath` to concatenate the base url and the path, the function prevented this double slash issue.
