### ISSUE TITLE
Attributes translation for WFS results in docker

### ISSUE THREAD

**Issue by llienher** [camptocamp/c2cgeoportal#3000]
When we want to translate the attributes we get in the result of a WFS request, geomapfish use a DescribeFeatureType request to get a list of translatable attributes, such as this link:
https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?VERSION=1.1.0&REQUEST=DescribeFeatureType&SERVICE=WFS 

Currently in the config of any project, if there is docker enabled, the development.ini is ignored:
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L275-L278

The initial reason why this file is ignored is, I guess, that the database container is not running yet at this moment of build. If we can get this step to be done with database access or after the database is up, we could make it work in the docker environment.

As a result now no docker project can translate the attribute's keys we get in popup/table when we are requesting a feature in  WFS (left column) :
![image](https://user-images.githubusercontent.com/25748389/28013743-6847eafc-656a-11e7-86fb-247da0708a3f.png)

**Comment by sbrunner** [comment]
Fixed in 2.3
