### ISSUE TITLE
Detect the server type

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#3015]
In the `production.ini` file add the following configuration:

qgisserver_re
geoserver_re

And use it as regexp in the URL to determine the server type

**Comment by gnerred** [comment]
Ping (just to keep informed about that issue)

**Comment by sbrunner** [comment]
linked to #2793

**Comment by sbrunner** [comment]
@gnerred Just to refresh my memory, this is for the upgrade right?

**Comment by gnerred** [comment]
Which upgrade ? This is for printing QGIS layers

**Comment by sbrunner** [comment]
Oups I will say the themev1tov2 tool...
To have the right server type in the OGCserver table :-)

**Comment by gnerred** [comment]
Yes this is one thing, but even if the server type is right, the print of a QGIS layer does not work properly, and it has to be fixed in this issue, no ?

**Comment by sbrunner** [comment]
No, this is this one https://github.com/camptocamp/ngeo/issues/2793 :-)

**Comment by gnerred** [comment]
Ok so that's fine, this issue is to fix themev1tov2 tool
