### ISSUE TITLE
Edit interface attribute fields order configuration

### ISSUE THREAD

**Issue by ebelo** [camptocamp/c2cgeoportal#3022]
Currently (2x), the edit attributes fields are ordered according their order in the database, with the rule that relation attributes are postponed to the end of the list,

An enhancement would be to add a new metadata to configure the order of the fields in the edit UI.

**Comment by asaunier** [comment]
Do we really need a new metadata for this? I thought mapfile's ``gml_include_items`` could be used to set the order of the returned attributes.

**Comment by ebelo** [comment]
That s a good point.

+1

Emmanuel

**Comment by sbrunner** [comment]
@asaunier but the edit interface use Mapfish protocol, not OGC services...

**Comment by asaunier** [comment]
@sbrunner You're right: the editing plugin is fed using the ``layer_metadata`` service of GMF
https://github.com/camptocamp/c2cgeoportal/blob/306481bac55307ed15cc0e644bedf022cdaa2dbf/c2cgeoportal/views/layers.py#L395
which generates an XSD file listing the table attributes (the order of the attributes in the XSD is the one used in the editing panel). Mapserver (and ``gml_include_items``) is not used at all here.

**Comment by asaunier** [comment]
Suggested implementation:

* edit ``get_table`` at https://github.com/camptocamp/c2cgeoportal/blob/306481bac55307ed15cc0e644bedf022cdaa2dbf/c2cgeoportal/lib/dbreflection.py#L147 and add an optional ``include_properties`` argument (list of colnames). If provided, the generated ``Table`` object's properties are filtered and sorted according to it.
* edit ``get_class`` at https://github.com/camptocamp/c2cgeoportal/blob/306481bac55307ed15cc0e644bedf022cdaa2dbf/c2cgeoportal/lib/dbreflection.py#L173 to add the optional ``include_properties`` argument as well + add some cache based upon this argument.
* add ``include_properties`` to the ``layers_metadata`` route handler at https://github.com/camptocamp/c2cgeoportal/blob/306481bac55307ed15cc0e644bedf022cdaa2dbf/c2cgeoportal/views/layers.py#L395
* add an ``include_properties`` property to the ``Layer`` model, the same way than for ``exclude_properties``: https://github.com/camptocamp/c2cgeoportal/blob/306481bac55307ed15cc0e644bedf022cdaa2dbf/c2cgeoportal/models.py#L569
* add an alembic script to add this new column to the data table ``layer``. See for instance https://github.com/camptocamp/c2cgeoportal/blob/c2c3c02c6b20d77d6d4c7b32b8283ee0be315f30/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/32527659d57b_move_exclude_properties_from_layerv1_to_.py#L49
* add unittests
* update admin interface? Unless forms are automatically built based on the models?
* translations of the new ``include_properties`` attribute name (in Transifex?)

@sbrunner Makes sense to you?

**Comment by sbrunner** [comment]
yes :-)

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-545
