### ISSUE TITLE
Issues with using touch events as reason for mobile redirection

### ISSUE THREAD

**Issue by pfirpfel** [camptocamp/c2cgeoportal#3033]
The[ recommended redirection to the mobile interface](https://github.com/camptocamp/c2cgeoportal/blob/2468bf4f60066c6ca6b9f6d245ca6f81252adb7a/doc/integrator/legacy_cgxp.rst.mako#L109-L110) only checks for the availability of touch events:

`if(('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch) {`

The use of tablets like the Microsoft Surface as desktop replacement gets more and more common. These are often used in conjunction with a docking station and full-sized screens. On such a device you would get automatically redirected to the mobile version despite having a more than sufficiently large screen resolution.

Instead of looking for touch events, we should check the screen resolution with [screen.availWidth and screen.availHeight](https://www.quirksmode.org/dom/w3c_cssom.html#screenview). I don't know what good values for this would be. Maybe a width of 1024px and above?

**Comment by fredj** [comment]
In ngeo mobile, a redirect message is display using the `hidden-xs` (screen width > 768px) CSS: https://github.com/camptocamp/ngeo/blob/28b52b8000fc43a9d4819c17b917102f1db43e08/contribs/gmf/apps/mobile/index.html#L77-L80

We should use the same value.

**Comment by pfirpfel** [comment]
768 might be a bit low. iPads already have this width if you use them in portrait orientation (1024 in landscape).
Also new phones have [crazy high resolutions](http://screensiz.es/phone) (and still relatively tiny screens).

**Comment by fredj** [comment]
Yes, 1024 sounds a good value.

**Comment by sbrunner** [comment]
@pfirpfel the tablets should be redirected to the mobile interface...

**Comment by pfirpfel** [comment]
What about using the user agent? [Mozilla recommends](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) looking for the string "Mobi":

> In summary, we recommend looking for the string “Mobi” anywhere in the User Agent to detect a mobile device.

Example code:
```
if (/Mobi/.test(navigator.userAgent)) {
    // mobile!
}
```

**Comment by sbrunner** [comment]
Reopen for eventually using Modi on 2.3
