### ISSUE TITLE
Copyable is not documented

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/c2cgeoportal#3085]
The page https://camptocamp.github.io/c2cgeoportal/master/administrator/editing.html#enabling-copy-to-functionality define the copy_to function that is only available in CGXP. We have a function "copyable" in NGEO but I don't know well how it works. Please address documentation.

Also, Update the metatdata description to makes it understandable : https://camptocamp.github.io/ngeo/2.2/apidoc/gmfThemes.GmfMetaData.html (search `copyable`)

Also, can't we rename it to "copy_to", as in cgxp ?

**Comment by eleu** [comment]
The "copyable" metadata refers to a interface call ObjectEditing/oeedit that is not yet documented. Hereafter a first draft documentation of the ObjectEditing including "copyable" (see last section, _Copy from_ and _Cut from_).
Can someone integrate this documentation into the doc of c2cgeoportal?

## ObjectEditing

This section describes how to set up editing for one feature at a time in c2cgeoportal applications.
It is accessed via a URL defining the feature and the layer to edit, and opens an object-editing interface which centers on the feature. The feature can then be edited and saved.


### Requirements
The layer has to be editable (see https://camptocamp.github.io/c2cgeoportal/master/administrator/editing.html)
The user has to have the right to edit it (already logged in or using login via URL, see https://camptocamp.github.io/c2cgeoportal/master/integrator/urllogin.html)

### Access via URL
The following parameters can be set in the URL and allow to use the ObjectEditing interface available under /oeedit :

- objectediting_geomtype: MultiPolygon
- objectediting_layer: the layer ID from the Admin Interface
- objectediting_theme: the theme name (untranslated) from the Admin Interface
- objectediting_property: the key for searching the feature in the database
- objectediting_id: the value of the key for searching the feature in the database. If not found, a new feature with this value will be created.


### Features

- Access a feature via a URL, center on it if it exists.
- Editing of this one feature (only one).
 - No tool chosen: Change the feature
 - Plus-tool chosen: Add new parts to the feature (supports multi-point, multi-line, multi-polygon)
 - Minus-tool chosen: Remove parts from the feature 
 - Triangle-tool chosen: Draw a fixed-sized by clicking on the map
 - Copy from: Copy a geometry from another layer. The layer needs WFS and a copyable Metadata.
 - Cut from: Cut the feature with a geometry from another layer. The layer needs WFS and a copyable Metadata.
- FeatureQuery showing a FeatureWindow

**Comment by ger-benjamin** [comment]
Closed with #3099 (GMF 2.2)

**Comment by jwkaltz** [comment]
FYI link to newly created object editing functionality in ngeo (for 2.2):
 https://camptocamp.github.io/c2cgeoportal/2.2/integrator/object_editing.html
