### ISSUE TITLE
Add referer resourceproxy?

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3086]
Hi,

Do you know if there is a way to simply add a referer in the `resourceproxy`?

Thanks in advance for your answer.

**Comment by sbrunner** [comment]
A referer check?

**Comment by rbovard** [comment]
Not this way, sorry if it was not clear. The goal is to load an external ressource with a specifc referer.

**Comment by sbrunner** [comment]
And the referrer isn't forwarded? for me it should be...

**Comment by rbovard** [comment]
Yes, but what I'm looking for is a way to add a custom referrer for a specific target.

**Comment by ebelo** [comment]
Hi @rbovard could you please open a support request on jira?

**Comment by rbovard** [comment]
@ebelo Done: `GEO-441`

**Comment by sbrunner** [comment]
=> close :-)
