### ISSUE TITLE
Allow special characters in dimension table for layertree WMS Filtering

### ISSUE THREAD

**Issue by ebelo** [camptocamp/c2cgeoportal#3109]
In order to use the QGIS WMS Filtering capabilities, one should be allowed to add a FILTER dimension  with following syntax: 
NAME =  FILTER 
VALUE = countries:"name" IN ( 'Germany' , 'Italy' )

In the current system, the theme webservice removes the special characters and throws such an error back:
  "errors": ["The layer 'Agrola' has an **unsupported dimension value** 'stationsch_all:stationPRO IN AGROLA' ('FILTERkkkk')."],

[1] https://docs.qgis.org/2.18/en/docs/training_manual/qgis_server/wms.html#moderate-fa-use-filter-opacities-and-filter-parameters

**Comment by fredj** [comment]
See https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/entry.py#L86-L89
