### ISSUE TITLE
forward_headers is allowed in checker sub sections but readed from checker section

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cgeoportal#3127]
Project: aeroportdelyon_sig

* GitHub URL: https://github.com/camptocamp/aeroportdelyon_sig
* GeoMapFish version: 2.2

In section 'checker' in https://github.com/camptocamp/c2cgeoportal/blob/2.2/c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
`forward_headers` is allowed in `checker` sub sections (for example in section `defaults`).

But in https://github.com/camptocamp/c2cgeoportal/blob/2.2/c2cgeoportal/views/checker.py#L65
it is readed from `checker` section.

So is no more possible to transfert Cookies through checkers.

**Comment by arnaud-morvan** [comment]
IMHO, putting it in section defaults seems more flexible and do not need repetition.

**Comment by arnaud-morvan** [comment]
Could we consider making the config check against schema not blocking, just a warning.

**Comment by sbrunner** [comment]
No, not in the generic code, bet you can override the concerned rule to make what you want :-)

**Comment by sbrunner** [comment]
Isn't better to do a pull request to fix that?
