### ISSUE TITLE
Print - wrong scale in PDF result

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#3133]
Version 2.2.0

To reproduce : go to https://map.cartoriviera.ch, zoom and print at 1:250 for example. The scale given in PDF is wrong

**Comment by sbrunner** [comment]
This https://github.com/camptocamp/cartoriviera_geomapfish/blob/master/print/print-apps/cartoriviera/A0_Landscape.jrxml#L153-L154
Shouldn't be replaced by
```xml
<textFieldExpression><![CDATA[String.format("1:%,.0f",$P{mapContext}.getRoundedScaleDenominator())]]></textFieldExpression>
```
?

**Comment by gnerred** [comment]
Yes now it works with your modification, thanks! 

But it was C2C that configured my jrxml files...

**Comment by sbrunner** [comment]
Yes but the old code works will now working only for 72 DPI, and the new method don't exists previously :-)

**Comment by gnerred** [comment]
Ok thanks, so it has to be documented somewhere during migration
