### ISSUE TITLE
Print problem when setting background layer transparency

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#3140]
Version 2.2.0

To reproduce : 
1°/ Go to https://map.cartoriviera.ch/s/OmSf
2°/ Try to print -> in the PDF, the backgroundlayer plan cadastral is not visible

**Comment by gnerred** [comment]
@sbrunner , this problem is very annoying for our users... Could it be possible to provide a workaround to fix it quickly ? Thanks !

**Comment by pvalsecc** [comment]
Same issue as: https://github.com/mapfish/mapfish-print/issues/589

**Comment by gnerred** [comment]
Thanks @pvalsecc . Any idea of the delay to solve this problem ?

**Comment by pvalsecc** [comment]
I don't know, @sbrunner just asked me if that ringed a bell and it did ;-)
He is working on it.

**Comment by gnerred** [comment]
Ok thanks ! What comes in my mind : you can ring my bee eeee eeeel, ring my bell ;-D

**Comment by gnerred** [comment]
Sorry to insist, but this issue is really a problem... Is there a solution to quickly fix ?

**Comment by sbrunner** [comment]
We just merge the print pull request, tomorrow we will do a new print release :-)

**Comment by gnerred** [comment]
Great thanks ! Could you please tell me how to integrate a new print release in GMF ?

**Comment by jwkaltz** [comment]
@gnerred it depends on your current version of gmf and your current version of mapfish-print. Could you please open a support ticket for that? (we will handle it quickly)

**Comment by gnerred** [comment]
Done

**Comment by pvalsecc** [comment]
OK, release 3.10.4 of the print is done, containing the fix for that. The maven repository is not completely up to date yet (takes a few hours to propagate), but you can already find the WAR here: http://central.maven.org/maven2/org/mapfish/print/print-servlet/3.10.4/print-servlet-3.10.4.war

**Comment by gnerred** [comment]
Great now it works, thanks
