### ISSUE TITLE
enumeratedAttributes could be calculated from layers enum settings

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cgeoportal#3153]
For now, in GMF 2.2 it seems it is need to manually enter for each layer the enumeratedAttributes metadata.
But it seems this could be deducted from layers enum settings.
And this seems to be right in all cases.

**Comment by arnaud-morvan** [comment]
@sbrunner : what do you think about this, do I miss something, can I propose a PR ?

**Comment by sbrunner** [comment]
Yes, +1 for a Pull reuest

**Comment by sbrunner** [comment]
Moved to Jira https://jira.camptocamp.com/browse/GSGMF-504
