### ISSUE TITLE
[doc] fix code formatting

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3185]
A few parts of our docu use code: instead of code:: to show code examples. These parts do not appear in the resulting html.

**Comment by sbrunner** [comment]
link ?

**Comment by jwkaltz** [comment]
I found two places, here is one: https://camptocamp.github.io/c2cgeoportal/master/integrator/internationalization.html
(top of the page).

But the fix is trivial - I will do it in a few minutes.
