### ISSUE TITLE
file .gitignore is fishy

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3204]
The .gitignore of the master contains too many files.
For sure, the doc files listed in the .gitignore should not be there (rst files, so source for the documentation).

I am not sure about files such as /geoportal/tests/functional/test.ini
Is is correct that they are in the .gitignore?

**Comment by sbrunner** [comment]
> For sure, the doc files listed in the .gitignore should not be there (rst files, so source for the documentation).

Do you have some examples?

`/geoportal/tests/functional/test.ini` should be in the `.gitignore` because he is generated from `geoportal/tests/functional/test.ini.mako`.

**Comment by jwkaltz** [comment]
Current master c2cgeoportal/.gitignore contains these doc files:
/doc/administrator/administrate.rst
/doc/developer/client_side.rst
/doc/index.rst
/doc/integrator/legacy_cgxp.rst
/doc/integrator/editing.rst
/doc/integrator/features.rst
/doc/integrator/fulltext_search.rst
/doc/integrator/print.rst
/doc/integrator/upgrade_application.rst

It looks like these were to .gitignore in this commit:
https://github.com/camptocamp/c2cgeoportal/commit/d304a9e5567f6b9c5bb07d3a0ca51602e595f3a6
Was this an accident?I see no reason why they should be in the .gitignore?

**Comment by jwkaltz** [comment]
Ah, is it because of the .mako files? :O

**Comment by sbrunner** [comment]
All those files are generated from mako files, than they should be in the `.gitignore`...

**Comment by jwkaltz** [comment]
Yes, of course... I did not realize that some files from the doc are generated via mako (others are not), sorry about that.
