### ISSUE TITLE
Display PostgreSQL errors in UI

### ISSUE THREAD

**Issue by julsbreakdown** [camptocamp/c2cgeoportal#3233]
Project:

* Repository URL :
The target project is https://github.com/camptocamp/aeroportdelyon_sig
But we will develop using "demo_geomapfish" : https://github.com/camptocamp/demo_geomapfish
* Server : gmf-test.infra.internal

* GeoMapFish version: 2.2

Description:

When a user submit new feature or changes to existing features, he'd like to see the exact error message from PostgreSQL constraints.

**Comment by sbrunner** [comment]
It seem to be fixed :-)

**Comment by sbrunner** [comment]
@julsbreakdown Why did you replace the label Ongoing by Ready?

**Comment by julsbreakdown** [comment]
Doesn't the ready label mean that the issue has been merged? Is not my bad

**Comment by sbrunner** [comment]
No, it's before we start working on it :-)
Standard workflow: 
Backog
->
Ready
->
Ongoing
->
Ongoing + close issue (Should be tested by the client)
->
Done (tested by the client) :-)

**Comment by julsbreakdown** [comment]
ah okay =)

On Tue, Nov 21, 2017 at 10:39 AM, Stéphane Brunner <notifications@github.com
