### ISSUE TITLE
CI / Infrastructure debug tools and documentation

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cgeoportal#3255]
To deal with continuous integration checks, we need:
* to understand precisely the infrastructure involved
* to be able to run tests locally, one test at a time, in the same environment as it is run in Travis or Jenkins. This need to be short and well documented.

# Docker / Travis / Jenkins

As I understand for now, we need to build docker image _geomapfish-build-dev_ only if we change something in docker/build : 
```
docker build --tag camptocamp/geomapfish-build-dev:2.3 docker/build
```
All python requitements are there, commons, geoportal and admin packages are installed with --no-deps from sources in a volume.

Run the build ?
```
docker-run make build
```
What does this do ? What are we building here ?

And run the tests locally:
```
./docker-compose-run make tests
```
Seems that we need to run prepare-tests before:
```
./docker-run make prepare-tests
```
What is the difference between docker-run and docker-compose-run ?
Why do we have 2 entry points ?

I'm used to run docker run myself.
How do I enter the container to check something  with bash or python ?

If I correctly understand, I should add pydevd in docker/build/requirements.txt to be able to debug with eclipse.

But we also need to run one test at a time, so after reading the `make tests` target, I've tried:
```
./docker-compose-run py.test -k test_get_class_nonexisting_table --cov=geoportal/c2cgeoportal_geoportal geoportal/tests
```
But seems that setup_common is not executed.
I do not understand setup_method, for me we use fixtures with pytest.

# Codacy

As Codacy green label is now required to merge, It would be more confortable to be able to debug it locally. As codacy use Pylint, it should be simple to run the same checks locally. Note that if we put a pylintrc file at root, Codacy should use it.

**Comment by arnaud-morvan** [comment]
@sbrunner: Note that GMF Admin developpers are not familiar with c2cgeoportal tests infrastructure, I'd like this to be clearer before commons and admin CI tests are merged with c2cgeoportal infrastructure.

**Comment by sbrunner** [comment]
Shouldn't it be in Jira?

**Comment by sbrunner** [comment]
Be able to run the test without init the database...

**Comment by arnaud-morvan** [comment]
in admin part we do it in the dbsession fixture : https://github.com/camptocamp/c2cgeoportal/blob/12804a35863a40b79760afeaf138cdc910638c18/admin/acceptance_tests/conftest.py#L21
which have a session scope (run only once for the tests session)

**Comment by arnaud-morvan** [comment]
So we have all time fresh schemas main and main_static in each pytest call.
