### ISSUE TITLE
Specify name and column seperator in csv export

### ISSUE THREAD

**Issue by julsbreakdown** [camptocamp/c2cgeoportal#3276]
Project:

Repository URL :
The target project is https://github.com/camptocamp/aeroportdelyon_sig
But we will develop using "demo_geomapfish" : https://github.com/camptocamp/demo_geomapfish

Server : gmf-test.infra.internal

GeoMapFish version: 2.2

Description:

Enable the user to change the default name of an exported csv.
Allow to change the seperator

**Comment by sbrunner** [comment]
In fact it's not a c2cgeoportal issue,
The view will just return what's she reserve in the `csv` query-string argument and the filename is in the `name` query-string argument, ngeo will probably not using the view...

**Comment by julsbreakdown** [comment]
If I understand, it is more of a ngeo issue?

**Comment by sbrunner** [comment]
Yes :-)
