### ISSUE TITLE
Lint jasper report files with xmllint

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/c2cgeoportal#3301]
It should be possible to lint the xmls as part of the migration process.
It would avoid client errors.

For example, with a wrongly closed tag:
```
gberaudo@kisvm7:/var/www/vhosts/planv4-dev/private/gberaudo/epfl_authgeoportail (c2cgeportail_upgrade $%)$ xmllint print/print-apps/**/*.jrxml > /dev/null
print/print-apps/epfl_authgeoportail/A3_Landscape.jrxml:156: parser error : expected '>'
                                <subreportExpression><![CDATA[$P{legendSubReport}]]></subreportExpression>
```

It might also be possible to validate the xmls (if we have the jasper reports dtd).

https://community.jaspersoft.com/questions/504123/jasperreports-dtd-system-vs-public they say the dtd exists and should be extracted from the jar file.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-505
