### ISSUE TITLE
GMF 2.2 - Session Management

### ISSUE THREAD

**Issue by svagap** [camptocamp/c2cgeoportal#3328]
We had several issues with the update (first from 1.6 to 2.1) and lately with the update from 2.1 to 2.2 and Database Sessions.

We changed the DB Session definition according to: https://camptocamp.github.io/c2cgeoportal/master/integrator/multiple_databases.html?highlight=dbsessions

and "used" the sessions in our "own" python code. Now several problems occour:

A) We had (in our own python code) that the objects loaded from Database were not "in Memory anymore.
B) We had to change our code from session.flush() to session.commit() (from 2.1 to 2.2)
C) there seams to be more DB-Connections open then necessary
D) the sessions seams to "lock" tables (even only data selection occoured)
E) the sessions dont close "automaticaly"

So, what is the correct way to 
i) select data from db in "our" own python code
ii) modify data to db in "our" own python code (using transaction / session close? etc)

**Comment by sbrunner** [comment]
Should be reported on Jira as support issue
