### ISSUE TITLE
502 Bad Gateway during upgrade to 2.2.1

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3329]
* GeoMapFish version: 2.1.11 > 2.2.1

Running command: `$ make -f instance_dev.mk upgrade5`

Result:

```
.build/venv/bin/c2ctool upgrade  instance_dev.mk 2.2.1 --step 5

================================================================
Checker error:
Open `wsgi/check_collector?` for more informations.
Correct the checker, the it again:
make -f instance_dev.mk upgrade5
CONST_Makefile:1295: recipe for target 'upgrade5' failed
make: *** [upgrade5] Error 1
```

And the checker returns:

```
502 Bad Gateway Bad gateway. GetCapabilities from URL http://localhost/dev/mapserv?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS returns a wrong Content-Type: text/html msLoadMap(): Unknown identifier. Parsing error near (role_id):(line 1621)
```

When I try to get the GetCap:

```
502 Bad Gateway

Bad gateway.

WARNING! an error occurred while trying to read the mapfile and recover the themes. url: http://localhost/dev/mapserv?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS xml: <HTML> <HEAD><TITLE>MapServer Message</TITLE></HEAD> <!-- MapServer version 7.0.6 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE --> <BODY BGCOLOR="#FFFFFF"> msLoadMap(): Unknown identifier. Parsing error near (role_id):(line 1621) </BODY></HTML>
```

How can I see the line 1621 knowing that I use a lot of mapfiles includes?

**Comment by ochriste** [comment]
the only way I know is to comment the map's INCLUDE iteratively until you find which one is the culprit

**Comment by ochriste** [comment]
you can do that directly in the c2cgeoportal.map without rebuilding the projet to regenerate the .map,
simple do some manual apache graceful

**Comment by rbovard** [comment]
Thanks for the tip @ochriste, I get the guilty one in https://github.com/camptocamp/nyon_c2cgeoportal/blob/master/mapserver/mapfiles/reseaux_souterrains.map.mako

To let you knwo where I am now, it's probably related to restriction area:
```
WHERE ST_Intersects((${mapfile_data_subselect} ...
```

But it's strange because the first ones works in `reseau_eau.map` but not in `reseau_electricite.map`

**Comment by ochriste** [comment]
what does your generated reseaux_souterrains.map look like ?

**Comment by rbovard** [comment]
The same as `reseaux_souterrains.map.mako`.

After more "commenting" investigations it's in https://github.com/camptocamp/nyon_c2cgeoportal/blob/master/mapserver/mapfiles/reseau_electricite_coupes.map.mako

**Comment by rbovard** [comment]
**I GOT IT!**

I have a commented layer in this file:

```
#    VALIDATION
#        ${mapserver_layer_validation}
#    END
```

And when the mapfile is generated, the result is:

```
#    VALIDATION
#        "default_role_id" "-1"
"role_id" "^-?[0-9]*$"

#    END
```

Now the question is: why does this error was not in 2.1? Did you changed something there?

**Comment by ochriste** [comment]
im pretty sure this behavior exists since the beginning of GeoMapfish as I remember having dealt with it every now and then since we have been working on it.

**Comment by rbovard** [comment]
It's strange, my config which is currently in prod returns a correct GetCap...

**Comment by rbovard** [comment]
In my prod:

````
#    VALIDATION
#        "default_role_id" "-1" "role_id" "^-?[0-9]*$"
#    END
```

So something has changed!

**Comment by ochriste** [comment]
I will ask @sbrunner

**Comment by sbrunner** [comment]
For me it's buggy in 2.1, If you relay want this you should add this in your vars file...
```yaml
     mapserver_layer_validation: '"default_role_id" "-1" "role_id" "^-?[0-9]*$"'
```

**Comment by rbovard** [comment]
I never touched this value.

https://github.com/camptocamp/nyon_c2cgeoportal/blob/master/CONST_vars.yaml#L47

And the mako are the same...

Nothing new about newlines in 2.2 compared to 2.1?

**Comment by yjacolin** [comment]
I agree with @ochriste about the existing behaviour of mapfile comment for ${mapserver_layer_validation} in previous release. I have no doubt about this!

**Comment by rbovard** [comment]
Ok, very strange... To bypass it, I removed the commented secure layer and it works.

If it's ok for you, you can close it.

**Comment by rbovard** [comment]
@ochriste @yjacolin FYI Something had changed here... https://github.com/camptocamp/c2cgeoportal/commit/9b3f23c1789b156c8a17fb1312eb0efd300051cb
