### ISSUE TITLE
[Security Issue] WMS acces of non accessible Layers

### ISSUE THREAD

**Issue by svagap** [camptocamp/c2cgeoportal#3348]
On the test server we can reproduce it on the layers firestations and hospitals...

https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?ogcserver=Main+PNG&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=firestations&SERVERTYPE=mapserver&CRS=EPSG%3A21781&STYLES=&WIDTH=1521&HEIGHT=791&BBOX=533625.0082555609%2C147257%2C548835.0082555609%2C155167
=> error
https://geomapfish-demo.camptocamp.net/2.2/wsgi/mapserv_proxy?ogcserver=Main+PNG&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=hospitals&SERVERTYPE=mapserver&CRS=EPSG%3A21781&STYLES=&WIDTH=1521&HEIGHT=791&BBOX=533625.0082555609%2C147257%2C548835.0082555609%2C155167
=> get a non empty result

<s>When printing with the default print functionality, one can manipulate the print request and add Layer(names) of layers normaly not accesseable. The print functionality does not check if the user has access to the layer and add them to printing output without checking access right.</s>

**Comment by sbrunner** [comment]
You succeed to do that, because it should be impossible ...

**Comment by svagap** [comment]
It is possible, at least on our GMF installation. If I would know a "secret" Layername on demo I could try to reproduce on your Demo. How can I proof it is possible? 

How can I support my claim? What Info would be helpfull?

**Comment by sbrunner** [comment]
What's your "secet" layer name?
To see how you configure it
Do you configure it in the database as private?
Do You use the mapserver or the mapserv_proxy URL to do your test?

**Comment by svagap** [comment]
I used the layer "LK_SIA405_Unterirdisch_Wasser_Linie_Kanal" as test (https://github.com/camptocamp/baselstadt_mapbs/blob/1a55b203ca1ad2a0187cbb60c77f20f90178f1c9/mapserver/include/LK_SIA405_LKMap_unterirdisch.map.mako#L73)
In the admin tool it looks like this:
![lk_sia405_unterirdisch_wasser](https://user-images.githubusercontent.com/29245949/34257053-806acc3e-e658-11e7-8a70-2bbc05745713.PNG)

Yes, in the Database it is "not public" (-> private?)

I used http://map.geo.bs.ch/main/wsgi/printproxy/report.pdf (the request done by the "default" printing functionality and modified the payload as follow (replace layername of "public" layer by the layername of "private" layer):

{"layout":"A4 Hochformat","outputFormat":"pdf","attributes":{"title":"","comment":"","map":{"projection":"EPSG:2056","dpi":254,"rotation":0,"center":[2611281.3015176,1267675.4994941],"scale":750,"longitudeFirst":true,"layers":[{"baseURL":"http://map.geo.bs.ch/main/wsgi/mapserv_proxy?cache_version=34bf287d261743bfa9f6be6252d77e4c","opacity":1,"type":"wms","layers":["**LK_SIA405_Unterirdisch_Wasser_Linie_Kanal**"],"imageFormat":"image/png","styles":[""],"customParams":{"TRANSPARENT":true},"useNativeAngle":true,"serverType":"mapserver"},{"baseURL":"http://map.geo.bs.ch/main/wsgi/mapserv_proxy?cache_version=34bf287d261743bfa9f6be6252d77e4c","opacity":1,"type":"wms","version":"1.0.0","imageFormat":"image/png","layers":["Parzellenplan_Bodenbedeckung_farbig"],"useNativeAngle":true,"serverType":"mapserver"},{"baseURL":"http://map.geo.bs.ch/main/wsgi/mapserv_proxy?cache_version=34bf287d261743bfa9f6be6252d77e4c","opacity":1,"type":"wms","version":"1.0.0","imageFormat":"image/png","layers":["SP_Stadtplan_farbig_Baselayer"],"useNativeAngle":true,"serverType":"mapserver"}]}}}

**Comment by svagap** [comment]
It looks like I can also make a wms (mapserv_proxy) request to get private layer

**Comment by ochriste** [comment]
@svagap please could you enable your database query logs and give us the queries done on the database when you trigger the pdf generation ?
im especially interested by the query for the layer LK_SIA405_Unterirdisch_Wasser_Linie_Kanal
thank you

**Comment by ochriste** [comment]
@svagap please ignore my last comment,
we could reproduce the problem,
we will correct this asap

**Comment by sbrunner** [comment]
On the test server we can reproduce it on the layers firestations and hospitals...

**Comment by ger-benjamin** [comment]
Because the getmap is never rejected: https://github.com/camptocamp/c2cgeoportal/blob/2.2/c2cgeoportal/views/mapserverproxy.py#L157

(But data can't be viewed)

**Comment by sbrunner** [comment]
After a second test I fount that not possible to reproduce on mapserv_proxy,
but throw the print it's probably fixed by this pull request: https://github.com/mapfish/mapfish-print/pull/626 (included in print version 3.10.5), then for me we can close this issue

**Comment by jwkaltz** [comment]
@svagap since we updated the print at BS, you should no longer see this behavior in the print in your project, can you confirm?

**Comment by svagap** [comment]
sorry did not see your comment. 

Yes, it seams to fix the problem. Could not get the print to get "private" layers
