### ISSUE TITLE
Ignored enumeratedAttributes if multiple one on a layer

### ISSUE THREAD

**Issue by llienher** [camptocamp/c2cgeoportal#3358]
Issue related to GMF 2.2 and beyond.

Using and testing filters I found that any enums that are refered in the yaml config file are not requested if the list is superior to one enum (when requested on a single layer, at least).

First I had two enums defined in the vars_project.yaml file (let's call it A and B). In administration, under Functionality, I have one with key/value 'EnumerateAttributes/A,B. That way I listed both under the same layer.

Now there were different behaviours:
- Are listed in that order in the .yaml: Enum A, then Enum B. GMF requested only A, ignoring B request. UI displays both, correctly.
- Are listed in that order in the .yaml: Enum B, then Enum A. GMF requested only B, ignoring A request. UI displays both, correctly.
- With only one value in admin, works as excepted. UI displays one, correctly.

**Comment by ger-benjamin** [comment]
I found that the bug is in the ngeo side.
I close this issue and continue here: https://github.com/camptocamp/ngeo/issues/3365
