### ISSUE TITLE
Filter: public layer not shown when logged in

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3374]
When a user is logged in, the public layers no longer appear in the filter selection dropdown.

Verified as follows on our Demo https://geomapfish-demo.camptocamp.net/2.2/
- open https://geomapfish-demo.camptocamp.net/2.2/?lang=en&tree_groups=Transport&tree_group_layers_Transport=fuel&baselayer_ref=OSM%20map , without login
- Choose filter icon. Under Filter, "OSM map" is available
- do a login with demo user
- choose filter icon. Message "No filtrable layer available!" appears.

Expected result: filterable public layers are always available for filtering, regardless of whether the user is logged in.

Note: issue first found by BS on their installation (https://jira.camptocamp.com/browse/GEO-874).

**Comment by sbrunner** [comment]
The login user has the filterable layers as: firestations, hospitals
and the anonymous user as:  osm_open, OSM map, osm_time_r_dp_2

Then this comportment is correct...
