### ISSUE TITLE
Log warning "CORS query not allowed" when using default settings

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3400]
When using the default settings of c2cgeoportal 2.1 or 2.2, the following warning may appear in the logs when a user does a login in the portal: "CORS query not allowed for origin=(host name), service=login"

**Comment by jwkaltz** [comment]
Fixed in https://github.com/camptocamp/c2cgeoportal/pull/3399

**Comment by rbovard** [comment]
Thanks @jwkaltz
