### ISSUE TITLE
Weak password hashing

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/c2cgeoportal#3414]
Project: All

* GeoMapFish version: master

The current password hashing is implemented there: https://github.com/camptocamp/c2cgeoportal/blob/master/commons/c2cgeoportal_commons/models/static.py#L171

As you can see, there is not seed and this is a bad security practice.

We should use the python `crypt` module to do proper password hashing instead. We could still support the current format by detecting it (it doesn't start with a `$`).

**Comment by gberaudo** [comment]
@pvalsecc, is it the same as bcrypt?

**Comment by gberaudo** [comment]
Hmm, no that looks different.
We are using bcrypt in c2corg (almost the same code as c2cgeoportal if I remember well). See https://github.com/c2corg/v6_api/blob/87aee209c5a254c5388c247210cec732449fa582/c2corg_api/models/user.py#L43.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-527
