### ISSUE TITLE
2.2.2 - Trailing slash in request.route_url

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#3446]
When defining `module.constant('gmfLayersUrl', '${request.route_url('layers_root') | n}');` in desktop.html, this produce an URL with a trailing slash:

![image](https://user-images.githubusercontent.com/1681332/36314816-3f9e7d1c-1336-11e8-91f8-03087adcab12.png)

This generates an error:

![image](https://user-images.githubusercontent.com/1681332/36314895-7e4c28f2-1336-11e8-94c2-b6dc13c52ef3.png)

If I (manually) remove this slash (http://localhost:5000/layers), then it works .

Is there a way to correct that ?

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-506
