### ISSUE TITLE
[Print] Labels disappear if there is conflict

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3456]
* Host: geomapfish-demo
* GeoMapFish version: 2.2
* MapFish Print: 3.x

Labels disappear if there is conflict with *MFP3* (it was not the case with *MFP2*), see [here](https://geomapfish-demo.camptocamp.net/2.2/theme/Transport?lang=fr&tree_groups=Transport&tree_group_layers_Transport=&baselayer_ref=OSM%20map&map_x=533692&map_y=153007&map_zoom=3&rl_features=Fa(hef4Fsjyw_1ea-1w8_h4r_z80g3r-g9g-~n*Polygone%25201%27c*%2523DB4436%27a*0%27o*0.2%27m*true%27b*false%27s*10%27k*2)p(h896F97yx_~t*true%27n*Texte%25202%27c*%2523000000%27a*0%27o*0.2%27m*false%27b*false%27s*10%27k*2)).

Note: I can reproduce it with cgxp interface as well.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-528
