### ISSUE TITLE
[Print] Cannot print external WMS layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3463]
* Host: geomapfish-demo
* GeoMapFish version: 1.6 (to have external WMS browser)
* MapFish Print: 3.x

Steps to reproduce:
* Open https://geomapfish-demo.camptocamp.net/1.6/
* Add an external WMS layer (for instance `http://wms.geo.admin.ch` > `Stand der amtlichen Vermessung`
* Print

Result:

```
org.mapfish.print.ExtraPropertyException: Extra properties were found in the request data at: spec.attributes.map.layers[0]: 
Extra Properties: 

	* maxScaleDenominator

All allowed properties are: 

	* imageFormat
	* tileSize
	* layers
	* baseURL
	* styles
	* rasterStyle
	* failOnError
	* version
	* serverType
	* customParams
	* name
	* mergeableParams
	* opacity
	* useNativeAngle
```

**Comment by sbrunner** [comment]
Fixed in ngeo
