### ISSUE TITLE
OGC proxy limitation

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#350]
On <a href="https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/__init__.py#L102-111" target=_blank>lines 102-111 of `__init__.py`</a>, isn't there an other way round to test if ogcproxy is used to reach mapserv ?? Because if you use this as it is, then we won't be able to use URLs like the following one:

<a href="http://ogc.heig-vd.ch/mapserver/wms?" target=_blank>`http://ogc.heig-vd.ch/mapserver/wms?`</a>

**Comment by ybolognini** [comment]
OGC proxy no more needed
