### ISSUE TITLE
Could not find a version that satisfies the requirement c2cwsgiutils

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3523]
Project:

* GitHub URL: https://github.com/camptocamp/nyon_c2cgeoportal
* GeoMapFish version: 2.2.2

Running command: `make -f my.mk build`

Result:

```
Could not find a version that satisfies the requirement c2cwsgiutils (from tilecloud-chain->nyon==1.0) (from versions: )
No matching distribution found for c2cwsgiutils (from tilecloud-chain->nyon==1.0)
```

Did something change here, because I haven't done anything on my side...

**Comment by rbovard** [comment]
Any news on this one? I cannot build my instance...

**Comment by sbrunner** [comment]
Fro me the requirement in the `setup.py`
https://github.com/camptocamp/nyon_c2cgeoportal/blob/master/setup.py#L18-L22
should be empty or just contains c2cgeoportal.
in this case you specify tilecloud_chain with any version,
then he download the latest version,
who had a new dependency on c2cwsgi_utils,
And for actually a unknown reason he isn't downloadable...

**Comment by rbovard** [comment]
Ok, thanks for the info.

So in my case as quick workaround, I could just specify the latest stable version of tilecloud, right? If yes, what was this version number?

**Comment by sbrunner** [comment]
No you should remove the requirement, the makfile will automatically install the right version :-)
Specified in `CONST_optional-requirements.txt` :-)

**Comment by rbovard** [comment]
Ok, it solved it. Thanks.

I let you choose if this issue can be closed or not.

**Comment by sbrunner** [comment]
Cool :-)
