### ISSUE TITLE
Referer check don't works on non flush mode on dev instance

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#3676]
authorised referer: https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz/
used referer: https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz?lang=de&baselayer_ref=ch.swisstopo.pixelkarte-grau

Should be considered as valid but it's not...

**Comment by jwkaltz** [comment]
@sbrunner we can close this, right?

**Comment by sbrunner** [comment]
Effectively, closed :-)
