### ISSUE TITLE
Short link failing with authenticated user

### ISSUE THREAD

**Issue by brossardm** [camptocamp/c2cgeoportal#3701]
# Project:

* GitHub URL: https://github.com/camptocamp/demo_geomapfish/tree/2.2
* Host: https://geomapfish-demo.camptocamp.net/2.2/
* GeoMapFish version: 2.2.2

# Running command: 
* ask for a short link
  * the window appears with the shortlink
* login in the interface as admin
* ask for a short link

# Result:

The window appears with no shortlink and and timeout appear with:  Erreur, impossible d'obtenir l'URL réduite. 

![selection_013](https://user-images.githubusercontent.com/11328768/39045433-36dd68bc-4493-11e8-969d-1b3f7f9cfc1e.png)

**Comment by pfirpfel** [comment]
I think, I found the cause:
If you remove the email_body property inside the shortener property of your vars file, the shortener works again. There seems to be an issue with this multi-line syntax. The password reset mechanism seems to be affected as well.

**Comment by sbrunner** [comment]
Done
