### ISSUE TITLE
Development.ini for pserve

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#3712]
Is there a reason to have removed the main section (https://github.com/camptocamp/c2cgeoportal/blob/2.2/c2cgeoportal/scaffolds/create/development.ini.mako_tmpl#L38-L41) in the `development.ini` template of version 2.3 ?

By doing so, `pserve` cannot be used anymore (and this was quite useful for us...)

**Comment by sbrunner** [comment]
It's made for Docker where it's obsolete, no other reason :-)

**Comment by kalbermattenm** [comment]
Oh... Right... Thanks for your answer (I added it again in my project and it is working again, for a non-docker upgrade)
