### ISSUE TITLE
foreign key column name is too restrictive

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3810]
Since GMF 2.2.1, the column name of a foreign key must contain "_id", because of the implementation of lingua_extractor.py

This is too restrictive, and in contradiction of the documentation here: https://camptocamp.github.io/c2cgeoportal/2.2/administrator/editing.html?highlight=foreign%20key#requirements

There should be no restriction on the naming of a foreign key column.

**Comment by sbrunner** [comment]
Here we can use forain key that's not ends with '_id'
https://github.com/camptocamp/c2cgeoportal/blob/2.3/geoportal/c2cgeoportal_geoportal/lib/dbreflection.py#L215

But here it's not the case:
https://github.com/camptocamp/c2cgeoportal/blob/2.3/geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py#L436-L437

**Comment by ybolognini** [comment]
Done
