### ISSUE TITLE
Scrolling on HTC devices

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#384]
There is a problem with scrollong lists on HTC phones and Android. Sometimes the screen freezes, and the scolling is not fluent. To test : 

1°/ Get a HTC mobile phone :O)
2°/ Go to http://preprod.cartoriviera.ch/preprod/wsgi/mobile_dev/
3/° Select backgroundlayer "Plan cadastral" and zoom in a litle
4°/ Do a long touch query, to get a lot of results
5°/ Try scrolling in the results list

**Comment by sbrunner** [comment]
The mobile app will be replaced by ngeo => abandoned...
