### ISSUE TITLE
Create application: the default version in the script is the next stable

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/c2cgeoportal#3890]
In http://camptocamp.github.io/c2cgeoportal/2.3/integrator/create_application.html#list-existing-scaffolds

The following command line: `./docker-run --image=camptocamp/geomapfish-build pcreate -l` download the last GMF release (aka currently 2.4).

The doc should either linked to `https://raw.githubusercontent.com/camptocamp/c2cgeoportal/**<branche>**/docker-run` in the previous section or add the --version parameter to the docker-run command.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-569
