### ISSUE TITLE
GMF 2.3.1 missing ol.js in admin

### ISSUE THREAD

**Issue by monodo** [camptocamp/c2cgeoportal#3897]
**GMF 2.3.1**

In admin interface, ol.js script does not get loaded what causes the map not to appear when editing a restriction area. 

**Project: yverdon_geoportal**

* GitHub URL:  c2c yverdon_geoportal
* Infrastructure description URL: c2c/exoscale
* Host: https://gmf23-mapnv.preprod.sig.cloud.camptocamp.com/preprod/ 
* GeoMapFish version: 2.3.1

Échec du chargement pour l’élément <script> dont la source est « https://gmf23-mapnv.preprod.sig.cloud.camptocamp.com/preprod/wsgi/admin/node_modules_for_outsider/openlayers/dist/ol.js ». 16:51
[Afficher/Masquer les détails du message.] ReferenceError: ol is not defined[En savoir plus]

**Comment by yjacolin** [comment]
Same problem in demo geomapfish. See console log with https://geomapfish-demo.camptocamp.com/2.3/wsgi/admin/restriction_areas/5
