### ISSUE TITLE
BUG with some devices on iOS 6

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#398]
There is a serious problem with mobile application and some devices on iOS 6 -> the application does not load, and hangs with the animation of the three white points.  Since we officially published our Cartoriviera mobile application, I had several user feedback with this problem. More info : 

- iPad 2 and iOS 6 -> OK
- iPhone 3 and iOS 6 -> OK
- iPhone 4 and iOS 6 -> sometimes OK, and sometimes BUG
- iPhone 4S and iOS 6 -> sometimes OK, and sometimes BUG
- iPhone 5 and iOS 6 -> BUG
- To reproduced : http://map.cartoriviera.ch/wsgi/mobile/ or http://sitn.ne.ch/sitn_dev/wsgi/mobile/
- With dev mode, all is OK and the bug disappears (..../mobile_dev/)
- Impossible de reproduce the problem on BrowserStack, all is OK on that emulator...

Unfortunatly, a lot of users work with these "bad" configurations above... 

Thanks

**Comment by sbrunner** [comment]
The mobile app will be replaced by ngeo => abandoned...
