### ISSUE TITLE
URL of 1.6 documentation is dead

### ISSUE THREAD

**Issue by vvmruder** [camptocamp/c2cgeoportal#5227]
Following the link to documentation of package in branch 1.6 leads to dead end. Can you please fix?

Path of file is:
https://github.com/camptocamp/c2cgeoportal/blob/1.6/README.rst

**Comment by kalbermattenm** [comment]
Meanwhile, if you really need the doc, then : https://camptocamp.github.io/c2cgeoportal/1.6/

**Comment by vvmruder** [comment]
Thanks! I opened a PR. :+1:

**Comment by ponceta** [comment]
@vvmruder if it's ok for you we can close this.

**Comment by vvmruder** [comment]
Yes. Sorry I forgot about that.
