### ISSUE TITLE
shouldn't this be `self.server_iface` instead of `server_iface`?

### ISSUE THREAD

**Issue by danduk82** [camptocamp/c2cgeoportal#5590]
Hi @sbrunner ,
I was just reading the code of geomapfish_qgisserver and was wondering if this line is correct:

https://github.com/camptocamp/c2cgeoportal/blob/016369036b4d6a201a241485ca0bc34e5e9c598e/docker/qgisserver/geomapfish_qgisserver/accesscontrol.py#L94

or if it should refer to `self.server_iface` instead. Or is the reference enough?

**Comment by sbrunner** [comment]
Upper we see:
```
self.server_iface = server_iface
```
Then booth have the same value...
