### ISSUE TITLE
Mobile - Problem with navigation on Samsung Android tablet

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#562]
On my Samsung Galaxy tab 10.1 N, there is a problem with the display of map when navigating (the map moves in several unwanted directions)

- Model Samsung Galaxy tab 10.1 N
- OS : Android 3.2

Reproduced on http://map.cartoriviera.ch and on http://sitn.ne.ch/sitn_dev/wsgi/mobile/?debug=true

To see the problem : http://www.cartoriviera.ch/web/temp/C2Cmobile_samsung_android.MOV

Any idea ?

**Comment by sbrunner** [comment]
The mobile app will be replaced by ngeo => abandoned...
