### ISSUE TITLE
Update c2cgeoportal to be PostGIS 2.1 compatible

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#757]
As discussed with @bquartier, this is a (really) long term question that we should ask ourselves...

Notably concerning:
* Egg (GeoAlchemy / c2cgeoportal / other?) compatibility
* User requirements and limitations

I think that it is quite early to ask this question... But we might go 3D in the coming months (and for that it is much much better to use PostGIS 2.1...)

**Comment by sbrunner** [comment]
done
