### ISSUE TITLE
Mobile - Desktop app does not load on iPad some times

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#775]
Related to https://github.com/camptocamp/c2cgeoportal/issues/528

Some times, desktop app does not load on some iPads, because of the too big size of app.js file. What can be done to split this file ? @kalbermattenm proposed to get Ext out of app.js. Thanks

**Comment by sbrunner** [comment]
The mobile app will be replaced by ngeo => abandoned...
