### ISSUE TITLE
Docs: Demo for 2.7 offline

### ISSUE THREAD

**Issue by almereyda** [camptocamp/c2cgeoportal#8128]
The documentation page at https://camptocamp.github.io/c2cgeoportal/master/, built from this repository, links to two demo applications

- https://geomapfish-demo-2-7.camptocamp.com/
- https://geomapfish-demo-2-7.camptocamp.com/desktop_alt

which aren't currently accessible.

**Comment by sbrunner** [comment]
Effectively, the development of the 2.7 didn't start, you should use the demo 2.6 https://camptocamp.github.io/c2cgeoportal/2.6/ :-)

**Comment by almereyda** [comment]
Intricate!
