### ISSUE TITLE
Mobile - OL buttons on Chrome

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#944]
A client just reported us that the OpenLayers buttons on the mobile app do not work when using Chrome (version unknown) on a Samsung S4. (the click action does not trigger anything)

I did test it on Chrome on a Samsung Galaxy express and a Samsung S4 mini express. On these ones, it worked as expected.

It's a bit a "light" issue as I cannot reproduce the problem... I just hope that it won't appear on other devices...

**Comment by rbovard** [comment]
@sbrunner Is it possible to merge #1160 into 1.5 `branch`? We aim to deploy Android tablets with Chrome as browser...

Ping @tczaka
