### ISSUE TITLE
Regex metadata type not available in themes.

### ISSUE THREAD

**Issue by mki-c2c** [camptocamp/c2cgeoportal#9473]
Regex type can be used as a metadata type ([definition](https://github.com/camptocamp/c2cgeoportal/blob/472345146e96c75e30380a911129fe86d8a052d8/admin/c2cgeoportal_admin/schemas/metadata.py#L107) - [example](https://github.com/camptocamp/c2cgeoportal/blob/472345146e96c75e30380a911129fe86d8a052d8/admin/config.yaml#L311))

However theme generation uses [get_typed() to retrieve metadata](https://github.com/camptocamp/c2cgeoportal/blob/472345146e96c75e30380a911129fe86d8a052d8/geoportal/c2cgeoportal_geoportal/views/theme.py#L170), but get_typed does not support regex type (see [here](https://github.com/camptocamp/c2cgeoportal/blob/472345146e96c75e30380a911129fe86d8a052d8/geoportal/c2cgeoportal_geoportal/lib/__init__.py#L113))

==> therefore regex type metadata does not appear in theme tree

Jira ticket : https://jira.camptocamp.com/browse/GSGMF-1789

**Comment by arnaud-morvan** [comment]
Done by https://github.com/camptocamp/c2cgeoportal/pull/9575 (2.7 and master)
